"""Bid requirements + compliance intelligence vocabulary.

Coexists with requirement_register / solicitation_package / deal_readiness —
does not replace them.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Document types (package map)
# ---------------------------------------------------------------------------
DOC_SOLICITATION = "SOLICITATION"
DOC_RFQ = "RFQ"
DOC_RFP = "RFP"
DOC_IFB = "IFB"
DOC_SOW = "STATEMENT_OF_WORK"
DOC_SPEC = "PRODUCT_SPECIFICATION"
DOC_PRICING = "PRICING_SCHEDULE"
DOC_BID_SCHEDULE = "BID_SCHEDULE"
DOC_AMENDMENT = "AMENDMENT"
DOC_QA = "Q_AND_A"
DOC_INSTRUCTIONS = "BIDDER_INSTRUCTIONS"
DOC_TERMS = "TERMS_AND_CONDITIONS"
DOC_REPS = "REPRESENTATIONS_CERTIFICATIONS"
DOC_FORMS = "REQUIRED_FORMS"
DOC_DRAWING = "DRAWING"
DOC_TECH = "TECHNICAL_ATTACHMENT"
DOC_DELIVERY = "DELIVERY_SCHEDULE"
DOC_HISTORICAL = "HISTORICAL_REFERENCE"
DOC_UNKNOWN = "UNKNOWN"

GOVERNING_DOC_TYPES = frozenset(
    {
        DOC_SOLICITATION,
        DOC_RFQ,
        DOC_RFP,
        DOC_IFB,
        DOC_SOW,
        DOC_SPEC,
        DOC_PRICING,
        DOC_BID_SCHEDULE,
        DOC_AMENDMENT,
        DOC_QA,
        DOC_INSTRUCTIONS,
        DOC_TERMS,
        DOC_REPS,
        DOC_FORMS,
        DOC_DELIVERY,
        DOC_TECH,
    }
)

REFERENCE_ONLY_DOC_TYPES = frozenset({DOC_HISTORICAL, DOC_DRAWING})

# Document authority / requirement authority states
AUTH_GOVERNING = "GOVERNING"
AUTH_NON_GOVERNING = "NON_GOVERNING"
AUTH_REFERENCE = "REFERENCE_ONLY"
AUTH_UNKNOWN = "UNRESOLVED_AUTHORITY"

REQ_ACTIVE = "ACTIVE_REQUIREMENT"
REQ_SUPERSEDED = "SUPERSEDED_REQUIREMENT"
REQ_HISTORICAL = "HISTORICAL_REQUIREMENT"
REQ_CONFLICTING = "CONFLICTING_REQUIREMENT"
REQ_UNRESOLVED_AUTH = "UNRESOLVED_AUTHORITY"
REQUIREMENT_CONFLICT = "REQUIREMENT_CONFLICT_REQUIRES_RESOLUTION"

# ---------------------------------------------------------------------------
# Requirement categories (minimum set from mission)
# ---------------------------------------------------------------------------
REQUIREMENT_CATEGORIES = (
    "PRODUCT",
    "QUANTITY",
    "TECHNICAL_SPECIFICATION",
    "BRAND_OR_EQUAL",
    "EXACT_BRAND_REQUIRED",
    "OEM_REQUIREMENT",
    "AUTHORIZED_RESELLER",
    "AUTHORIZED_DISTRIBUTOR",
    "MANUFACTURER_AUTHORIZATION",
    "COUNTRY_OF_ORIGIN",
    "DOMESTIC_CONTENT",
    "BUY_AMERICAN",
    "TRADE_AGREEMENTS",
    "CERTIFICATION",
    "TESTING",
    "SAMPLE",
    "WARRANTY",
    "SUPPORT",
    "DELIVERY_DATE",
    "DELIVERY_LOCATION",
    "FREIGHT",
    "INSTALLATION",
    "TRAINING",
    "ASSEMBLY",
    "PACKAGING",
    "LABELING",
    "SERIAL_NUMBER",
    "LOT_OR_BATCH",
    "SUBSTITUTION",
    "ALTERNATE_PRODUCT",
    "BIDDER_QUALIFICATION",
    "PAST_PERFORMANCE",
    "EXPERIENCE",
    "LICENSE",
    "INSURANCE",
    "BOND",
    "REGISTRATION",
    "SAM_REGISTRATION",
    "STATE_VENDOR_REGISTRATION",
    "PORTAL_REGISTRATION",
    "SMALL_BUSINESS",
    "SET_ASIDE",
    "SOCIOECONOMIC_REQUIREMENT",
    "NAICS",
    "SIZE_STANDARD",
    "REPRESENTATION",
    "CERTIFICATION_FORM",
    "PRICING_FORM",
    "SIGNATURE",
    "NOTARIZATION",
    "ACKNOWLEDGEMENT",
    "AMENDMENT_ACKNOWLEDGEMENT",
    "Q_AND_A",
    "SUBMISSION_METHOD",
    "SUBMISSION_PORTAL",
    "SUBMISSION_EMAIL",
    "SUBMISSION_ADDRESS",
    "SUBMISSION_FORMAT",
    "FILE_FORMAT",
    "PAGE_LIMIT",
    "NAMING_CONVENTION",
    "BID_DEADLINE",
    "QUESTION_DEADLINE",
    "SITE_VISIT",
    "PREBID_MEETING",
    "BID_SECURITY",
    "PAYMENT_TERMS",
    "EVALUATION_METHOD",
    "AWARD_BASIS",
    "LPTA",
    "BEST_VALUE",
    "MULTIPLE_AWARD",
    "ALL_OR_NONE",
    "PARTIAL_AWARD",
    "OPTION",
    "RENEWAL",
    "CANCELLATION",
    "TERMS_AND_CONDITIONS",
    "OTHER_MANDATORY",
    "OTHER_INFORMATIONAL",
)

# Severity
SEV_INFORMATIONAL = "INFORMATIONAL"
SEV_PREFERENCE = "PREFERENCE"
SEV_CONDITIONAL = "CONDITIONAL"
SEV_MANDATORY = "MANDATORY"
SEV_MANDATORY_MATERIAL = "MANDATORY_MATERIAL"
SEV_HARD_BLOCKER = "HARD_BLOCKER_IF_UNSATISFIED"

# Compliance matrix statuses
ST_SATISFIED = "SATISFIED"
ST_LIKELY = "LIKELY_SATISFIED"
ST_UNRESOLVED = "UNRESOLVED"
ST_RESEARCH = "RESEARCH_REQUIRED"
ST_DOCUMENT = "DOCUMENT_REQUIRED"
ST_FUTURE = "FUTURE_ACTION_IF_PURSUED"
ST_NA = "NOT_APPLICABLE"
ST_CONFLICTING = "CONFLICTING"
ST_UNSATISFIED = "UNSATISFIED"
ST_BLOCKED = "BLOCKED"
ST_SUPERSEDED = "SUPERSEDED"

# Company mapping
CO_KNOWN_SATISFIED = "KNOWN_SATISFIED"
CO_KNOWN_UNSATISFIED = "KNOWN_UNSATISFIED"
CO_UNKNOWN = "UNKNOWN"
CO_FUTURE = "FUTURE_ACTION_IF_PURSUED"

# Product compliance
PROD_EXACT = "EXACT_MATCH"
PROD_EQUIV = "COMPLIANT_EQUIVALENT"
PROD_LIKELY = "LIKELY_COMPLIANT"
PROD_SPEC_GAP = "SPEC_GAP"
PROD_DOC_GAP = "DOCUMENTATION_GAP"
PROD_AUTH_GAP = "AUTHORIZATION_GAP"
PROD_ORIGIN_GAP = "ORIGIN_GAP"
PROD_UNKNOWN = "UNKNOWN"
PROD_NONCOMPLIANT = "NONCOMPLIANT"

# Brand / substitution policy
BRAND_ONLY = "BRAND_ONLY"
BRAND_OR_EQUAL = "BRAND_OR_EQUAL"
EQUAL_WITH_DOC = "EQUAL_WITH_DOCUMENTATION"
EQUAL_PREAPPROVAL = "EQUAL_REQUIRES_PREAPPROVAL"
AMBIGUOUS_SUB = "AMBIGUOUS_SUBSTITUTION_POLICY"

# Authorization channel
AUTHZ_NONE = "NO_AUTHORIZATION_REQUIREMENT_FOUND"
AUTHZ_PRODUCT = "AUTHORIZED_CHANNEL_PRODUCT_REQUIRED"
AUTHZ_BIDDER = "BIDDER_AUTHORIZATION_REQUIRED"
AUTHZ_DOC = "DOCUMENTATION_REQUIRED"
AUTHZ_AMBIGUOUS = "AUTHORIZATION_REQUIREMENT_AMBIGUOUS"
AUTHZ_FUTURE = "FUTURE_ACTION_IF_PURSUED"

# Origin
ORIGIN_VERIFIED = "VERIFIED_COMPLIANT"
ORIGIN_LIKELY = "LIKELY_COMPLIANT"
ORIGIN_DOC = "ORIGIN_DOCUMENTATION_REQUIRED"
ORIGIN_UNKNOWN = "UNKNOWN_ORIGIN"
ORIGIN_POTENTIAL_FAIL = "POTENTIALLY_NONCOMPLIANT"

# Package completeness
PKG_UNKNOWN = "PACKAGE_UNKNOWN"
PKG_PARTIAL = "PACKAGE_PARTIAL"
PKG_MATERIAL_MISSING = "PACKAGE_MATERIAL_DOCUMENTS_MISSING"
PKG_REQ_EXTRACTED = "PACKAGE_REQUIREMENTS_EXTRACTED"
PKG_COMPLIANCE = "PACKAGE_COMPLIANCE_ANALYZED"
PKG_OPERATOR_VERIFY = "PACKAGE_READY_FOR_OPERATOR_VERIFICATION"
PKG_BID_ASSEMBLY = "PACKAGE_READY_FOR_BID_ASSEMBLY"
PKG_BLOCKED = "PACKAGE_BLOCKED"

# Bid readiness ladder
READY_DISCOVERED = "DISCOVERED"
READY_PACKAGE_ACQUIRED = "PACKAGE_ACQUIRED"
READY_PACKAGE_MAPPED = "PACKAGE_MAPPED"
READY_REQ_EXTRACTED = "REQUIREMENTS_EXTRACTED"
READY_COMPLIANCE = "COMPLIANCE_ANALYZED"
READY_GAPS = "MATERIAL_GAPS_IDENTIFIED"
READY_AUTO_RESEARCH = "AUTOMATED_RESEARCH_COMPLETE"
READY_COMMERCIAL = "COMMERCIAL_VERIFICATION_REQUIRED"
READY_OPERATOR = "OPERATOR_VERIFICATION_REQUIRED"
READY_BID_ASSEMBLY = "READY_FOR_BID_ASSEMBLY"
READY_BLOCKED = "BLOCKED"
READY_TOO_LATE = "TOO_LATE"

# Material change categories
CHG_QUANTITY = "QUANTITY_CHANGE"
CHG_SPEC = "SPEC_CHANGE"
CHG_PRODUCT = "PRODUCT_CHANGE"
CHG_DEADLINE = "DEADLINE_CHANGE"
CHG_DELIVERY = "DELIVERY_CHANGE"
CHG_ELIGIBILITY = "ELIGIBILITY_CHANGE"
CHG_FORM = "FORM_CHANGE"
CHG_SUBMISSION = "SUBMISSION_CHANGE"
CHG_EVALUATION = "EVALUATION_CHANGE"
CHG_AUTHORIZATION = "AUTHORIZATION_CHANGE"
CHG_DOMESTIC = "DOMESTIC_CONTENT_CHANGE"
CHG_QA = "Q_AND_A_CLARIFICATION"
CHG_CANCEL = "CANCELLATION"
CHG_OTHER = "OTHER_MATERIAL_CHANGE"

FUTURE_ACTION = "FUTURE_ACTION_IF_PURSUED"
TRACKED_CHANGE_ACK_REQUIRED = "ACKNOWLEDGMENT_REQUIRED"

UI_BADGE_READY = "READY"
UI_BADGE_UNRESOLVED = "UNRESOLVED"
UI_BADGE_BLOCKED = "BLOCKED"
UI_BADGE_FUTURE = "FUTURE ACTION"
UI_BADGE_SUPERSEDED = "SUPERSEDED"
UI_BADGE_MATERIAL = "MATERIAL CHANGE"
UI_BADGE_ACK = "ACKNOWLEDGMENT REQUIRED"
