"""Bid assembly + pricing intelligence vocabulary."""

from __future__ import annotations

# Cost confidence
CONF_VERIFIED_BINDING = "VERIFIED_BINDING"
CONF_VERIFIED_PUBLIC = "VERIFIED_PUBLIC"
CONF_RECENT_HISTORICAL = "RECENT_HISTORICAL"
CONF_DEFENSIBLE_ESTIMATE = "DEFENSIBLE_ESTIMATE"
CONF_COMPARABLE_ESTIMATE = "COMPARABLE_ESTIMATE"
CONF_STALE = "STALE"
CONF_UNKNOWN = "UNKNOWN"
CONF_COMMERCIAL_VERIFY = "COMMERCIAL_VERIFICATION_REQUIRED"

# Historical match quality
HIST_EXACT = "EXACT_PRODUCT_HISTORY"
HIST_FAMILY = "SAME_FAMILY_HISTORY"
HIST_COMPARABLE = "COMPARABLE_PRODUCT_HISTORY"
HIST_BASKET = "BASKET_HISTORY"
HIST_WEAK = "WEAK_COMPARABLE"

# Freight / financing states
FREIGHT_VERIFIED = "FREIGHT_VERIFIED"
FREIGHT_ESTIMATED = "FREIGHT_ESTIMATED"
FREIGHT_ALLOWANCE = "FREIGHT_ALLOWANCE"
FREIGHT_VERIFY = "FREIGHT_VERIFICATION_REQUIRED"

FIN_VERIFIED = "FINANCING_VERIFIED"
FIN_ESTIMATED = "FINANCING_ESTIMATED"
FIN_ALLOWANCE = "FINANCING_ALLOWANCE"
FIN_VERIFY = "FINANCING_VERIFICATION_REQUIRED"
FIN_UNRESOLVED = "FUNDING_PATH_UNRESOLVED"

# Price freshness
PRICE_CURRENT = "PRICE_CURRENT"
PRICE_AGING = "PRICE_AGING"
PRICE_STALE = "PRICE_STALE"
PRICE_EXPIRED = "PRICE_EXPIRED"
PRICE_REVERIFY = "PRICE_REVERIFY_IF_PURSUED"

# Profit floor flags
PROFIT_BELOW = "BELOW_PROFIT_FLOOR"
PROFIT_THIN = "MARGIN_TOO_THIN"
PROFIT_MET = "PROFIT_TARGET_MET"
PROFIT_EXCEEDED = "PROFIT_TARGET_EXCEEDED"
PROFIT_UNCERTAIN = "PROFIT_UNCERTAIN"

# Scenarios
SCENARIO_AGGRESSIVE = "AGGRESSIVE_BID"
SCENARIO_BALANCED = "BALANCED_BID"
SCENARIO_MARGIN = "MARGIN_PROTECTIVE_BID"
SCENARIO_BASE = "BASE_CASE"
SCENARIO_DOWNSIDE = "DOWNSIDE_CASE"
SCENARIO_SEVERE = "SEVERE_DOWNSIDE"

# Recommendation
REC_BID = "RECOMMENDED_BID_PRICE"
REC_NEEDS_VERIFY = "BID_PRICE_REQUIRES_COMMERCIAL_VERIFICATION"

# Award modes
AWARD_ALL_OR_NONE = "ALL_OR_NONE"
AWARD_PARTIAL = "PARTIAL_AWARD"
AWARD_LINE_ITEM = "LINE_ITEM_AWARD"

# Form population
FORM_READY = "FORM_READY"
FORM_PARTIAL = "FORM_PARTIALLY_POPULATED"
FORM_OPERATOR = "OPERATOR_INPUT_REQUIRED"
FORM_SIGNATURE = "SIGNATURE_REQUIRED"
FORM_NOTARY = "NOTARY_REQUIRED"
FORM_COMMERCIAL = "COMMERCIAL_VERIFICATION_REQUIRED"
FORM_MISSING = "FORM_MISSING"
FORM_BLOCKED = "BLOCKED"

# Field placeholders
OP_INPUT = "OPERATOR_INPUT_REQUIRED"
SIG_REQUIRED = "SIGNATURE_REQUIRED"
COMM_VERIFY = "COMMERCIAL_VERIFICATION_REQUIRED"
DOC_REQUIRED = "DOCUMENT_REQUIRED"
REG_REQUIRED = "REGISTRATION_REQUIRED"
FIELD_UNKNOWN = "UNKNOWN"

# Finalization / pricing states (no SUBMITTED)
PRICING_NOT_STARTED = "PRICING_NOT_STARTED"
PRICING_IN_PROGRESS = "PRICING_IN_PROGRESS"
PRICING_RESEARCH = "PRICING_RESEARCH_REQUIRED"
PRICING_COMMERCIAL = "PRICING_COMMERCIAL_VERIFICATION_REQUIRED"
PRICING_READY = "PRICING_READY"
DRAFT_INCOMPLETE = "DRAFT_BID_INCOMPLETE"
DRAFT_READY = "DRAFT_BID_READY"
OPERATOR_FINAL = "OPERATOR_FINALIZATION_REQUIRED"
READY_AUTH_COMMERCIAL = "READY_FOR_AUTHORIZED_COMMERCIAL_VERIFICATION"
READY_OPERATOR_REVIEW = "READY_FOR_OPERATOR_REVIEW"
SUBMISSION_BLOCKED = "SUBMISSION_BLOCKED"

FUTURE_ACTION = "FUTURE_ACTION_IF_PURSUED"

CALC_VERSION = "bid-pricing-v1"
