"""Commercial verification + execution control vocabulary."""

from __future__ import annotations

# Verification categories
CAT_SUPPLIER_PRICE = "SUPPLIER_PRICE"
CAT_PRODUCT_AVAILABILITY = "PRODUCT_AVAILABILITY"
CAT_LEAD_TIME = "LEAD_TIME"
CAT_FREIGHT = "FREIGHT"
CAT_PRICE_VALIDITY = "PRICE_VALIDITY"
CAT_AUTHORIZED_RESELLER = "AUTHORIZED_RESELLER_STATUS"
CAT_OEM_AUTHORIZATION = "OEM_AUTHORIZATION"
CAT_PRODUCT_COMPLIANCE_DOC = "PRODUCT_COMPLIANCE_DOCUMENT"
CAT_COUNTRY_OF_ORIGIN = "COUNTRY_OF_ORIGIN"
CAT_FINANCING_ELIGIBILITY = "FINANCING_ELIGIBILITY"
CAT_FINANCING_COST = "FINANCING_COST"
CAT_ADVANCE_PCT = "ADVANCE_PERCENTAGE"
CAT_PERSONAL_GUARANTEE = "PERSONAL_GUARANTEE"
CAT_PERSONAL_CREDIT = "PERSONAL_CREDIT_REQUIREMENT"
CAT_MINIMUM_FICO = "MINIMUM_FICO"
CAT_CASH_CONTRIBUTION = "CASH_CONTRIBUTION"
CAT_REPAYMENT = "REPAYMENT_STRUCTURE"
CAT_ASSIGNMENT = "ASSIGNMENT_REQUIREMENT"
CAT_DELIVERY = "DELIVERY_COMMITMENT"

# Priority
PRI_DEAL_KILLER = "DEAL_KILLER"
PRI_HIGH = "HIGH_VALUE"
PRI_MATERIAL = "MATERIAL"
PRI_LOW = "LOW_VALUE"
PRI_OPTIONAL = "OPTIONAL"

# Verification item status
V_PENDING = "PENDING"
V_PROPOSED = "PROPOSED"
V_AUTHORIZED = "AUTHORIZED"
V_IN_PROGRESS = "IN_PROGRESS"
V_VERIFIED = "VERIFIED"
V_FAILED = "FAILED"
V_EXPIRED = "EXPIRED"
V_NOT_NEEDED = "NOT_NEEDED"

# Evidence authority
AUTH_BINDING_QUOTE = "BINDING_QUOTE"
AUTH_WRITTEN = "WRITTEN_COMMERCIAL_CONFIRMATION"
AUTH_COND_FIN = "CONDITIONAL_FINANCING_INDICATION"
AUTH_TERM_SHEET = "TERM_SHEET"
AUTH_OEM_LETTER = "AUTHORIZATION_LETTER"
AUTH_OFFICIAL = "OFFICIAL_DOCUMENT"
AUTH_VERBAL = "VERBAL_CONFIRMATION"
AUTH_MARKETING = "PUBLIC_MARKETING"
AUTH_INFERRED = "INFERRED"
AUTH_UNKNOWN = "UNKNOWN"

# Financing compatibility
FIN_COMPATIBLE = "COMPATIBLE"
FIN_POTENTIAL = "POTENTIALLY_COMPATIBLE"
FIN_UNCERTAINTY = "MATERIAL_UNCERTAINTY"
FIN_LIKELY_INCOMPAT = "LIKELY_INCOMPATIBLE"
FIN_INCOMPATIBLE = "INCOMPATIBLE"  # financier-level only when affirmative evidence
FIN_UNKNOWN = "UNKNOWN"
FINANCIER_INCOMPATIBLE = "FINANCIER_INCOMPATIBLE"  # explicit financier-level failure

# Funding path lifecycle (not negative when UNTESTED)
PATH_UNTESTED = "UNTESTED"
PATH_PUBLIC_POSSIBLE = "PUBLIC_EVIDENCE_SUPPORTS_POSSIBILITY"
PATH_VERIFY_REQ = "VERIFICATION_REQUIRED"
PATH_INQUIRY_PREP = "TRANSACTION_INQUIRY_PREPARED"
PATH_CONDITIONAL = "CONDITIONAL_INDICATION"
PATH_VERIFIED_OK = "VERIFIED_COMPATIBLE"
PATH_VERIFIED_BAD = "VERIFIED_INCOMPATIBLE"
PATH_DECLINED = "DECLINED_FOR_TRANSACTION"
PATH_EXPIRED = "EXPIRED"

# Funding gate
FUND_NOT_REQUIRED = "FUNDING_NOT_REQUIRED"
FUND_REQ_UNKNOWN = "FUNDING_REQUIREMENT_UNKNOWN"
FUND_RESEARCH_ONLY = "FUNDING_RESEARCH_ONLY"
FUND_PATH_ID = "FUNDING_PATH_IDENTIFIED"
FUND_VERIFY_REQ = "FUNDING_VERIFICATION_REQUIRED"
FUND_INDICATION = "FUNDING_INDICATION_RECEIVED"
FUND_COND_FEASIBLE = "FUNDING_CONDITIONALLY_FEASIBLE"
FUND_VERIFIED = "FUNDING_VERIFIED_FOR_TRANSACTION"
FUND_INCOMPATIBLE = "FUNDING_INCOMPATIBLE"  # legacy; prefer TRANSACTION_FUNDING_EXHAUSTED
FUND_EXHAUSTED = "TRANSACTION_FUNDING_EXHAUSTED"
FUND_BLOCKED = "FUNDING_BLOCKED"

ECON_ATTRACTIVE_FUNDING_UNVERIFIED = "ECONOMICALLY_ATTRACTIVE_BUT_FUNDING_UNVERIFIED"
ECON_ATTRACTIVE_FUNDING_VERIFY_REQ = "ECONOMICALLY_ATTRACTIVE_FUNDING_VERIFICATION_REQUIRED"

# PG / credit / FICO independent vocabulary
PG_REQUIRED = "PG_REQUIRED"
PG_NOT_REQUIRED = "PG_NOT_REQUIRED"
PG_UNKNOWN = "PG_UNKNOWN"
PULL_REQUIRED = "PERSONAL_CREDIT_PULL_REQUIRED"
PULL_NOT_REQUIRED = "PERSONAL_CREDIT_PULL_NOT_REQUIRED"
PULL_UNKNOWN = "PERSONAL_CREDIT_PULL_UNKNOWN"
CREDIT_DEP = "PERSONAL_CREDIT_DEPENDENT"
CREDIT_NOT_MATERIAL = "PERSONAL_CREDIT_NOT_MATERIAL"
CREDIT_DEP_UNKNOWN = "PERSONAL_CREDIT_DEPENDENCY_UNKNOWN"
FICO_KNOWN = "MINIMUM_FICO_KNOWN"
FICO_NOT_STATED = "MINIMUM_FICO_NOT_STATED"
FICO_UNKNOWN = "MINIMUM_FICO_UNKNOWN"

# Alternative structure labels (recognition only — do not fabricate availability)
STRUCT_PO = "PO_FINANCING"
STRUCT_PO_AR = "PO_PLUS_AR"
STRUCT_FACTORING = "FACTORING_AFTER_INVOICE"
STRUCT_SUPPLIER_TERMS = "SUPPLIER_TERMS"
STRUCT_DEPOSIT_PO = "SUPPLIER_DEPOSIT_PLUS_PO"
STRUCT_DISTRIBUTOR = "DISTRIBUTOR_TERMS"
STRUCT_GOV_CONTRACT = "GOVERNMENT_CONTRACT_FINANCING"
STRUCT_WC = "TRANSACTION_WORKING_CAPITAL"
STRUCT_COMBO = "COMBINATION_STRUCTURE"

# Commercial verification outcome
CV_PENDING = "COMMERCIAL_VERIFICATION_PENDING"
CV_PARTIAL = "COMMERCIAL_VERIFICATION_PARTIAL"
CV_PASSED = "COMMERCIAL_VERIFICATION_PASSED"
CV_FAILED = "COMMERCIAL_VERIFICATION_FAILED"
CV_EXPIRED = "COMMERCIAL_VERIFICATION_EXPIRED"
CV_FINANCIER_PATH_FAILED = "FINANCIER_PATH_FAILED"

# Pursuit vs execution (commercial layer)
PURSUIT_KEEP = "KEEP_PURSUING"
PURSUIT_KEEP_UNCERTAIN = "PURSUIT_WORTHY_WITH_MATERIAL_UNCERTAINTY"
PURSUIT_STOP_FUNDING = "PURSUIT_STOPPED_FUNDING_EXHAUSTED"

# Underwriting model
UW_INTERNAL = "UNDERWRITING_INTERNAL"
UW_EXTERNAL = "UNDERWRITING_EXTERNAL"
UW_BROKERED = "BROKERED"
UW_HYBRID = "HYBRID"
UW_UNKNOWN = "UNKNOWN"

# External action types
ACT_SUPPLIER_QUOTE = "REQUEST_SUPPLIER_QUOTE"
ACT_VERIFY_STOCK = "VERIFY_SUPPLIER_STOCK"
ACT_VERIFY_AUTH = "VERIFY_AUTHORIZATION"
ACT_FINANCING_IND = "REQUEST_FINANCING_INDICATION"
ACT_AGENCY_Q = "ASK_AGENCY_QUESTION"
ACT_REGISTER = "REGISTER_PORTAL"
ACT_SIGN = "SIGN_DOCUMENT"
ACT_SUBMIT_BID = "SUBMIT_BID"

# Authorization states
AUTHZ_NOT = "NOT_AUTHORIZED"
AUTHZ_REVIEW = "OPERATOR_REVIEW_REQUIRED"
AUTHZ_AUTHORIZED = "AUTHORIZED"
AUTHZ_REJECTED = "REJECTED"
AUTHZ_EXPIRED = "EXPIRED"
AUTHZ_REVOKED = "REVOKED"

# Execution
EXEC_NOT_STARTED = "NOT_STARTED"
EXEC_DRY_RUN = "DRY_RUN_ONLY"
EXEC_BLOCKED_MODE = "EXECUTION_BLOCKED_BY_OPERATING_MODE"
EXEC_BLOCKED_AUTH = "EXECUTION_BLOCKED_NOT_AUTHORIZED"
EXEC_BLOCKED_GOV = "EXECUTION_BLOCKED_BY_COST_GOVERNOR"
EXEC_BLOCKED_FORBIDDEN = "EXECUTION_BLOCKED_FORBIDDEN_IN_CONTROLLED_MODE"
EXEC_CONTROLLED_AUTHORIZED = "CONTROLLED_OPERATOR_AUTHORIZED_NO_NETWORK"
EXEC_DONE = "EXECUTED"  # only for dry-run in this build

# Audit events
AUD_PROPOSED = "PROPOSED"
AUD_REVIEWED = "REVIEWED"
AUD_AUTHORIZED = "AUTHORIZED"
AUD_REJECTED = "REJECTED"
AUD_BLOCKED = "BLOCKED"
AUD_EXECUTED = "EXECUTED"
AUD_RESULT = "RESULT_RECEIVED"
AUD_EXPIRED = "EXPIRED"
AUD_REVOKED = "REVOKED"

# Negotiation bands
NEG_TARGET = "TARGET"
NEG_ACCEPTABLE = "ACCEPTABLE"
NEG_HARD_CEILING = "HARD_CEILING"
NEG_WALK_AWAY = "WALK_AWAY"

# Commercial freshness
CF_CURRENT = "CURRENT"
CF_AGING = "AGING"
CF_REVERIFY = "REVERIFY_IF_PURSUED"
CF_EXPIRED = "EXPIRED"

# Commercial readiness ladder
CR_PUBLIC = "PUBLIC_RESEARCH_ONLY"
CR_PLAN_READY = "COMMERCIAL_VERIFICATION_PLAN_READY"
CR_AUTH_REQ = "OPERATOR_AUTHORIZATION_REQUIRED"
CR_IN_PROGRESS = "VERIFICATION_IN_PROGRESS"
CR_PARTIAL = "COMMERCIAL_INPUTS_PARTIAL"
CR_VERIFIED = "COMMERCIAL_INPUTS_VERIFIED"
CR_FUNDING_UNVER = "FUNDING_UNVERIFIED"
CR_FUNDING_COND = "FUNDING_CONDITIONALLY_FEASIBLE"
CR_EXEC_CONFIRMED = "COMMERCIAL_EXECUTABILITY_CONFIRMED"
CR_FINAL_REVIEW = "READY_FOR_FINAL_BID_REVIEW"

# Execution gate
EG_NOT_READY = "EXECUTION_NOT_READY"
EG_CONDITIONAL = "EXECUTION_CONDITIONALLY_READY"
EG_READY_FINAL = "EXECUTION_READY_FOR_OPERATOR_FINALIZATION"

FUTURE_ACTION = "FUTURE_ACTION_IF_PURSUED"
