"""Cost Governor constants — paid research capital allocation."""

from __future__ import annotations

# Cost states
COST_FREE = "FREE"
COST_AUTHORIZED = "AUTHORIZED"
COST_EXECUTED = "EXECUTED"
COST_RECONCILED = "RECONCILED"
COST_DEFERRED_BUDGET = "DEFERRED_BUDGET"
COST_DEFERRED_PRIORITY = "DEFERRED_PRIORITY"
COST_DEFERRED_VALUE = "DEFERRED_VALUE"
COST_BLOCKED_HARD_CAP = "BLOCKED_HARD_CAP"
COST_BLOCKED_PER_OPP = "BLOCKED_PER_OPPORTUNITY_CAP"
COST_BLOCKED_DAILY = "BLOCKED_DAILY_CAP"
COST_BLOCKED_MONTHLY = "BLOCKED_MONTHLY_CAP"
COST_BLOCKED_RUN = "BLOCKED_PER_RUN_CAP"
COST_UNKNOWN = "UNKNOWN_COST"
COST_FAILED_NO_CHARGE = "FAILED_NO_CHARGE"
COST_FAILED_CHARGE_POSSIBLE = "FAILED_CHARGE_POSSIBLE"
COST_REUSED_EVIDENCE = "REUSED_EXISTING_EVIDENCE"
COST_CATCHUP_REJECT = "CATCHUP_REJECT_TOO_LATE"

# Priority tiers
TIER_1_ACTIVE = "TIER_1_PROTECT_ACTIVE_PURSUITS"
TIER_2_QUALIFIED = "TIER_2_ADVANCE_QUALIFIED"
TIER_3_BACKLOG = "TIER_3_EXISTING_BACKLOG"
TIER_4_NEW_DISCOVERY = "TIER_4_NEW_PAID_DISCOVERY"

TIER_ORDER = (TIER_1_ACTIVE, TIER_2_QUALIFIED, TIER_3_BACKLOG, TIER_4_NEW_DISCOVERY)

# Budget operating states
BUDGET_NORMAL = "BUDGET_NORMAL"
BUDGET_CONSTRAINED = "BUDGET_CONSTRAINED"
DISCOVERY_THROTTLED = "DISCOVERY_THROTTLED"
PAID_DISCOVERY_PAUSED = "PAID_DISCOVERY_PAUSED"
HARD_CAP_EXHAUSTED = "HARD_CAP_EXHAUSTED"
CATCH_UP = "CATCH_UP"
BACKLOG_RECOVERY = "BACKLOG_RECOVERY"

# Market coverage
MARKET_CURRENT = "MARKET_COVERAGE_CURRENT"
MARKET_BEHIND = "MARKET_COVERAGE_BEHIND"
MARKET_CATCHING_UP = "MARKET_COVERAGE_CATCHING_UP"
MARKET_UNKNOWN = "MARKET_COVERAGE_UNKNOWN"

# Source pause reasons
SOURCE_PAUSED_BUDGET = "SOURCE_PAUSED_BUDGET"
SOURCE_FAILED = "SOURCE_FAILED"

# Inventory
DISCOVERED_PENDING_RESEARCH = "DISCOVERED_PENDING_RESEARCH"
TRACKED_CHANGE_ANALYSIS_BLOCKED_BY_BUDGET = "TRACKED_CHANGE_ANALYSIS_BLOCKED_BY_BUDGET"

# Catch-up reject reasons
CATCHUP_REJECT_TOO_LATE = "CATCHUP_REJECT_TOO_LATE"
CATCHUP_REJECT_EXPIRED = "CATCHUP_REJECT_EXPIRED"
CATCHUP_REJECT_CANCELLED = "CATCHUP_REJECT_CANCELLED"
CATCHUP_REJECT_CLOSED = "CATCHUP_REJECT_CLOSED"
CATCHUP_REJECT_NON_FIT = "CATCHUP_REJECT_NON_FIT"
CATCHUP_PRESERVE_ACTIONABLE = "CATCHUP_PRESERVE_ACTIONABLE"

# Defaults (development/testing — operator config authoritative)
DEFAULT_ABSOLUTE_CAP = 25.0
DEFAULT_MONTHLY_CAP = 40.0
DEFAULT_DAILY_CAP = 5.0
DEFAULT_PER_RUN_CAP = 10.0
DEFAULT_PER_OPPORTUNITY_CAP = 8.0
DEFAULT_SAFETY_BUFFER = 0.05

# Action types
ACTION_AI_COMPLETION = "AI_COMPLETION"
ACTION_PAID_SEARCH = "PAID_SEARCH"
ACTION_DOCUMENT_PROCESSING = "DOCUMENT_PROCESSING"
ACTION_DATA_PROVIDER = "DATA_PROVIDER"
ACTION_COMMERCIAL_ENRICHMENT = "COMMERCIAL_ENRICHMENT"
ACTION_PAID_SOURCE_FETCH = "PAID_SOURCE_FETCH"
ACTION_OTHER_METERED = "OTHER_METERED"
