"""Deep Deal Research + Bid Qualification — constants and states."""

from __future__ import annotations

# --- Deal types ---
DEAL_ONE_TIME_PRODUCT = "ONE_TIME_PRODUCT_PURCHASE"
DEAL_IDIQ = "IDIQ_PRODUCT_CONTRACT"
DEAL_COOP_MASTER = "COOPERATIVE_MASTER_CONTRACT"
DEAL_BPA = "BPA_OR_BLANKET_VEHICLE"
DEAL_CATALOG = "CATALOG_DISCOUNT_CONTRACT"
DEAL_REQUIREMENTS = "REQUIREMENTS_CONTRACT"
DEAL_PRODUCT_PLUS_INSTALL = "PRODUCT_PLUS_INSTALLATION"
DEAL_CONSTRUCTION = "CONSTRUCTION_OR_UPGRADE"
DEAL_SERVICE = "SERVICE_CONTRACT"
DEAL_LEASE = "LEASE_OR_RENTAL"
DEAL_UNKNOWN = "UNKNOWN_DEAL_TYPE"

# --- Pre-deep launch fit ---
FIT_CORE_TRANSACTIONAL = "CORE_TRANSACTIONAL_RESALE"
FIT_POTENTIAL_VEHICLE = "POTENTIAL_RESALE_VEHICLE"
FIT_PRODUCT_PLUS_SUB = "PRODUCT_PLUS_SUBCONTRACTABLE_WORK"
FIT_LONG_TERM_CHANNEL = "LONG_TERM_CHANNEL_OPPORTUNITY"
FIT_POOR_LAUNCH = "POOR_LAUNCH_FIT"
FIT_NOT_OUR_MODEL = "NOT_OUR_MODEL"
FIT_NEEDS_DOC_REVIEW = "NEEDS_DOCUMENT_REVIEW"

# --- Revenue certainty ---
REV_GUARANTEED = "GUARANTEED"
REV_ESTIMATED = "ESTIMATED"
REV_POTENTIAL = "POTENTIAL_FUTURE"
REV_NONE = "NO_COMMITTED_PURCHASE"
REV_UNKNOWN = "UNKNOWN"

# --- Bid qualification states ---
STATE_DISCOVERED = "DISCOVERED"
STATE_NEEDS_DOC_REVIEW = "NEEDS_DOCUMENT_REVIEW"
STATE_DOC_REVIEWED = "DOCUMENT_REVIEWED"
STATE_NEEDS_PRODUCT_ID = "NEEDS_PRODUCT_IDENTIFICATION"
STATE_NEEDS_SUPPLIER_QUOTE = "NEEDS_SUPPLIER_QUOTE"
STATE_NEEDS_SUPPLIER_TERMS = "NEEDS_SUPPLIER_TERMS"
STATE_NEEDS_COMPLIANCE = "NEEDS_COMPLIANCE_VERIFICATION"
STATE_NEEDS_PRICING_HISTORY = "NEEDS_PRICING_HISTORY"
STATE_NEEDS_FUNDING = "NEEDS_FUNDING_VERIFICATION"
STATE_ECONOMICS_PENDING = "ECONOMICS_PENDING"
STATE_QUALIFIED_REVIEW = "QUALIFIED_FOR_OPERATOR_REVIEW"
STATE_BID_READY = "BID_READY"
STATE_WAITING_EXTERNAL = "WAITING_EXTERNAL_INFORMATION"
STATE_REJECTED = "REJECTED"
STATE_STRATEGIC = "STRATEGIC_LONG_TERM"

# --- Operator queue buckets ---
QUEUE_IMMEDIATE = "IMMEDIATE_RESALE_CANDIDATES"
QUEUE_CHEAP_CLASS = "NEEDS_CHEAP_CLASSIFICATION"
QUEUE_DEEP = "DEEP_RESEARCH"
QUEUE_WAITING = "WAITING_EXTERNAL"
QUEUE_BID_PREP = "BID_PREPARATION"
QUEUE_STRATEGIC = "STRATEGIC_CONTRACT_VEHICLES"
QUEUE_REJECTED = "REJECTED"

# --- Compliance statuses ---
COMP_PASS = "PASS"
COMP_LIKELY = "LIKELY_PASS"
COMP_NEEDS = "NEEDS_VERIFICATION"
COMP_FAIL = "FAIL"
COMP_NA = "NOT_APPLICABLE"
COMP_UNKNOWN = "UNKNOWN"

# --- NMR / set-aside ---
NMR_PASS = "PASS"
NMR_NEEDS = "NEEDS_VERIFICATION"
NMR_POTENTIAL = "POTENTIAL_BLOCKER"
NMR_HARD = "HARD_BLOCKER"

# --- Product ID certainty ---
PROD_EXACT = "EXACT_PRODUCT_IDENTIFIED"
PROD_SPEC = "SPEC_BASED_PRODUCT"
PROD_BRAND_EQUAL = "BRAND_OR_EQUAL"
PROD_CUSTOM = "CUSTOM_CONFIGURED_PRODUCT"
PROD_UNKNOWN = "PRODUCT_UNKNOWN"

# --- Profit confidence (deep) ---
PROFIT_VERIFIED = "PROFIT_VERIFIED"
PROFIT_HIGH = "PROFIT_HIGH_CONFIDENCE"
PROFIT_ESTIMATED = "PROFIT_ESTIMATED"
PROFIT_POTENTIAL = "PROFIT_POTENTIAL"
PROFIT_UNKNOWN = "PROFIT_UNKNOWN"
PROFIT_BELOW = "PROFIT_BELOW_TARGET"

# --- Operator decisions ---
DEC_CONTINUE = "CONTINUE_DEEP_RESEARCH"
DEC_WAIT_QUOTE = "WAIT_FOR_QUOTE"
DEC_WAIT_FUNDING = "WAIT_FOR_FUNDING_VERIFICATION"
DEC_QUALIFIED = "QUALIFIED_FOR_OPERATOR_REVIEW"
DEC_STRATEGIC = "STRATEGIC_LONG_TERM"
DEC_REJECT = "REJECT"
DEC_BID_READY = "BID_READY"

# --- Evidence / AI fact states ---
EV_VERIFIED_DOCUMENT = "VERIFIED_DOCUMENT"
EV_VERIFIED_PUBLIC = "VERIFIED_PUBLIC"
EV_VERIFIED_QUOTE = "VERIFIED_QUOTE"
EV_ASSESSMENT = "ASSESSMENT"
EV_UNKNOWN = "UNKNOWN"
EV_PROPOSED_AI = "PROPOSED_AI_UNCONFIRMED"

# --- Cheap second-stage classification ---
CHEAP_LIKELY_PRODUCT = "LIKELY_PRODUCT"
CHEAP_LIKELY_PRODUCT_PLUS = "LIKELY_PRODUCT_PLUS_SERVICE"
CHEAP_LIKELY_SERVICE = "LIKELY_SERVICE"
CHEAP_INSUFFICIENT = "INSUFFICIENT_INFORMATION"

# --- Launch priority tiers (discovery ranking) ---
TIER_A_IMMEDIATE = "TIER_A_IMMEDIATE_TRANSACTIONAL_RESALE"
TIER_B_LIKELY = "TIER_B_LIKELY_TRANSACTIONAL_RESALE"
TIER_C_VEHICLE = "TIER_C_PRODUCT_VEHICLE_RECURRING"
TIER_D_STRATEGIC = "TIER_D_STRATEGIC_LONG_TERM"
TIER_E_PLUS_PERF = "TIER_E_PRODUCT_PLUS_PERFORMANCE"
TIER_F_LOW_FIT = "TIER_F_LOW_FIT_REJECT"
TIER_G_UNKNOWN = "TIER_G_UNKNOWN"

# --- Value potential ---
VALUE_HIGH = "HIGH_VALUE_POTENTIAL"
VALUE_ADEQUATE = "ADEQUATE_VALUE_POTENTIAL"
VALUE_UNCERTAIN = "UNCERTAIN_VALUE"
VALUE_LOW = "LOW_VALUE_LIKELY"
VALUE_BELOW = "BELOW_TARGET"

# --- Expansion ---
MIN_TIER_AB_BEFORE_EXPANSION = 3
TOP_DEEP_RESEARCH_SLOTS = 3
EXPANSION_TARGET_HTTP = 50
EXPANSION_HARD_MAX_HTTP = 70


# --- Request budgets for this validation pass ---
TARGET_OPENAI = 10
HARD_MAX_OPENAI = 15
TARGET_PUBLIC_HTTP = 60
HARD_MAX_PUBLIC_HTTP = 80
TARGET_USASPENDING = 5
HARD_MAX_USASPENDING = 10

# --- Research stop reasons ---
STOP_DEADLINE = "deadline_too_late"
STOP_NOT_RESALE = "not_resale_opportunity"
STOP_INELIGIBLE = "ineligible_compliance"
STOP_PROFIT_BELOW = "profit_clearly_below_target"
STOP_FUNDING_ONLY_PG = "funding_requires_pg_or_cash_only"
STOP_OEM_REQUIRED = "manufacturer_authorization_unavailable"
STOP_SELF_PERFORM = "mandatory_self_performance"
STOP_STRATEGIC_ONLY = "master_contract_no_near_term_transaction"
STOP_BUDGET = "research_budget_exhausted"
