"""Authorized document ingestion — constants (no auth bypass)."""

from __future__ import annotations

# Acquisition methods (operator-authorized paths)
ACQ_PUBLIC_FETCH = "PUBLIC_FETCH"
ACQ_AUTHORIZED_OPERATOR_DOWNLOAD = "AUTHORIZED_OPERATOR_DOWNLOAD"
ACQ_MANUAL_UPLOAD = "MANUAL_UPLOAD"
ACQ_AUTHORIZED_PORTAL_EXPORT = "AUTHORIZED_PORTAL_EXPORT"
ACQ_UNKNOWN = "UNKNOWN"

ACQUISITION_METHODS = frozenset(
    {
        ACQ_PUBLIC_FETCH,
        ACQ_AUTHORIZED_OPERATOR_DOWNLOAD,
        ACQ_MANUAL_UPLOAD,
        ACQ_AUTHORIZED_PORTAL_EXPORT,
        ACQ_UNKNOWN,
    }
)

# Explicit blockers (mutually prioritized in classify_blockers)
BLOCKER_AUTH = "AUTHENTICATION_BLOCKED_DOCUMENT"
BLOCKER_OPERATOR_DOC = "OPERATOR_DOCUMENT_REQUIRED"
BLOCKER_SUPPLIER_QUOTE = "SUPPLIER_QUOTE_REQUIRED"
BLOCKER_FREIGHT = "FREIGHT_REQUIRED"
BLOCKER_GOV_REVENUE = "GOVERNMENT_REVENUE_EVIDENCE_REQUIRED"
BLOCKER_COMPLIANCE = "COMPLIANCE_REVIEW_REQUIRED"
BLOCKER_FUNDING = "FUNDING_VERIFICATION_REQUIRED"
BLOCKER_OTHER = "OTHER"

# Supplier fit after spec ingestion
FIT_EXACT = "EXACT_MATCH"
FIT_LIKELY = "LIKELY_MATCH"
FIT_POSSIBLE = "POSSIBLE_MATCH"
FIT_NOT = "NOT_MATCH"
FIT_QUOTE = "QUOTE_REQUIRED"
FIT_INSUFFICIENT = "INSUFFICIENT_EVIDENCE"

# Bid-price threshold kinds (not winning prices)
BID_BREAK_EVEN = "BREAK_EVEN_BID"
BID_MIN_10K = "MINIMUM_BID_FOR_10K_PROFIT"
BID_MIN_MARGIN = "MINIMUM_BID_FOR_TARGET_MARGIN"
BID_MARKET_REF = "OPTIONAL_MARKET_REFERENCE_PRICE"
BID_HISTORICAL = "HISTORICAL_AWARD_REFERENCE"
BID_USER_SELECTED = "USER_SELECTED_BID_PRICE"

THRESHOLD_CALCULATED = "calculated_threshold"
THRESHOLD_HISTORICAL = "historical_evidence"
THRESHOLD_MARKET = "market_evidence"
THRESHOLD_SUBMITTED = "actual_submitted_bid"

SUPPORTED_INGEST_EXTENSIONS = {
    ".pdf",
    ".doc",
    ".docx",
    ".xls",
    ".xlsx",
    ".csv",
    ".txt",
    ".zip",
}
