"""Executable deal pipeline — stages, readiness, evidence maturity, actions."""

from __future__ import annotations

# Pipeline stages
STAGE_OPPORTUNITY_DISCOVERED = "OPPORTUNITY_DISCOVERED"
STAGE_TRANSACTIONAL_QUALIFICATION = "TRANSACTIONAL_QUALIFICATION"
STAGE_DEADLINE_VALIDATION = "DEADLINE_VALIDATION"
STAGE_REQUIREMENT_ACQUISITION = "REQUIREMENT_ACQUISITION"
STAGE_REQUIREMENT_EXTRACTION = "REQUIREMENT_EXTRACTION"
STAGE_BOM_DEFINITION = "BOM_DEFINITION"
STAGE_SUPPLIER_IDENTIFICATION = "SUPPLIER_IDENTIFICATION"
STAGE_SUPPLIER_COSTING = "SUPPLIER_COSTING"
STAGE_FREIGHT_AND_TRANSACTION_COSTING = "FREIGHT_AND_TRANSACTION_COSTING"
STAGE_ECONOMIC_QUALIFICATION = "ECONOMIC_QUALIFICATION"
STAGE_WORKING_CAPITAL_DEFINITION = "WORKING_CAPITAL_DEFINITION"
STAGE_FUNDING_COMPATIBILITY = "FUNDING_COMPATIBILITY"
STAGE_COMPLIANCE_REVIEW = "COMPLIANCE_REVIEW"
STAGE_OPERATOR_ACTION = "OPERATOR_ACTION"
STAGE_DEAL_READY_FOR_BID_PREPARATION = "DEAL_READY_FOR_BID_PREPARATION"
STAGE_DEAL_REJECTED = "DEAL_REJECTED"

# Operator-facing readiness (single surface)
READY_RESEARCHING = "RESEARCHING"
READY_OPERATOR_ACTION = "OPERATOR_ACTION_REQUIRED"
READY_QUOTE_REQUIRED = "QUOTE_REQUIRED"
READY_ECONOMICS_REVIEW = "ECONOMICS_REVIEW"
READY_FUNDING_CALL = "FUNDING_CALL_READY"
READY_FUNDING_VERIFY = "FUNDING_VERIFICATION_REQUIRED"
READY_COMPLIANCE = "COMPLIANCE_REVIEW_REQUIRED"
READY_BID_PREP = "READY_FOR_BID_PREPARATION"
READY_REJECTED = "REJECTED"

# Evidence maturity
EV_VERIFIED_SOLICITATION = "VERIFIED_SOLICITATION"
EV_PUBLIC_CURRENT = "PUBLIC_CURRENT"
EV_HISTORICAL_REFERENCE = "HISTORICAL_REFERENCE"
EV_ESTIMATE = "ESTIMATE"
EV_QUOTE_REQUIRED = "QUOTE_REQUIRED"
EV_OPERATOR_CONFIRMED = "OPERATOR_CONFIRMED"
EV_INFERRED = "INFERRED"
EV_UNKNOWN = "UNKNOWN"
EV_VERIFIED_PROVIDER = "VERIFIED_PROVIDER"
EV_DEAL_SPECIFIC_CONFIRMATION_REQUIRED = "DEAL_SPECIFIC_CONFIRMATION_REQUIRED"
EV_VERIFIED_QUOTE = "VERIFIED_QUOTE"

# Cost/quote distinctions
PUBLIC_PRICE_PRELIMINARY = "PUBLIC_PRICE_SUFFICIENT_FOR_PRELIMINARY_ECONOMICS"
FORMAL_QUOTE_REQUIRED = "FORMAL_QUOTE_REQUIRED_BEFORE_BID"
SUPPLIER_CONFIRMATION_REQUIRED = "SUPPLIER_CONFIRMATION_REQUIRED"
AUTHORIZATION_CONFIRMATION_REQUIRED = "AUTHORIZATION_CONFIRMATION_REQUIRED"
LEAD_TIME_CONFIRMATION_REQUIRED = "LEAD_TIME_CONFIRMATION_REQUIRED"

# Actions
ACTION_CALL_SUPPLIER = "CALL_SUPPLIER"
ACTION_EMAIL_SUPPLIER = "EMAIL_SUPPLIER"
ACTION_CALL_FINANCIER = "CALL_FINANCIER"
ACTION_DOWNLOAD_AUTH = "DOWNLOAD_AUTH_DOCUMENT"
ACTION_REGISTER_PORTAL = "REGISTER_PORTAL"
ACTION_ASK_AGENCY = "ASK_AGENCY_CLARIFICATION"
ACTION_REVIEW_PG = "REVIEW_PG"
ACTION_CONFIRM_COMPLIANCE = "CONFIRM_COMPLIANCE"
ACTION_OBTAIN_FREIGHT = "OBTAIN_FREIGHT_QUOTE"
ACTION_REVIEW_BID = "REVIEW_BID_DECISION"

# Funding compatibility labels
FUND_LIKELY = "LIKELY_COMPATIBLE"
FUND_POSSIBLE = "POSSIBLE_WITH_VERIFICATION"
FUND_INCOMPATIBLE = "INCOMPATIBLE"
FUND_STALE = "STALE_REVERIFY"
FUND_UNKNOWN = "UNKNOWN"

# Knowledge promotion
PROMOTE_DEAL_SPECIFIC = "DEAL_SPECIFIC_ONLY"
PROMOTE_REUSABLE = "REUSABLE_KNOWLEDGE"

PROFIT_FLOOR_USD = 10_000.0
OPERATOR_FICO = 480
MAX_SUPPLIER_SHORTLIST = 5

LIVE_IOWA = "645-DOTRFB-2975-2027"
