"""Federal/DLA product-intelligence constants (description, tech-data, readiness, signals)."""

from __future__ import annotations

# Description recovery states
DESCRIPTION_INLINE = "DESCRIPTION_INLINE"
DESCRIPTION_PUBLIC_RECOVERED = "DESCRIPTION_PUBLIC_RECOVERED"
DESCRIPTION_EXTERNAL_POINTER = "DESCRIPTION_EXTERNAL_POINTER"
DESCRIPTION_AUTH_REQUIRED = "DESCRIPTION_AUTH_REQUIRED"
DESCRIPTION_BOT_BLOCKED = "DESCRIPTION_BOT_BLOCKED"
DESCRIPTION_NOT_FOUND = "DESCRIPTION_NOT_FOUND"
DESCRIPTION_FETCH_FAILED = "DESCRIPTION_FETCH_FAILED"
DESCRIPTION_UNSUPPORTED = "DESCRIPTION_UNSUPPORTED"
DESCRIPTION_EMPTY = "DESCRIPTION_EMPTY"

# Document / package reference classes
REF_SOLICITATION_DOCUMENT = "SOLICITATION_DOCUMENT"
REF_AMENDMENT = "AMENDMENT"
REF_ATTACHMENT = "ATTACHMENT"
REF_TECHNICAL_DATA = "TECHNICAL_DATA"
REF_DRAWING_REFERENCE = "DRAWING_REFERENCE"
REF_SPECIFICATION_REFERENCE = "SPECIFICATION_REFERENCE"
REF_PACKAGING_REFERENCE = "PACKAGING_REFERENCE"
REF_CLAUSE_DOCUMENT = "CLAUSE_DOCUMENT"
REF_EXTERNAL_PORTAL = "EXTERNAL_PORTAL"
REF_SUBMISSION_PORTAL = "SUBMISSION_PORTAL"
REF_CONTROLLED_DATA = "CONTROLLED_DATA"
REF_AUTH_REQUIRED = "AUTH_REQUIRED"
REF_BOT_BLOCKED = "BOT_BLOCKED"
REF_UNKNOWN = "UNKNOWN_REFERENCE"
REF_SAM_DESCRIPTION = "SAM_DESCRIPTION"
REF_SAM_RESOURCE = "SAM_RESOURCE"

# Technical-data access states (do not hard-code cFolders)
TECH_PUBLIC_AVAILABLE = "PUBLIC_TECHNICAL_DATA_AVAILABLE"
TECH_PUBLIC_PACKAGE = "PUBLIC_SOLICITATION_PACKAGE_AVAILABLE"
TECH_DIBBS_REF = "DIBBS_REFERENCE_AVAILABLE"
TECH_TDMT_REF = "TDMT_REFERENCE_AVAILABLE"
TECH_CONTROLLED = "CONTROLLED_TECHNICAL_DATA"
TECH_JCP_REQUIRED = "JCP_OR_ELIGIBILITY_REQUIRED"
TECH_AUTH_REQUIRED = "AUTH_REQUIRED"
TECH_BUYER_REQUEST = "BUYER_REQUEST_REQUIRED"
TECH_NO_GOVT_DATA = "NO_GOVERNMENT_TECHNICAL_DATA"
TECH_EXTERNAL_SOURCE = "EXTERNAL_SOURCE_REFERENCE"
TECH_UNKNOWN = "TECHNICAL_DATA_UNKNOWN"

# Structure
STRUCT_SINGLE_ITEM_RFQ = "SINGLE_ITEM_RFQ"
STRUCT_MULTI_LINE_RFQ = "MULTI_LINE_RFQ"
STRUCT_IDC = "IDC"
STRUCT_SIDC = "SIDC"
STRUCT_BPA_ORDER = "BPA_ORDER"
STRUCT_DELIVERY_ORDER = "DELIVERY_ORDER"
STRUCT_UNKNOWN = "UNKNOWN_STRUCTURE"

# Identity
ID_EXACT_NSN = "EXACT_NSN"
ID_EXACT_OEM_PART = "EXACT_OEM_PART"
ID_EXACT_APPROVED_SOURCE_PART = "EXACT_APPROVED_SOURCE_PART"
ID_EXACT_MODEL = "EXACT_MODEL"
ID_EXACT_SKU = "EXACT_SKU"
ID_SPEC_IDENTIFIED = "SPEC_IDENTIFIED"
ID_CATEGORY_IDENTIFIED = "CATEGORY_IDENTIFIED"
ID_AMBIGUOUS = "AMBIGUOUS"
ID_UNKNOWN = "UNKNOWN"

# Product-transaction readiness
READY_DISCOVERED_ONLY = "DISCOVERED_ONLY"
READY_DESCRIPTION_RECOVERED = "DESCRIPTION_RECOVERED"
READY_PACKAGE_PARTIAL = "PACKAGE_PARTIAL"
READY_PACKAGE_RECOVERED = "PACKAGE_RECOVERED"
READY_PRODUCT_IDENTITY_PARTIAL = "PRODUCT_IDENTITY_PARTIAL"
READY_PRODUCT_IDENTITY_EXACT = "PRODUCT_IDENTITY_EXACT"
READY_TRANSACTION_STRUCTURE_PARTIAL = "TRANSACTION_STRUCTURE_PARTIAL"
READY_TRANSACTION_STRUCTURE_COMPLETE = "TRANSACTION_STRUCTURE_COMPLETE"
READY_COMMERCIAL_RESEARCH = "COMMERCIAL_RESEARCH_READY"
READY_HISTORICAL_RESEARCH = "HISTORICAL_RESEARCH_READY"
READY_BLOCKED_CONTROLLED = "BLOCKED_BY_CONTROLLED_DATA"
READY_BLOCKED_MISSING_PACKAGE = "BLOCKED_BY_MISSING_PUBLIC_PACKAGE"
READY_HUMAN_DOCUMENT_ACCESS = "HUMAN_DOCUMENT_ACCESS_EVENTUALLY_REQUIRED"
READY_ECONOMIC_POTENTIAL_DOC_ACCESS = "ECONOMIC_RESEARCH_POTENTIAL_DOCUMENT_ACCESS_REQUIRED"

# Enrichment checkpoint
ENRICHMENT_CHECKPOINT_KEY = "m3_federal_dla_enrichment_v1"
ENRICHMENT_VERSION = "20260918-m3-federal-dla-product-intelligence-1"

# Pipeline durable pointer (file-primary for large stores)
PIPELINE_DURABLE_POINTER_KEY = "m3_pipeline_durable_pointer_v1"
