"""Funding Path Intelligence — status / type constants (deterministic, no API calls)."""

from __future__ import annotations

# --- Funding path types ---
PATH_PO_FINANCING = "PO_FINANCING"
PATH_CONTRACT_FINANCING_PRIVATE = "CONTRACT_FINANCING_PRIVATE"
PATH_SUPPLIER_TERMS = "SUPPLIER_TERMS"
PATH_SUPPLIER_DIRECT_PAY = "SUPPLIER_DIRECT_PAY_STRUCTURE"
PATH_DISTRIBUTOR_CREDIT = "DISTRIBUTOR_CREDIT"
PATH_MANUFACTURER_CREDIT = "MANUFACTURER_CREDIT"
PATH_INVOICE_FACTORING = "INVOICE_FACTORING"
PATH_AR_FINANCING = "ACCOUNTS_RECEIVABLE_FINANCING"
PATH_HYBRID_SUPPLIER_PLUS_PO = "HYBRID_SUPPLIER_PLUS_PO_FINANCE"
PATH_HYBRID_PO_PLUS_FACTORING = "HYBRID_PO_FINANCE_PLUS_FACTORING"
PATH_GOV_ADVANCE = "GOVERNMENT_COMMERCIAL_ADVANCE_PAYMENT"
PATH_GOV_INTERIM = "GOVERNMENT_COMMERCIAL_INTERIM_PAYMENT"
PATH_GOV_INSTALLMENT = "GOVERNMENT_INSTALLMENT_PAYMENT"
PATH_GOV_PROGRESS = "GOVERNMENT_PROGRESS_PAYMENT"
PATH_GOV_OTHER = "GOVERNMENT_OTHER_CONTRACT_FINANCING"
PATH_OTHER_VERIFIED = "OTHER_VERIFIED_STRUCTURE"

FUNDING_PATH_TYPES: tuple[str, ...] = (
    PATH_PO_FINANCING,
    PATH_CONTRACT_FINANCING_PRIVATE,
    PATH_SUPPLIER_TERMS,
    PATH_SUPPLIER_DIRECT_PAY,
    PATH_DISTRIBUTOR_CREDIT,
    PATH_MANUFACTURER_CREDIT,
    PATH_INVOICE_FACTORING,
    PATH_AR_FINANCING,
    PATH_HYBRID_SUPPLIER_PLUS_PO,
    PATH_HYBRID_PO_PLUS_FACTORING,
    PATH_GOV_ADVANCE,
    PATH_GOV_INTERIM,
    PATH_GOV_INSTALLMENT,
    PATH_GOV_PROGRESS,
    PATH_GOV_OTHER,
    PATH_OTHER_VERIFIED,
)

# Structure availability (per path / solicitation)
STRUCT_AVAILABLE = "AVAILABLE"
STRUCT_POTENTIALLY = "POTENTIALLY_AVAILABLE"
STRUCT_NEEDS_VERIFICATION = "NEEDS_VERIFICATION"
STRUCT_NOT_APPLICABLE = "NOT_APPLICABLE"
STRUCT_PROHIBITED = "PROHIBITED"
STRUCT_REJECTED = "REJECTED"

# Source match results
MATCH_MATCH = "MATCH"
MATCH_CONDITIONAL = "CONDITIONAL_MATCH"
MATCH_NEEDS_VERIFICATION = "NEEDS_VERIFICATION"
MATCH_REJECT = "REJECT"
MATCH_NOT_APPLICABLE = "NOT_APPLICABLE"

# Deal-level funding confidence
CONF_UNASSESSED = "UNASSESSED"
CONF_NO_KNOWN_PATH = "NO_KNOWN_PATH"
CONF_THEORETICAL_ONLY = "THEORETICAL_PATH_ONLY"
CONF_NEEDS_LENDER_VERIFICATION = "NEEDS_LENDER_VERIFICATION"
CONF_PRELIMINARY_MATCH = "PRELIMINARY_MATCH"
CONF_MULTIPLE_PRELIMINARY = "MULTIPLE_PRELIMINARY_MATCHES"
CONF_VERIFIED_PRE_BID = "VERIFIED_PRE_BID_PATH"
CONF_POST_AWARD_REQUIRED = "POST_AWARD_VERIFICATION_REQUIRED"
CONF_APPLICATION_IN_PROGRESS = "FUNDING_APPLICATION_IN_PROGRESS"
CONF_CONDITIONALLY_APPROVED = "CONDITIONALLY_APPROVED"
CONF_SECURED = "FUNDING_SECURED"
CONF_REJECTED = "FUNDING_REJECTED"
CONF_MANUAL_REVIEW = "MANUAL_REVIEW"

# Funding readiness gate
READY_PRE_BID = "FUNDING_READY_PRE_BID"
READY_PLAUSIBLE = "FUNDING_PLAUSIBLE_NEEDS_VERIFICATION"
READY_UNKNOWN = "FUNDING_UNKNOWN"
READY_HARD_FAIL = "FUNDING_HARD_FAIL"
READY_POST_AWARD = "POST_AWARD_FUNDING_REQUIRED"

# Funding stage
STAGE_PRE_BID = "PRE_BID"
STAGE_POST_AWARD = "POST_AWARD"

# Criterion verification status
EV_VERIFIED_PUBLIC = "VERIFIED_PUBLIC"
EV_VERIFIED_BY_CALL = "VERIFIED_BY_CALL"
EV_VERIFIED_BY_EMAIL = "VERIFIED_BY_EMAIL"
EV_VERIFIED_BY_DOCUMENT = "VERIFIED_BY_DOCUMENT"
EV_INFERRED = "INFERRED"
EV_UNKNOWN = "UNKNOWN"
EV_STALE = "STALE"
EV_CONFLICTING = "CONFLICTING"
EV_PROPOSED_AI = "PROPOSED_AI_UNCONFIRMED"

VERIFIED_EVIDENCE = frozenset(
    {EV_VERIFIED_PUBLIC, EV_VERIFIED_BY_CALL, EV_VERIFIED_BY_EMAIL, EV_VERIFIED_BY_DOCUMENT}
)

# Personal guarantee policy values on sources
PG_REQUIRED = "REQUIRED"
PG_NOT_REQUIRED = "NOT_REQUIRED"
PG_CONDITIONAL = "CONDITIONAL"
PG_UNKNOWN = "UNKNOWN"

# Assignment of claims
ASSIGN_UNKNOWN = "UNKNOWN"
ASSIGN_POSSIBLE = "POSSIBLE"
ASSIGN_NOT_APPLICABLE = "NOT_APPLICABLE"
ASSIGN_PROHIBITED = "PROHIBITED"
ASSIGN_REQUIRES_REVIEW = "REQUIRES_REVIEW"

# Source activity
SOURCE_ACTIVE = "ACTIVE"
SOURCE_INACTIVE = "INACTIVE"
SOURCE_NEEDS_REVERIFY = "NEEDS_REVERIFY"

# Operating policy (authoritative) — PG ≠ automatic reject; credit ≠ guarantee
HARD_POLICY = {
    "personal_guarantee_allowed": True,  # allowed as OPERATOR RISK DECISION; not auto-approve
    "personal_guarantee_auto_reject": False,
    "personal_credit_allowed": False,  # qualifying personal credit as underwriting gate still blocked when verified
    "personal_cash_contribution_allowed": False,
    "assume_business_credit": False,
    "assume_net30_supplier_terms": False,
    "assume_lender_finances_because_gov_customer": False,
    "minimum_actual_profit_usd": 10000.0,
    "operator_personal_fico_approx": 480,
    "operator_fico_is_global_lender_veto": False,
}

# Fixture / test marker
DATA_FIXTURE = "TEST_FIXTURE"
DATA_PRODUCTION = "PRODUCTION"
DATA_SEED_UNVERIFIED = "SEED_UNVERIFIED"

# Provider role
ROLE_DIRECT_FUNDER = "DIRECT_FUNDER"
ROLE_BROKER = "BROKER"
ROLE_MARKETPLACE = "MARKETPLACE"
ROLE_REFERRAL = "REFERRAL_NETWORK"
ROLE_UNKNOWN = "UNKNOWN"

# Launch fit vs current company profile
FIT_REJECT_NOW = "REJECT_NOW"
FIT_POTENTIAL_MATCH = "POTENTIAL_MATCH"
FIT_NEEDS_VERIFICATION = "NEEDS_VERIFICATION"
FIT_FUTURE_MATCH = "FUTURE_MATCH"
FIT_NOT_APPLICABLE = "NOT_APPLICABLE"

# Operator call priority
CALL_NOW = "CALL_NOW"
CALL_AFTER_FIRST_AWARD = "CALL_AFTER_FIRST_AWARD"
CALL_LOW_PRIORITY = "LOW_PRIORITY"
CALL_DO_NOT_CALL_NOW = "DO_NOT_CALL_NOW"

# Product-resale fit
RESALE_STRONG = "STRONG"
RESALE_POSSIBLE = "POSSIBLE"
RESALE_WEAK = "WEAK"
RESALE_NO = "NO"
RESALE_UNKNOWN = "UNKNOWN"

# Research HTTP budget (public GET only)
MAX_PUBLIC_FINANCING_HTTP = 40

# Provider role
ROLE_DIRECT_FUNDER = "DIRECT_FUNDER"
ROLE_BROKER = "BROKER"
ROLE_MARKETPLACE = "MARKETPLACE"
ROLE_REFERRAL_NETWORK = "REFERRAL_NETWORK"
ROLE_UNKNOWN = "UNKNOWN"

# Launch fit vs launch-company profile
FIT_REJECT_NOW = "REJECT_NOW"
FIT_POTENTIAL_MATCH = "POTENTIAL_MATCH"
FIT_NEEDS_VERIFICATION = "NEEDS_VERIFICATION"
FIT_FUTURE_MATCH = "FUTURE_MATCH"
FIT_NOT_APPLICABLE = "NOT_APPLICABLE"

# Call priority
CALL_NOW = "CALL_NOW"
CALL_AFTER_FIRST_AWARD = "CALL_AFTER_FIRST_AWARD"
CALL_LOW_PRIORITY = "LOW_PRIORITY"
CALL_DO_NOT_CALL_NOW = "DO_NOT_CALL_NOW"

# Product-resale fit
RESALE_STRONG = "STRONG"
RESALE_POSSIBLE = "POSSIBLE"
RESALE_WEAK = "WEAK"
RESALE_NO = "NO"
RESALE_UNKNOWN = "UNKNOWN"
