"""Constants for historical case-study inventory and temporal evidence firewall."""

from __future__ import annotations

# --- Case classification ---
CLASS_CORE_PRODUCT_RESALE = "CORE_PRODUCT_RESALE"
CLASS_PRODUCT_PLUS_INCIDENTAL_SERVICE = "PRODUCT_PLUS_INCIDENTAL_SERVICE"
CLASS_SERVICE_DOMINANT = "SERVICE_DOMINANT"
CLASS_CONSTRUCTION = "CONSTRUCTION"
CLASS_GRANT_OR_INNOVATION = "GRANT_OR_INNOVATION"
CLASS_HYPOTHETICAL_EXAMPLE = "HYPOTHETICAL_EXAMPLE"
CLASS_PROMOTIONAL_CLAIM = "PROMOTIONAL_CLAIM"
CLASS_OTHER = "OTHER"

PRIMARY_BACKTEST_CLASSES = frozenset(
    {
        CLASS_CORE_PRODUCT_RESALE,
        CLASS_PRODUCT_PLUS_INCIDENTAL_SERVICE,
    }
)

# --- Claim / fact status ---
STATUS_SOURCE_CLAIM = "SOURCE_CLAIM"
STATUS_VERIFIED = "VERIFIED"
STATUS_EVIDENCE_BOUNDED_ESTIMATE = "EVIDENCE_BOUNDED_ESTIMATE"
STATUS_UNKNOWN = "UNKNOWN"
STATUS_SOURCE_CLAIM_ONLY = "SOURCE_CLAIM_ONLY"

# --- Temporal evidence states ---
TEMPORAL_AVAILABLE_BEFORE_CUTOFF = "AVAILABLE_BEFORE_CUTOFF"
TEMPORAL_AVAILABLE_AT_CUTOFF = "AVAILABLE_AT_CUTOFF"
TEMPORAL_POST_CUTOFF = "POST_CUTOFF"
TEMPORAL_PUBLICATION_DATE_UNKNOWN = "PUBLICATION_DATE_UNKNOWN"
TEMPORAL_TEMPORAL_CONFLICT = "TEMPORAL_CONFLICT"
TEMPORAL_NOT_APPLICABLE = "NOT_APPLICABLE"

# --- Evidence roles ---
ROLE_PRE_BID_DISCOVERY = "PRE_BID_DISCOVERY_EVIDENCE"
ROLE_PRE_BID_REQUIREMENT = "PRE_BID_REQUIREMENT_EVIDENCE"
ROLE_PRE_BID_SUPPLIER = "PRE_BID_SUPPLIER_EVIDENCE"
ROLE_PRE_BID_PRICE = "PRE_BID_PRICE_EVIDENCE"
ROLE_PRE_BID_FUNDING = "PRE_BID_FUNDING_EVIDENCE"
ROLE_POST_BID_AWARD = "POST_BID_AWARD_EVIDENCE"
ROLE_POST_BID_PERFORMANCE = "POST_BID_PERFORMANCE_EVIDENCE"
ROLE_POST_BID_PAYMENT = "POST_BID_PAYMENT_EVIDENCE"
ROLE_POST_BID_OUTCOME = "POST_BID_OUTCOME_EVIDENCE"
ROLE_UNKNOWN = "UNKNOWN_ROLE"

PRE_BID_ROLES = frozenset(
    {
        ROLE_PRE_BID_DISCOVERY,
        ROLE_PRE_BID_REQUIREMENT,
        ROLE_PRE_BID_SUPPLIER,
        ROLE_PRE_BID_PRICE,
        ROLE_PRE_BID_FUNDING,
    }
)
POST_BID_ROLES = frozenset(
    {
        ROLE_POST_BID_AWARD,
        ROLE_POST_BID_PERFORMANCE,
        ROLE_POST_BID_PAYMENT,
        ROLE_POST_BID_OUTCOME,
    }
)

# --- Simulation cutoff confidence ---
CUTOFF_HIGH = "SIMULATION_CUTOFF_HIGH_CONFIDENCE"
CUTOFF_MEDIUM = "SIMULATION_CUTOFF_MEDIUM_CONFIDENCE"
CUTOFF_LOW = "SIMULATION_CUTOFF_LOW_CONFIDENCE"
CUTOFF_UNAVAILABLE = "SIMULATION_CUTOFF_UNAVAILABLE"

# --- Traceability ---
TRACE_FULLY = "FULLY_TRACEABLE"
TRACE_STRONGLY = "STRONGLY_TRACEABLE"
TRACE_PARTIALLY = "PARTIALLY_TRACEABLE"
TRACE_WEAKLY = "WEAKLY_TRACEABLE"
TRACE_UNTRACEABLE = "UNTRACEABLE"

# --- Backtest suitability ---
BACKTEST_READY = "BACKTEST_READY"
BACKTEST_READY_WITH_LIMITATIONS = "BACKTEST_READY_WITH_LIMITATIONS"
BACKTEST_RESEARCH_REQUIRED = "RESEARCH_REQUIRED"
BACKTEST_NOT_SUITABLE = "NOT_SUITABLE"
BACKTEST_HYPOTHETICAL_ONLY = "HYPOTHETICAL_ONLY"

# --- Research quality (no fake percentages) ---
QUALITY_HIGH = "HIGH"
QUALITY_MEDIUM = "MEDIUM"
QUALITY_LOW = "LOW"
QUALITY_INSUFFICIENT = "INSUFFICIENT"

# --- Counterfactual outcomes (never WOULD_HAVE_WON) ---
CF_WOULD_HAVE_FOUND = "WOULD_HAVE_FOUND"
CF_WOULD_HAVE_QUALIFIED = "WOULD_HAVE_QUALIFIED"
CF_WOULD_HAVE_CONTINUED = "WOULD_HAVE_CONTINUED"
CF_WOULD_HAVE_REJECTED = "WOULD_HAVE_REJECTED"
CF_INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
# Explicitly forbidden token for docs/tests:
FORBIDDEN_COUNTERFACTUAL = "WOULD_HAVE_WON"

# --- Source corpus status ---
CORPUS_AVAILABLE = "SOURCE_CORPUS_AVAILABLE"
CORPUS_PARTIAL = "SOURCE_CORPUS_PARTIAL"
CORPUS_NOT_AVAILABLE = "SOURCE_CORPUS_NOT_AVAILABLE"

# --- Simulation namespace (isolation from LIVE) ---
SIMULATION_NAMESPACE = "HISTORICAL_SIMULATION"
LIVE_IOWA_SOLICITATION = "645-DOTRFB-2975-2027"

# Simulation cutoff selection rule (documented, reproducible — not discovery timing proof)
# Simulate at midpoint between posting and deadline when both known; floor at posting+1 day.
CUTOFF_RULE_ID = "MIDPOINT_AFTER_POSTING_BEFORE_DEADLINE_V1"
CUTOFF_RULE_DESCRIPTION = (
    "When solicitation_posting_date and bid_deadline are both known, set simulation_as_of "
    "to the UTC midpoint between posting and deadline, floored to posting + 1 calendar day "
    "if the midpoint would otherwise be earlier. This is a reproducible candidate cutoff; "
    "it does not prove actual historical discovery timing."
)

# Artifact directory under govtracker/artifacts (LIVE packets stay elsewhere)
HISTORICAL_ARTIFACT_DIRNAME = "historical_simulation"
