"""M3 evidence acquisition constants — failure reasons, access states, commercial states."""

from __future__ import annotations

# Structured evidence failure reasons (do not collapse to requirements_insufficient alone)
LISTING_ONLY = "LISTING_ONLY"
PACKAGE_URL_MISSING = "PACKAGE_URL_MISSING"
PACKAGE_URL_FOUND_NOT_FETCHED = "PACKAGE_URL_FOUND_NOT_FETCHED"
ATTACHMENT_NOT_FETCHED = "ATTACHMENT_NOT_FETCHED"
ATTACHMENT_PARSE_FAILED = "ATTACHMENT_PARSE_FAILED"
SOURCE_CHANGED = "SOURCE_CHANGED"
SOURCE_BLOCKED = "SOURCE_BLOCKED"
BOT_PROTECTED = "BOT_PROTECTED"
AUTH_REQUIRED = "AUTH_REQUIRED"
REGISTRATION_REQUIRED = "REGISTRATION_REQUIRED"
PUBLIC_METADATA_ONLY = "PUBLIC_METADATA_ONLY"
ALTERNATE_ROUTE_NOT_TRIED = "ALTERNATE_ROUTE_NOT_TRIED"
WEB_SEARCH_NOT_TRIED = "WEB_SEARCH_NOT_TRIED"
GOVERNMENT_SOURCE_NOT_FOUND = "GOVERNMENT_SOURCE_NOT_FOUND"
PACKAGE_FOUND_IN_ALTERNATE_SOURCE = "PACKAGE_FOUND_IN_ALTERNATE_SOURCE"
INSUFFICIENT_REQUIREMENTS_AFTER_RECOVERY = "INSUFFICIENT_REQUIREMENTS_AFTER_RECOVERY"
OTHER_EXPLICIT_REASON = "OTHER_EXPLICIT_REASON"

# Source access states
SA_PUBLIC = "PUBLIC"
SA_PUBLIC_METADATA_ONLY = "PUBLIC_METADATA_ONLY"
SA_AUTH_REQUIRED = "AUTH_REQUIRED"
SA_REGISTRATION_REQUIRED = "REGISTRATION_REQUIRED"
SA_CREDENTIALS_AVAILABLE = "CREDENTIALS_AVAILABLE"
SA_AUTHENTICATED = "AUTHENTICATED"
SA_AUTH_FAILED = "AUTH_FAILED"
SA_BOT_PROTECTED = "BOT_PROTECTED"
SA_SOURCE_CHANGED = "SOURCE_CHANGED"
SA_UNAVAILABLE = "UNAVAILABLE"

# Deal-type after evidence
DT_PRODUCT_RESALE = "PRODUCT_RESALE"
DT_SERVICE = "SERVICE"
DT_CONSTRUCTION = "CONSTRUCTION"
DT_MIXED = "MIXED"
DT_UNKNOWN = "UNKNOWN"

# Commercial / wholesale states
PUBLIC_PRICE_UNWORKABLE = "PUBLIC_PRICE_UNWORKABLE"
WHOLESALE_PRICE_VERIFICATION_REQUIRED = "WHOLESALE_PRICE_VERIFICATION_REQUIRED"
VERIFIED_ACQUISITION_UNWORKABLE = "VERIFIED_ACQUISITION_UNWORKABLE"
VERIFIED_ACQUISITION_WORKABLE = "VERIFIED_ACQUISITION_WORKABLE"
PUBLIC_RESEARCH_INCOMPLETE = "PUBLIC_RESEARCH_INCOMPLETE"
WHOLESALE_ACCESS_UNKNOWN = "WHOLESALE_ACCESS_UNKNOWN"

# Competition history signals (intelligence, not auto-reject)
OPEN_RESELLER_COMPETITION = "OPEN_RESELLER_COMPETITION"
RESELLER_HISTORY_PRESENT = "RESELLER_HISTORY_PRESENT"
OEM_DOMINATED_HISTORY = "OEM_DOMINATED_HISTORY"
SPECIALIZED_DISTRIBUTION_LIKELY = "SPECIALIZED_DISTRIBUTION_LIKELY"
WHOLESALE_ACCESS_MAY_BE_REQUIRED = "WHOLESALE_ACCESS_MAY_BE_REQUIRED"
COMPETITION_HISTORY_UNKNOWN = "COMPETITION_HISTORY_UNKNOWN"

# Evidence ladder tiers
TIER_0_EXISTING = "TIER_0_EXISTING"
TIER_1_DIRECT = "TIER_1_DIRECT"
TIER_2_ALTERNATE = "TIER_2_ALTERNATE"
TIER_3_WEB = "TIER_3_WEB"
TIER_4_OPENAI_WEB = "TIER_4_OPENAI_WEB"

# Evidence authority
AUTH_AUTHORITATIVE = "authoritative"
AUTH_SECONDARY = "secondary"
AUTH_HISTORICAL = "historical"
