"""National incremental discovery & tracking — constants and enums."""

from __future__ import annotations

# Operating modes
MODE_BOOTSTRAP = "BOOTSTRAP_DISCOVERY"
MODE_INCREMENTAL = "INCREMENTAL_DISCOVERY"

# Source registry health / lifecycle
SRC_DISCOVERED_UNVALIDATED = "DISCOVERED_UNVALIDATED"
SRC_VALIDATING = "VALIDATING"
SRC_HEALTHY = "HEALTHY_PRODUCTION"
SRC_DEGRADED = "DEGRADED"
SRC_AUTH = "AUTH_REQUIRED"
SRC_ANTI = "ANTI_AUTOMATION"
SRC_NOT_SOLICITATION = "NOT_A_SOLICITATION_SOURCE"
SRC_DUPLICATE = "DUPLICATE_SOURCE"
SRC_REPLACED = "REPLACED"
SRC_DEAD = "DEAD"
SRC_QUARANTINED = "QUARANTINED"
SRC_UNKNOWN = "UNKNOWN"

# Discovery cycle completeness
CYCLE_COMPLETE = "COMPLETE"
CYCLE_INCOMPLETE = "INCOMPLETE"

# Record change states
CHG_UNCHANGED = "UNCHANGED"
CHG_METADATA = "METADATA_CHANGED"
CHG_CONTENT = "CONTENT_CHANGED"
CHG_PACKAGE = "PACKAGE_CHANGED"
CHG_AMENDMENT = "AMENDMENT_ADDED"
CHG_QA = "QA_ADDED"
CHG_DEADLINE = "DEADLINE_CHANGED"
CHG_STATUS = "STATUS_CHANGED"
CHG_CANCELLED = "CANCELLED"
CHG_AWARDED = "AWARDED"
CHG_CLOSED = "CLOSED"
CHG_REOPENED = "REOPENED"
CHG_UNKNOWN = "UNKNOWN_CHANGE"
CHG_NEW = "NEW"

# Severity
SEV_CRITICAL = "CRITICAL"
SEV_MATERIAL = "MATERIAL"
SEV_INFO = "INFORMATIONAL"
SEV_NONMATERIAL = "NONMATERIAL"
SEV_UNKNOWN = "UNKNOWN"

# Inventory / stage states
INV_NEW = "NEW"
INV_CHEAP_SCREENING = "CHEAP_SCREENING"
INV_RESEARCH_QUEUED = "RESEARCH_QUEUED"
INV_AUTONOMOUS_RESEARCH = "AUTONOMOUS_RESEARCH"
INV_PRELIMINARY = "PRELIMINARY_POTENTIAL"
INV_PURSUIT_UNCERTAIN = "PURSUIT_WORTHY_WITH_UNCERTAINTY"
INV_PURSUIT_WORTHY = "PURSUIT_WORTHY"
INV_FUTURE_COMMERCIAL = "FUTURE_COMMERCIAL_VERIFICATION"
INV_FUTURE_FUNDING = "FUTURE_FUNDING_VERIFICATION"
INV_BID_PREP = "BID_PREP"
INV_SUBMITTED = "SUBMITTED"
INV_AWAITING = "AWAITING_RESULT"
INV_AWARDED = "AWARDED"
INV_NOT_AWARDED = "NOT_AWARDED"
INV_CANCELLED = "CANCELLED"
INV_REJECTED = "REJECTED"
INV_CLOSED = "CLOSED"
INV_POST_AMENDMENT = "POST_SUBMISSION_AMENDMENT"
INV_CLARIFICATION = "CLARIFICATION_ACTIVITY"
INV_UNKNOWN_RESULT = "UNKNOWN_RESULT"

# Monitoring tiers
MON_NORMAL = "NORMAL_TRACKING"
MON_ACTIVE = "ACTIVE_PURSUIT"
MON_BID_PREP = "BID_PREPARATION"
MON_DEADLINE_CRITICAL = "DEADLINE_CRITICAL"
MON_POST_SUBMISSION = "POST_SUBMISSION"

# Funnel stages
STAGE_0 = "STAGE_0_NORMALIZE_DEDUPE"
STAGE_1 = "STAGE_1_ULTRA_CHEAP_BOX"
STAGE_2 = "STAGE_2_TRANSACTION_FIT"
STAGE_3 = "STAGE_3_PACKAGE_ACQUISITION"
STAGE_4 = "STAGE_4_SERIOUS_RESEARCH"
STAGE_5 = "STAGE_5_PURSUIT_QUALIFICATION"

# Ranking label — never win probability
RANK_KIND = "PURSUIT_PRIORITY"

# Reverify marker
REVERIFY_IF_PURSUED = "REVERIFY_IF_PURSUED"

# Government / entity types
ENTITY_TYPES = (
    "FEDERAL",
    "STATE",
    "COUNTY",
    "CITY_MUNICIPAL",
    "K12_SCHOOL_DISTRICT",
    "HIGHER_EDUCATION",
    "AIRPORT",
    "TRANSIT",
    "UTILITY",
    "PUBLIC_AUTHORITY",
    "SPECIAL_DISTRICT",
    "PUBLIC_HEALTHCARE",
    "PORT_AUTHORITY",
    "HOUSING_AUTHORITY",
    "PUBLIC_SAFETY",
    "DOT_TRANSPORTATION",
    "COOPERATIVE",
    "OTHER_PUBLIC",
)

# Platform families
PLATFORM_FAMILIES = (
    "SAM_GOV",
    "JAGGAER_SCIQUEST",
    "BONFIRE",
    "OPENGOV",
    "IONWAVE",
    "BIDNET",
    "PUBLIC_PURCHASE",
    "STATE_OWNED",
    "UNIVERSITY",
    "MUNICIPAL_HTML",
    "PUBLIC_API_FEED",
    "OTHER",
)

DEFAULT_OVERLAP_HOURS = 36
DEFAULT_WEEKLY_SOURCE_DISCOVERY_DAYS = 7
DEFAULT_FRESHNESS_HOURS_NORMAL = 48
DEFAULT_FRESHNESS_HOURS_DEADLINE_CRITICAL = 6
HIGH_VOLUME_TARGET = 25_000

# Readiness
READY_FOR_SUBMISSION = "READY_FOR_SUBMISSION"
NOT_READY_UNREVIEWED_CHANGE = "NOT_READY_UNREVIEWED_MATERIAL_CHANGE"
NOT_READY_STALE = "NOT_READY_STALE_AUTHORITATIVE_CHECK"
