"""Public evidence recovery — evidence classes and decision states."""

from __future__ import annotations

# Evidence authority classes
EV_AUTHORITATIVE_CURRENT = "AUTHORITATIVE_CURRENT_SOLICITATION"
EV_AUTHORITATIVE_HISTORICAL = "AUTHORITATIVE_HISTORICAL_AGENCY"
EV_PUBLIC_AGENCY_REFERENCE = "PUBLIC_AGENCY_REFERENCE"
EV_HISTORICAL_AWARD = "HISTORICAL_AWARD"
EV_MANUFACTURER = "MANUFACTURER_EVIDENCE"
EV_AUTHORIZED_DISTRIBUTOR = "AUTHORIZED_DISTRIBUTOR_EVIDENCE"
EV_COMMERCIAL_DISTRIBUTOR = "COMMERCIAL_DISTRIBUTOR_EVIDENCE"
EV_THIRD_PARTY_MIRROR = "THIRD_PARTY_BID_MIRROR"
EV_SEARCH_DISCOVERY = "SEARCH_DISCOVERY_ONLY"
EV_INFERRED = "INFERRED"
EV_UNKNOWN = "UNKNOWN"

# Product match states
MATCH_EXACT_PUBLIC = "EXACT_PUBLIC_MATCH"
MATCH_STRONG_SPEC = "STRONG_SPEC_MATCH"
MATCH_POSSIBLE = "POSSIBLE_MATCH"
MATCH_HISTORICAL = "HISTORICAL_MATCH"
MATCH_INSUFFICIENT = "INSUFFICIENT_EVIDENCE"
MATCH_NOT = "NOT_MATCH"
MATCH_QUOTE = "QUOTE_REQUIRED"

# Price evidence classes
PRICE_CURRENT_PUBLIC = "CURRENT_PUBLIC_PRICE"
PRICE_HISTORICAL_GOV_UNIT = "HISTORICAL_GOVERNMENT_UNIT_PRICE"
PRICE_HISTORICAL_AWARD_IMPLIED = "HISTORICAL_AWARD_IMPLIED_PRICE"
PRICE_PUBLIC_DISTRIBUTOR = "PUBLIC_DISTRIBUTOR_PRICE"
PRICE_MANUFACTURER_LIST = "MANUFACTURER_LIST_PRICE"
PRICE_RANGE_ONLY = "PRICE_RANGE_ONLY"
PRICE_QUOTE_REQUIRED = "QUOTE_REQUIRED"
PRICE_NONE = "NO_PRICE_EVIDENCE"

# Deadline conflict states
DEADLINE_RESOLVED = "DEADLINE_RESOLVED"
DEADLINE_CONFLICT_UNRESOLVED = "DEADLINE_CONFLICT_UNRESOLVED"
DEADLINE_OPEN_VS_CLOSE_CLARIFIED = "DEADLINE_OPEN_VS_CLOSE_CLARIFIED"
DEADLINE_STALE_MIRROR = "DEADLINE_STALE_MIRROR"
DEADLINE_AMENDMENT = "DEADLINE_AMENDMENT"
DEADLINE_PARSE_ERROR = "DEADLINE_PARSE_ERROR"
DEADLINE_DIFFERENT_EVENT = "DEADLINE_DIFFERENT_EVENT"

# Portal registration decision support
PORTAL_NOT_YET = "PORTAL_REGISTRATION_NOT_YET_JUSTIFIED"
PORTAL_WORTHWHILE = "PORTAL_REGISTRATION_WORTHWHILE"
PORTAL_REQUIRED = "PORTAL_REGISTRATION_REQUIRED_TO_CONTINUE"
PORTAL_TOO_LATE = "PORTAL_REGISTRATION_TOO_LATE"
PORTAL_UNKNOWN = "UNKNOWN"

# Request budgets
PUBLIC_EVIDENCE_TARGET_HTTP = 35
PUBLIC_EVIDENCE_HARD_MAX_HTTP = 50

BLADE_ITEM_CODES = (
    "002367300",
    "002367400",
    "002367530",
    "002367600",
    "002367540",
    "002367700",
)

BLADE_SOLICITATION = "645-DOTRFB-2975-2027"
