"""Pursuit qualification constants — states, reasons, cost evidence."""

from __future__ import annotations

# Pursuit states
PURSUIT_RESEARCHING = "AUTONOMOUS_RESEARCH_IN_PROGRESS"
PURSUIT_INSUFFICIENT = "INSUFFICIENT_PUBLIC_EVIDENCE"
PURSUIT_PRELIMINARY = "PRELIMINARY_POTENTIAL"
PURSUIT_WORTHY = "PURSUIT_WORTHY"
PURSUIT_WORTHY_UNCERTAIN = "PURSUIT_WORTHY_WITH_MATERIAL_UNCERTAINTY"
PURSUIT_DEFER = "DEFER"
PURSUIT_REJECT = "REJECT"

# Action timing
ACTION_TIMING_NOW = "ACTION_NOW"
ACTION_TIMING_FUTURE = "FUTURE_ACTION_IF_PURSUED"
ACTION_TIMING_NONE = "NO_ACTION_REQUIRED"

# Package readiness layers
PKG_PRELIMINARY = "PACKAGE_COMPLETE_FOR_PRELIMINARY_ANALYSIS"
PKG_FORMAL_QUOTE = "PACKAGE_COMPLETE_FOR_FORMAL_QUOTE"
PKG_BID = "PACKAGE_COMPLETE_FOR_BID"
PKG_INCOMPLETE = "PACKAGE_INCOMPLETE"

# Requirement layers
REQ_PRICEABLE = "PRICEABLE_REQUIREMENTS"
REQ_COMPLIANT = "COMPLIANT_PRODUCT_REQUIREMENTS"
REQ_INSUFFICIENT = "REQUIREMENTS_INSUFFICIENT"

# Document materiality
MAT_NONMATERIAL = "NONMATERIAL"
MAT_COMPLIANCE = "MATERIAL_FOR_COMPLIANCE"
MAT_PRICING = "MATERIAL_FOR_PRICING"
MAT_DELIVERY = "MATERIAL_FOR_DELIVERY"
MAT_BID = "MATERIAL_FOR_BID_SUBMISSION"
MAT_UNKNOWN = "MATERIALITY_UNKNOWN"

# Cost evidence states
COST_EXACT_PUBLIC = "CURRENT_EXACT_PUBLIC_PRICE"
COST_COMPARABLE_PUBLIC = "CURRENT_COMPARABLE_PUBLIC_PRICE"
COST_HISTORICAL_EXACT = "HISTORICAL_EXACT_PRICE"
COST_HISTORICAL_COMPARABLE = "HISTORICAL_COMPARABLE_PRICE"
COST_ESTIMATED_RANGE = "ESTIMATED_RANGE"
COST_QUOTE_REQUIRED = "FORMAL_QUOTE_REQUIRED"
COST_UNKNOWN = "UNKNOWN"

# Economic potential
ECON_CLEARLY_UNECONOMIC = "CLEARLY_UNECONOMIC"
ECON_UNLIKELY_FLOOR = "UNLIKELY_TO_REACH_PROFIT_FLOOR"
ECON_POSSIBLE_FLOOR = "POSSIBLE_PROFIT_FLOOR"
ECON_STRONG = "STRONG_PRELIMINARY_POTENTIAL"
ECON_UNKNOWN = "ECONOMICS_UNKNOWN"

# Revenue context
REV_STRONG = "STRONG_CONTEXT"
REV_MODERATE = "MODERATE_CONTEXT"
REV_WEAK = "WEAK_CONTEXT"
REV_UNKNOWN = "UNKNOWN"

# Reject/defer reasons
REASON_PROFIT_IMPLAUSIBLE = "PROFIT_FLOOR_IMPLAUSIBLE"
REASON_MARKET_TOO_SMALL = "MARKET_TOO_SMALL"
REASON_SERVICE_HEAVY = "SERVICE_HEAVY"
REASON_DEADLINE_SHORT = "DEADLINE_TOO_SHORT"
REASON_NO_SUPPLIER = "NO_CREDIBLE_SUPPLIER"
REASON_PRODUCT_UNRESOLVED = "PRODUCT_REQUIREMENTS_UNRESOLVED"
REASON_COMPLIANCE = "COMPLIANCE_RISK_TOO_HIGH"
REASON_FINANCING = "FINANCING_STRUCTURALLY_INCOMPATIBLE"
REASON_INSUFFICIENT = "INSUFFICIENT_PUBLIC_EVIDENCE"
REASON_AUTH = "AUTH_DEPENDENCY"
REASON_COMPETITION = "COMPETITION_CONCERN"

# Source failure classes
SRC_NO_OPEN = "NO_OPEN_RESULTS"
SRC_PARSER = "PARSER_FAILURE"
SRC_CHANGED = "SOURCE_CHANGED"
SRC_AUTH = "AUTH_REQUIRED"
SRC_NETWORK = "NETWORK/DNS"
SRC_ANTI = "ANTI_AUTOMATION"
SRC_BAD_RECIPE = "BAD_SOURCE_RECIPE"
SRC_NOT_DISCOVERY = "NOT_ACTUALLY_DISCOVERY_SOURCE"
SRC_UNKNOWN = "UNKNOWN"

PROFIT_FLOOR = 10_000.0
DEFAULT_FINANCE_FEE_PCT_LOW = 0.02
DEFAULT_FINANCE_FEE_PCT_BASE = 0.04
DEFAULT_FINANCE_FEE_PCT_HIGH = 0.07
DEFAULT_FREIGHT_PCT_LOW = 0.02
DEFAULT_FREIGHT_PCT_BASE = 0.05
DEFAULT_FREIGHT_PCT_HIGH = 0.12
