"""Solicitation package constants, classification, and document access states."""

from __future__ import annotations

# Access states for attempted documents
ACCESS_PUBLIC_FETCHED = "PUBLIC_FETCHED"
ACCESS_LISTED_NOT_FETCHED = "PUBLIC_LISTED_NOT_FETCHED"
ACCESS_AUTH_REQUIRED = "AUTH_REQUIRED"
ACCESS_LOGIN_REQUIRED = "LOGIN_REQUIRED"
ACCESS_BROKEN_LINK = "BROKEN_LINK"
ACCESS_NOT_FOUND = "NOT_FOUND"
ACCESS_UNSUPPORTED = "UNSUPPORTED"
ACCESS_UNKNOWN = "UNKNOWN"

# Document classes / authority roles
DOC_SOLICITATION = "SOLICITATION"
DOC_BID_SCHEDULE = "BID_SCHEDULE"
DOC_PRICING_SHEET = "PRICING_SHEET"
DOC_SPECIFICATION = "SPECIFICATION"
DOC_SOW = "STATEMENT_OF_WORK"
DOC_PURCHASE_DESCRIPTION = "PURCHASE_DESCRIPTION"
DOC_LINE_ITEM_SCHEDULE = "LINE_ITEM_SCHEDULE"
DOC_AMENDMENT = "AMENDMENT"
DOC_Q_AND_A = "Q_AND_A"
DOC_DRAWING = "DRAWING"
DOC_DELIVERY = "DELIVERY_REQUIREMENT"
DOC_TERMS = "TERMS_AND_CONDITIONS"
DOC_VENDOR_FORM = "VENDOR_FORM"
DOC_REFERENCE = "REFERENCE_ONLY"
DOC_UNKNOWN = "UNKNOWN_DOCUMENT"

# Document completeness for transactional resale
COMPLETE_ENOUGH_FOR_PRODUCT_ID = "COMPLETE_ENOUGH_FOR_PRODUCT_ID"
LIKELY_COMPLETE = "LIKELY_COMPLETE"
PARTIAL = "PARTIAL"
CRITICAL_DOCUMENT_MISSING = "CRITICAL_DOCUMENT_MISSING"
AUTH_BLOCKED = "AUTH_BLOCKED"
COMPLETENESS_UNKNOWN = "UNKNOWN"

# Product identification states
PRODUCT_EXACT = "EXACT_PRODUCT_IDENTIFIED"
PRODUCT_PART_NUMBER = "EXACT_PART_NUMBER_IDENTIFIED"
PRODUCT_BRAND_OR_EQUAL = "BRAND_OR_EQUAL_IDENTIFIED"
PRODUCT_SPEC_COMMODITY = "SPEC_DEFINED_COMMODITY"
PRODUCT_MULTIPLE = "MULTIPLE_ACCEPTABLE_PRODUCTS"
PRODUCT_CUSTOM = "CUSTOM_OR_NONSTANDARD_PRODUCT"
PRODUCT_INSUFFICIENT = "INSUFFICIENT_INFORMATION"

# Price evidence
PRICE_VERIFIED_PUBLIC = "VERIFIED_PUBLIC_PRICE"
PRICE_PUBLIC_RANGE = "PUBLIC_PRICE_RANGE"
PRICE_MSRP = "MANUFACTURER_MSRP"
PRICE_DISTRIBUTOR = "DISTRIBUTOR_PUBLIC_PRICE"
PRICE_HISTORICAL = "HISTORICAL_PUBLIC_PRICE"
PRICE_QUOTE_REQUIRED = "QUOTE_REQUIRED"
PRICE_NONE = "NO_PUBLIC_PRICE_FOUND"

# Revenue confidence
REV_KNOWN_BUDGET = "KNOWN_BUDGET"
REV_KNOWN_HISTORICAL = "KNOWN_HISTORICAL_PRICE"
REV_KNOWN_PRIOR_AWARD = "KNOWN_PRIOR_AWARD"
REV_ESTIMATED_EVIDENCE = "ESTIMATED_FROM_EVIDENCE"
REV_UNKNOWN = "UNKNOWN"

# Empty bid price field
PRICE_TO_BE_PROVIDED = "PRICE_TO_BE_PROVIDED"

# Table extraction review flag
TABLE_EXTRACTION_NEEDS_REVIEW = "TABLE_EXTRACTION_NEEDS_REVIEW"

# Operator decisions for procurement pass
DEC_CONTINUE = "CONTINUE"
DEC_GET_SUPPLIER_QUOTE = "GET SUPPLIER QUOTE"
DEC_GET_MISSING_DOCUMENT = "GET MISSING DOCUMENT"
DEC_MANUAL_DOCUMENT_REVIEW = "MANUAL DOCUMENT REVIEW"
DEC_FUNDING_VERIFICATION = "FUNDING VERIFICATION"
DEC_BID_PREPARATION = "BID PREPARATION"
DEC_REJECT = "REJECT"

# Next actions
NEXT_GET_MISSING_DOC = "GET_MISSING_SOLICITATION_DOCUMENT"
NEXT_MANUAL_REVIEW = "MANUAL_DOCUMENT_REVIEW"
NEXT_SUPPLIER_QUOTE = "REQUEST_SUPPLIER_QUOTE"
NEXT_IDENTIFY_PRODUCT = "IDENTIFY_EXACT_PRODUCT"
NEXT_FREIGHT = "ESTIMATE_FREIGHT"
NEXT_REVENUE = "GATHER_REVENUE_EVIDENCE"
NEXT_FUNDING = "FUNDING_VERIFICATION"
NEXT_BID_PREP = "BID_PREPARATION"

# Request budgets for this pass
PROCUREMENT_TARGET_HTTP = 35
PROCUREMENT_HARD_MAX_HTTP = 50
PROCUREMENT_SAM = 0
PROCUREMENT_USASPENDING = 0
PROCUREMENT_OPENAI = 0

SUPPORTED_EXTENSIONS = {
    ".html",
    ".htm",
    ".pdf",
    ".doc",
    ".docx",
    ".xls",
    ".xlsx",
    ".csv",
    ".txt",
    ".zip",
}
