"""Phase L.13 — public artifact types, outcomes, and safety constants."""

from __future__ import annotations

BUILD = "20260928-m3-phase-l13-public-artifact-recovery"

# Workflow branch
PUBLIC_ARTIFACT_RECOVERY = "PUBLIC_ARTIFACT_RECOVERY"

# Artifact types
SOLICITATION_PRINT_VIEW = "SOLICITATION_PRINT_VIEW"
AWARD_PRINT_VIEW = "AWARD_PRINT_VIEW"
AWARD_PDF = "AWARD_PDF"
BID_TAB = "BID_TAB"
TABULATION = "TABULATION"
PUBLIC_ATTACHMENT = "PUBLIC_ATTACHMENT"
AMENDMENT = "AMENDMENT"
SPECIFICATION = "SPECIFICATION"
PRICE_SHEET = "PRICE_SHEET"
BOARD_DOCUMENT = "BOARD_DOCUMENT"
UNKNOWN_PUBLIC_ARTIFACT = "UNKNOWN_PUBLIC_ARTIFACT"

ARTIFACT_TYPES = (
    SOLICITATION_PRINT_VIEW,
    AWARD_PRINT_VIEW,
    AWARD_PDF,
    BID_TAB,
    TABULATION,
    PUBLIC_ATTACHMENT,
    AMENDMENT,
    SPECIFICATION,
    PRICE_SHEET,
    BOARD_DOCUMENT,
    UNKNOWN_PUBLIC_ARTIFACT,
)

# Per-opportunity outcomes
PUBLIC_ARTIFACT_RECOVERED = "PUBLIC_ARTIFACT_RECOVERED"
BUYER_ARTIFACT_RECOVERED = "BUYER_ARTIFACT_RECOVERED"
PUBLIC_METADATA_ONLY = "PUBLIC_METADATA_ONLY"
FREE_REGISTRATION_STILL_REQUIRED = "FREE_REGISTRATION_STILL_REQUIRED"
AUTHENTICATED_HISTORY_REQUIRED = "AUTHENTICATED_HISTORY_REQUIRED"
NO_PUBLIC_ARTIFACT_FOUND = "NO_PUBLIC_ARTIFACT_FOUND"
EVIDENCE_EXHAUSTED = "EVIDENCE_EXHAUSTED"

# Source staleness (hunt fallback inventory)
LIVE_FRESH = "LIVE_FRESH"
LAST_KNOWN_RECENT = "LAST_KNOWN_RECENT"
STALE = "STALE"
UNAVAILABLE = "UNAVAILABLE"

# Safety — explicitly forbidden
FORBIDDEN_ACTIONS = (
    "CAPTCHA_SOLVE",
    "SESSION_SPOOF",
    "COOKIE_THEFT",
    "AUTH_BYPASS",
    "ID_BRUTE_FORCE",
    "HIDDEN_ENDPOINT_ENUMERATION",
    "PROXY_ROTATION_FOR_EVASION",
    "ACCOUNT_CREATION",
)

# Per-opportunity query budget (no global row cap)
DEFAULT_QUERY_BUDGET = 8
DEFAULT_FETCH_BUDGET = 4

# BidNet exact recovery loop order (§15)
BIDNET_RECOVERY_ORDER = (
    "exact_solicitation_search",
    "public_print_search",
    "public_attachment_search",
    "public_award_search",
    "buyer_solicitation_search",
    "buyer_public_record_pivot",
    "registration_classification",
    "evidence_exhausted",
)
