"""Package recovery + SAM credit-aware queue.

Build: 20261005-m3-package-recovery-sam-budget-v1
"""

from __future__ import annotations

BUILD = "20261005-m3-package-recovery-sam-budget-v1"
CORPUS = "LARGE_TEST_CORPUS_V1.json"

CK = "m3_package_recovery_sam_budget_v1_checkpoint.json"
JOB = "m3_package_recovery_sam_budget_v1_job.json"
REPORT = "m3_package_recovery_sam_budget_v1_last_report.json"
REPORT_TXT = "m3_package_recovery_sam_budget_v1_last_report.txt"
PROGRESS = "m3_package_recovery_sam_budget_v1_progress.json"
RESULTS = "m3_package_recovery_sam_budget_v1_results.json"
UI = "m3_package_recovery_sam_budget_v1_ui.json"
CONSERVATION = "m3_package_recovery_sam_budget_v1_conservation.json"
BUYER_MEMORY = "BUYER_PACKAGE_SOURCE_MEMORY.json"
PORTAL_FAMILY = "m3_portal_family_learning_v1.json"
CROSS_MATCH = "CROSS_PORTAL_OPPORTUNITY_MATCH.json"
SAM_QUEUE = "m3_sam_package_priority_queue_v1.json"
REVENUE_QUEUE = "REVENUE_RECOVERY_QUEUE.json"
BASELINE = "m3_package_recovery_baseline_v1.json"

SAM_DAILY_MAX = 10
SAM_RESERVE = 1
CHECKPOINT_EVERY = 10

# Explicit package states (Phase 1)
PACKAGE_ACQUIRED = "PACKAGE_ACQUIRED"
PACKAGE_ACQUIRED_CACHED = "PACKAGE_ACQUIRED_CACHED"
PACKAGE_ACQUIRED_OFFICIAL_ALTERNATE = "PACKAGE_ACQUIRED_OFFICIAL_ALTERNATE"
PACKAGE_ACQUIRED_AGGREGATOR = "PACKAGE_ACQUIRED_AGGREGATOR"
PACKAGE_NOT_ATTEMPTED_SAM_BUDGET = "PACKAGE_NOT_ATTEMPTED_SAM_BUDGET"
PACKAGE_DEFERRED_SAM_PRIORITY = "PACKAGE_DEFERRED_SAM_PRIORITY"
PACKAGE_NOT_FOUND_FREE = "PACKAGE_NOT_FOUND_FREE"
PACKAGE_LOCKED_AGGREGATOR = "PACKAGE_LOCKED_AGGREGATOR"
PACKAGE_OFFICIAL_SOURCE_NOT_FOUND = "PACKAGE_OFFICIAL_SOURCE_NOT_FOUND"
PACKAGE_SOURCE_BLOCKED = "PACKAGE_SOURCE_BLOCKED"
PACKAGE_AUTH_REQUIRED = "PACKAGE_AUTH_REQUIRED"
PACKAGE_API_CREDIT_REQUIRED = "PACKAGE_API_CREDIT_REQUIRED"
PACKAGE_API_CREDIT_EXHAUSTED = "PACKAGE_API_CREDIT_EXHAUSTED"
PACKAGE_API_CALL_FAILED = "PACKAGE_API_CALL_FAILED"
PACKAGE_MISSING = "PACKAGE_MISSING"
PACKAGE_RETRYABLE = "PACKAGE_RETRYABLE"

ACQUIRED_STATES = {
    PACKAGE_ACQUIRED,
    PACKAGE_ACQUIRED_CACHED,
    PACKAGE_ACQUIRED_OFFICIAL_ALTERNATE,
    PACKAGE_ACQUIRED_AGGREGATOR,
}

# SAM queue states
SAM_PACKAGE_CACHED = "SAM_PACKAGE_CACHED"
SAM_PACKAGE_PRIORITY_READY = "SAM_PACKAGE_PRIORITY_READY"
SAM_PACKAGE_QUEUED = "SAM_PACKAGE_QUEUED"
SAM_PACKAGE_DEFERRED_BUDGET = "SAM_PACKAGE_DEFERRED_BUDGET"
SAM_PACKAGE_DEFERRED_LOW_PRIORITY = "SAM_PACKAGE_DEFERRED_LOW_PRIORITY"
SAM_PACKAGE_REQUESTED = "SAM_PACKAGE_REQUESTED"
SAM_PACKAGE_ACQUIRED = "SAM_PACKAGE_ACQUIRED"
SAM_PACKAGE_FAILED_RETRYABLE = "SAM_PACKAGE_FAILED_RETRYABLE"
SAM_PACKAGE_FAILED_TERMINAL = "SAM_PACKAGE_FAILED_TERMINAL"
