"""Line-level basket completion + strict economics gate.

Build: 20261005-m3-line-basket-completion-strict-economics-v1
"""

from __future__ import annotations

BUILD = "20261005-m3-line-basket-completion-strict-economics-v1"

CK = "m3_line_basket_completion_strict_economics_v1_checkpoint.json"
JOB = "m3_line_basket_completion_strict_economics_v1_job.json"
REPORT = "m3_line_basket_completion_strict_economics_v1_last_report.json"
CORPUS_V2 = "m3_basket_completion_corpus_v2.json"
STAGE_TRANSITIONS = "m3_stage_transition_log_v1.json"
LINE_INVENTORY = "m3_line_inventory_v2.json"
PROVENANCE_AUDIT = "m3_price_provenance_audit_v1.json"
CLUSTERS = "m3_commercial_line_clusters_v1.json"
COLLIER_VALIDATION = "m3_collier_hard_validation_v1.json"
CONTROLLED_100 = "m3_controlled_100_strict_economics_v1.json"
CONSERVATION = "m3_line_basket_conservation_v1.json"
QUOTE_RESERVE = "m3_quote_reserve_v1.json"

PRIOR_BOTH_SIDES = "m3_both_sides_basket_corpus_v1.json"
PRIOR_FUNNEL_CK = "m3_basket_full_funnel_reconcile_v1_checkpoint.json"
PRIOR_ACQ_CK = "m3_acquisition_scale_v1_checkpoint.json"
PRIOR_REV = "m3_revenue_evidence_v1_store.json"

COLLIER_OID = "opengov:collier-county-fl:295143"

# Line terminal / conservation buckets
PRICED_EXECUTABLE = "PRICED_EXECUTABLE"
QUOTE_REQUIRED = "QUOTE_REQUIRED"
IDENTITY_UNRESOLVED = "IDENTITY_UNRESOLVED"
IDENTITY_AMBIGUOUS = "IDENTITY_AMBIGUOUS"
NO_PUBLIC_PRICE = "NO_PUBLIC_PRICE"
PUBLIC_PRICE_UNAVAILABLE = "PUBLIC_PRICE_UNAVAILABLE"
NON_MATERIAL = "NON_MATERIAL"
EXECUTION_BLOCKED = "EXECUTION_BLOCKED"
OTHER_EXPLAINED = "OTHER_EXPLAINED"
UOM_UNRESOLVED = "UOM_UNRESOLVED"
PACK_UNRESOLVED = "PACK_UNRESOLVED"
NO_COMPLIANT_SOURCE = "NO_COMPLIANT_SOURCE"
RESEARCH_EXHAUSTED = "RESEARCH_EXHAUSTED"
TIME_BUDGET_EXHAUSTED = "TIME_BUDGET_EXHAUSTED"

CONSERVATION_BUCKETS = (
    PRICED_EXECUTABLE,
    QUOTE_REQUIRED,
    IDENTITY_UNRESOLVED,
    NO_PUBLIC_PRICE,
    NON_MATERIAL,
    EXECUTION_BLOCKED,
    OTHER_EXPLAINED,
)

# Materiality
P0 = "P0"
P1 = "P1"
P2 = "P2"
P3 = "P3"

# Price provenance audit classes
VALID_PRODUCTION_PRICE = "VALID_PRODUCTION_PRICE"
STALE = "STALE"
SENTINEL = "SENTINEL"
FIXTURE = "FIXTURE"
WRONG_IDENTITY = "WRONG_IDENTITY"
WRONG_PACK = "WRONG_PACK"
OTHER_INVALID = "OTHER_INVALID"

# Allowed production PRICE_ORIGIN
PUBLIC_CURRENT = "PUBLIC_CURRENT"
SUPPLIER_QUOTE = "SUPPLIER_QUOTE"
MANUFACTURER_CURRENT = "MANUFACTURER_CURRENT"
AUTHORIZED_DISTRIBUTOR_CURRENT = "AUTHORIZED_DISTRIBUTOR_CURRENT"
ALLOWED_PRICE_ORIGINS = {
    PUBLIC_CURRENT,
    SUPPLIER_QUOTE,
    MANUFACTURER_CURRENT,
    AUTHORIZED_DISTRIBUTOR_CURRENT,
}

# Quote subtypes
OEM_QUOTE_REQUIRED = "OEM_QUOTE_REQUIRED"
DISTRIBUTOR_QUOTE_REQUIRED = "DISTRIBUTOR_QUOTE_REQUIRED"
SUPPLIER_QUOTE_REQUIRED = "SUPPLIER_QUOTE_REQUIRED"

# Basket classes
BASKET_READY_PUBLIC_PRICE = "BASKET_READY_PUBLIC_PRICE"
BASKET_READY_QUOTE_DEPENDENT = "BASKET_READY_QUOTE_DEPENDENT"
BASKET_BLOCKED = "BASKET_BLOCKED"

# Strict economics
ECONOMICS_READY = "ECONOMICS_READY"
ECONOMICS_NOT_READY = "ECONOMICS_NOT_READY"
PROFIT_PROVEN = "PROFIT_PROVEN"
PROFIT_LIKELY = "PROFIT_LIKELY"
PROFIT_POSSIBLE = "PROFIT_POSSIBLE"
PROFIT_UNPROVEN = "PROFIT_UNPROVEN"
UNPROFITABLE = "UNPROFITABLE"

# Categories for routing
CATEGORY_ROUTES = (
    "TOOLS",
    "PLUMBING",
    "MRO",
    "LIGHTING",
    "PPE",
    "OFFICE",
    "FURNITURE",
    "HVAC",
    "AUTO_HD",
    "ELECTRICAL",
    "IRRIGATION",
    "CONSTRUCTION_INSTALL",
    "OTHER",
)

SENTINEL_PRICES = {0.0, 1.0}
MIN_EXECUTABLE_PRICE = 1.51  # align with price_coverage_80.MIN_CREDIBLE_PRICE

PROGRESS_EVERY = 1
ITEM_DEADLINE_S = 120.0
COLLIER_DEADLINE_S = 180.0
CONTROLLED_SAMPLE_N = 100
