"""Evidence exhaustion + last-resort quote reserve models.

Build: 20261004-m3-evidence-exhaustion-v1
"""

from __future__ import annotations

BUILD = "20261004-m3-evidence-exhaustion-v1"

# Product routing
COMMON_BROAD_CHANNEL = "COMMON_BROAD_CHANNEL"
SPECIALTY_OEM_NARROW_CHANNEL = "SPECIALTY_OEM_NARROW_CHANNEL"
STRONG_GENERIC_SPEC = "STRONG_GENERIC_SPEC"
BRAND_OR_EQUAL = "BRAND_OR_EQUAL"
UNKNOWN_CHANNEL = "UNKNOWN_CHANNEL"

ROUTING_CLASSES = {
    COMMON_BROAD_CHANNEL,
    SPECIALTY_OEM_NARROW_CHANNEL,
    STRONG_GENERIC_SPEC,
    BRAND_OR_EQUAL,
    UNKNOWN_CHANNEL,
}

# Price / research terminal distinctions
ROUTE_BLOCKED = "ROUTE_BLOCKED"
ROUTE_DEGRADED = "ROUTE_DEGRADED"
SEARCH_PROVIDER_DOWN = "SEARCH_PROVIDER_DOWN"
DOMAIN_BLOCKED = "DOMAIN_BLOCKED"
PRICE_NOT_EXTRACTABLE = "PRICE_NOT_EXTRACTABLE"
NO_VALID_MATCH = "NO_VALID_MATCH"
NO_PRICE_AFTER_EXHAUSTIVE_SEARCH = "NO_PUBLIC_PRICE_AFTER_EXHAUSTIVE_SEARCH"
NO_HISTORY_AFTER_EXHAUSTIVE_SEARCH = "NO_HISTORY_AFTER_EXHAUSTIVE_SEARCH"
PUBLIC_PRICE_FOUND = "PUBLIC_PRICE_FOUND"
GOV_VALUE_FOUND = "GOV_VALUE_FOUND"
REVENUE_REFERENCE_FOUND = "REVENUE_REFERENCE_FOUND"
ROUTE_BLOCKED_RETRYABLE = "ROUTE_BLOCKED_RETRYABLE"
AI_BUDGET_DEFERRED = "AI_BUDGET_DEFERRED"
RESEARCH_RETRYABLE = "RESEARCH_RETRYABLE"

# Channel signals
OPEN_RESELLER_CHANNEL_CONFIRMED = "OPEN_RESELLER_CHANNEL_CONFIRMED"
INCUMBENT_CHANNEL_ADVANTAGE = "INCUMBENT_CHANNEL_ADVANTAGE"
OEM_DIRECT_POSSIBLE = "OEM_DIRECT_POSSIBLE"
AUTHORIZED_DISTRIBUTOR_PATH = "AUTHORIZED_DISTRIBUTOR_PATH"

# Quote reserve
QUOTE_OUTREACH_RESERVE = "QUOTE_OUTREACH_RESERVE"
OEM_QUOTE_REQUIRED = "OEM_QUOTE_REQUIRED"
DISTRIBUTOR_QUOTE_REQUIRED = "DISTRIBUTOR_QUOTE_REQUIRED"
SUPPLIER_QUOTE_REQUIRED = "SUPPLIER_QUOTE_REQUIRED"
CHANNEL_CONTACT_REQUIRED = "CHANNEL_CONTACT_REQUIRED"

# Pipeline / profit terminals
PROVEN_PROFITABLE = "PROVEN_PROFITABLE"
LIKELY_PROFITABLE = "LIKELY_PROFITABLE"
POSSIBLE_PROFIT = "POSSIBLE_PROFIT"
UNPROFITABLE = "UNPROFITABLE"
EXECUTION_BLOCKED = "EXECUTION_BLOCKED"
INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
UNPROVEN = "UNPROVEN"
LENDER_READY = "LENDER_READY"
NEAR_READY_24H = "NEAR_READY_24H"

# Exhaustion path flags (must be true before reserve)
REQUIRED_EXHAUSTION_FLAGS = (
    "manufacturer_search_exhausted",
    "distributor_search_exhausted",
    "reseller_search_exhausted",
    "direct_catalog_exhausted",
    "structured_data_exhausted",
    "alternate_domain_search_exhausted",
    "history_search_exhausted",
)

OPTIONAL_EXHAUSTION_FLAGS = (
    "generic_spec_search_exhausted",
    "brand_equal_search_exhausted",
    "channel_research_exhausted",
)

# Owner pipeline priority (1 = highest)
OWNER_PIPELINE_PRIORITY = (
    LENDER_READY,
    NEAR_READY_24H,
    PROVEN_PROFITABLE,
    LIKELY_PROFITABLE,
    POSSIBLE_PROFIT,
    "HIGH_VALUE_RESEARCH_IN_PROGRESS",
    QUOTE_OUTREACH_RESERVE,
)

# Surface reserve only when strong leads fall below this
DEFAULT_STRONG_LEAD_THRESHOLD = 10

# Minimum fight score before true failure / reserve allowed
MIN_EXHAUSTION_SCORE_FOR_TERMINAL = 60
