"""BidNet recovery state machine constants."""

from __future__ import annotations

# Progressive enrichment states (ordered)
DISCOVERED = "DISCOVERED"
DETAIL_RECOVERED = "DETAIL_RECOVERED"
DOCUMENTS_RECOVERED = "DOCUMENTS_RECOVERED"
PRODUCT_IDENTIFIED = "PRODUCT_IDENTIFIED"
GOV_VALUE_FOUND = "GOV_VALUE_FOUND"
PUBLIC_COST_FOUND = "PUBLIC_COST_FOUND"
ECONOMICS_READY = "ECONOMICS_READY"
RECOVERY_BLOCKED = "RECOVERY_BLOCKED"

# Terminal / disposition
NOT_PRODUCT = "NOT_PRODUCT"
EXPIRED = "EXPIRED"
DUPLICATE = "DUPLICATE"
CANCELLED = "CANCELLED"

STATE_ORDER = (
    DISCOVERED,
    DETAIL_RECOVERED,
    DOCUMENTS_RECOVERED,
    PRODUCT_IDENTIFIED,
    GOV_VALUE_FOUND,
    PUBLIC_COST_FOUND,
    ECONOMICS_READY,
)

# Blockers
DETAIL_NOT_AVAILABLE = "DETAIL_NOT_AVAILABLE"
DEADLINE_NOT_AVAILABLE = "DEADLINE_NOT_AVAILABLE"
DOCUMENTS_NOT_AVAILABLE = "DOCUMENTS_NOT_AVAILABLE"
AUTH_REQUIRED = "AUTH_REQUIRED"
AUTH_CHALLENGE = "AUTH_CHALLENGE"
AUTH_FAILED = "AUTH_FAILED"
# Free-only package chase (no BidNet membership)
FREE_PACKAGE_FOUND = "FREE_PACKAGE_FOUND"  # legacy alias; prefer VALID/PARTIAL after quality gate
VALID_FREE_PACKAGE_FOUND = "VALID_FREE_PACKAGE_FOUND"
PARTIAL_FREE_PACKAGE_FOUND = "PARTIAL_FREE_PACKAGE_FOUND"
PACKAGE_UNAVAILABLE_FREE = "PACKAGE_UNAVAILABLE_FREE"
PACKAGE_RECOVERY_RETRYABLE = "PACKAGE_RECOVERY_RETRYABLE"
PACKAGE_MATCH_AMBIGUOUS = "PACKAGE_MATCH_AMBIGUOUS"
SOURCE_ERROR = "SOURCE_ERROR"
PRODUCT_IDENTITY_UNCLEAR = "PRODUCT_IDENTITY_UNCLEAR"
NO_GOV_VALUE_EVIDENCE = "NO_GOV_VALUE_EVIDENCE"
NO_PUBLIC_COST_EVIDENCE = "NO_PUBLIC_COST_EVIDENCE"
FREIGHT_UNRESOLVED = "FREIGHT_UNRESOLVED"
BLOCKER_EXPIRED = "EXPIRED"

# Deadline confidence
DEADLINE_CONFIRMED = "CONFIRMED"
DEADLINE_PROBABLE = "PROBABLE"
DEADLINE_UNKNOWN = "UNKNOWN"

# Stop-loss defaults
DEFAULT_MAX_DETAIL_ATTEMPTS = 3
DEFAULT_MAX_DOCUMENT_ATTEMPTS = 2
DEFAULT_MAX_EVIDENCE_ATTEMPTS = 2
