"""Statuses and constants for eligibility + recovery sweep."""

BUILD = "20261004-m3-eligibility-and-recovery-v1"

# Opportunity eligibility (exclusive)
BID_ELIGIBLE = "BID_ELIGIBLE"
BID_ELIGIBLE_WITH_ACTION = "BID_ELIGIBLE_WITH_ACTION"
ELIGIBILITY_UNKNOWN = "ELIGIBILITY_UNKNOWN"
BID_INELIGIBLE = "BID_INELIGIBLE"

ELIGIBILITY_STATUSES = [
    BID_ELIGIBLE,
    BID_ELIGIBLE_WITH_ACTION,
    ELIGIBILITY_UNKNOWN,
    BID_INELIGIBLE,
]

ELIGIBLE_TO_RESEARCH = {BID_ELIGIBLE, BID_ELIGIBLE_WITH_ACTION}

# Condition policy
NEW_REQUIRED = "NEW_REQUIRED"
NEW_ASSUMED = "NEW_ASSUMED"
REMAN_ALLOWED = "REMAN_ALLOWED"
RECONDITIONED_ALLOWED = "RECONDITIONED_ALLOWED"
USED_ALLOWED = "USED_ALLOWED"
CONDITION_UNKNOWN = "CONDITION_UNKNOWN"

# No-token classification
STRONG_GENERIC = "STRONG_GENERIC_COMMERCIAL_SPEC"
REFERENCE_PRODUCT = "REFERENCE_PRODUCT_WITHOUT_TOKEN"
BRAND_OR_EQUAL = "BRAND_OR_EQUAL_GENERIC"
WEAK_GENERIC = "WEAK_GENERIC"
NON_COMMERCIAL = "NON_COMMERCIAL_UNSOURCEABLE"

RESEARCHABLE_NO_TOKEN = {STRONG_GENERIC, REFERENCE_PRODUCT, BRAND_OR_EQUAL}

# Identity terminals (post-sweep)
ID_ADVANCED_TO_BOTH_SIDES = "ADVANCED_TO_BOTH_SIDES"
ID_GOV_ONLY = "GOV_ONLY"
ID_PRICE_ONLY = "PRICE_ONLY"
ID_NO_HISTORY = "NO_HISTORY_EXHAUSTIVE"
ID_NO_PRICE = "NO_PRICE_EXHAUSTIVE"
ID_CONDITION_BLOCK = "CONDITION_BLOCK"
ID_UOM_BLOCK = "UOM_BLOCK"
ID_ELIGIBILITY_BLOCK = "ELIGIBILITY_BLOCK"
ID_DUPLICATE = "DUPLICATE_COLLAPSED"
ID_INSUFFICIENT_GENERIC = "INSUFFICIENT_GENERIC_SPEC"
ID_NOT_PROCESSED = "NOT_PROCESSED"
ID_PIPELINE_BUG = "PIPELINE_BUG"
ID_RETRYABLE = "RETRYABLE_ERROR"
ID_BUDGET_DEFERRED = "AI_BUDGET_DEFERRED"
ID_OTHER = "OTHER_EXPLAINED"

IDENTITY_TERMINALS = [
    ID_ADVANCED_TO_BOTH_SIDES,
    ID_GOV_ONLY,
    ID_PRICE_ONLY,
    ID_NO_HISTORY,
    ID_NO_PRICE,
    ID_CONDITION_BLOCK,
    ID_UOM_BLOCK,
    ID_ELIGIBILITY_BLOCK,
    ID_DUPLICATE,
    ID_INSUFFICIENT_GENERIC,
    ID_NOT_PROCESSED,
    ID_PIPELINE_BUG,
    ID_RETRYABLE,
    ID_BUDGET_DEFERRED,
    ID_OTHER,
]

# Opportunity terminals (post-sweep)
OPP_BID_INELIGIBLE = "BID_INELIGIBLE"
OPP_BID_ELIGIBLE_WITH_ACTION = "BID_ELIGIBLE_WITH_ACTION"
OPP_NO_USABLE_IDENTITY = "NO_USABLE_IDENTITY"
OPP_NO_EVIDENCE = "NO_EVIDENCE"
OPP_GOV_ONLY = "GOV_ONLY"
OPP_PRICE_ONLY = "PRICE_ONLY"
OPP_BOTH_SIDES_PARTIAL = "BOTH_SIDES_PARTIAL"
OPP_BASKET_INCOMPLETE = "BASKET_INCOMPLETE"
OPP_BASKET_READY = "BASKET_READY"
OPP_ECONOMICS_READY = "ECONOMICS_READY"
OPP_PROFITABLE = "PROFITABLE"
OPP_UNPROFITABLE = "UNPROFITABLE"
OPP_EXECUTION_BLOCKED = "EXECUTION_BLOCKED"
OPP_RETRYABLE = "RETRYABLE"
OPP_OTHER = "OTHER_EXPLAINED"

OPPORTUNITY_TERMINALS = [
    OPP_BID_INELIGIBLE,
    OPP_BID_ELIGIBLE_WITH_ACTION,
    OPP_NO_USABLE_IDENTITY,
    OPP_NO_EVIDENCE,
    OPP_GOV_ONLY,
    OPP_PRICE_ONLY,
    OPP_BOTH_SIDES_PARTIAL,
    OPP_BASKET_INCOMPLETE,
    OPP_BASKET_READY,
    OPP_ECONOMICS_READY,
    OPP_PROFITABLE,
    OPP_UNPROFITABLE,
    OPP_EXECUTION_BLOCKED,
    OPP_RETRYABLE,
    OPP_OTHER,
]

# Diversity / sampling defaults
PER_OPP_SAMPLE_LINES = 15
PER_OPP_EXPAND_LINES = 120
MAX_LIVE_PRICE_QUERIES_PER_IDENTITY = 3
MIN_BUDGET_RESERVE = 10
