"""Statuses and constants for human-like public price search."""

from __future__ import annotations

BUILD = "20261004-m3-price-search-reliability-v1"

PUBLIC_PRICE_FOUND = "PUBLIC_PRICE_FOUND"
PUBLIC_PRICE_PARTIAL = "PUBLIC_PRICE_PARTIAL"
NO_PUBLIC_PRICE_AFTER_EXHAUSTIVE_SEARCH = "NO_PUBLIC_PRICE_AFTER_EXHAUSTIVE_SEARCH"
PRICE_SEARCH_BUDGET_EXHAUSTED = "PRICE_SEARCH_BUDGET_EXHAUSTED"
PRICE_SOURCE_BLOCKED_RETRYABLE = "PRICE_SOURCE_BLOCKED_RETRYABLE"
INSUFFICIENT_IDENTITY = "INSUFFICIENT_IDENTITY"
UOM_AMBIGUOUS = "UOM_AMBIGUOUS"
CONDITION_MISMATCH = "CONDITION_MISMATCH"

CONDITION_NEW = "NEW"
CONDITION_RECONDITIONED = "RECONDITIONED"
CONDITION_REMANUFACTURED = "REMANUFACTURED"
CONDITION_USED = "USED"
CONDITION_UNKNOWN = "UNKNOWN"

SELLER_MANUFACTURER = "MANUFACTURER"
SELLER_DISTRIBUTOR = "DISTRIBUTOR"
SELLER_RESELLER = "RESELLER"
SELLER_MARKETPLACE = "MARKETPLACE"
SELLER_SNIPPET = "SNIPPET"

DEFAULT_QUERY_BUDGET = 250  # SERP/query units per run day for price search
PER_IDENTITY_QUERY_CAP = 4
PER_IDENTITY_PAGE_CAP = 6
