"""BidNet authentication status constants."""

from __future__ import annotations

CONNECTED = "CONNECTED"
SESSION_REUSED = "SESSION_REUSED"
LOGIN_REQUIRED = "LOGIN_REQUIRED"
LOGIN_SUCCESS = "LOGIN_SUCCESS"
AUTH_CHALLENGE = "AUTH_CHALLENGE"
AUTH_FAILED = "AUTH_FAILED"
EXPIRED = "EXPIRED"
DISABLED = "DISABLED"

AUTHENTICATED_STATUSES = frozenset({CONNECTED, SESSION_REUSED, LOGIN_SUCCESS})
BLOCKING_STATUSES = frozenset({AUTH_CHALLENGE, AUTH_FAILED, EXPIRED, DISABLED, LOGIN_REQUIRED})
