"""P0 pre-scale hardening — close all 8 P0 gaps.

Build: 20261005-m3-p0-prescale-hardening-v1
"""

from __future__ import annotations

BUILD = "20261005-m3-p0-prescale-hardening-v1"

CK = "m3_p0_prescale_hardening_v1_checkpoint.json"
JOB = "m3_p0_prescale_hardening_v1_job.json"
REPORT = "m3_p0_prescale_hardening_v1_last_report.json"
GAP_REGISTER = "PRE_SCALE_GAP_REGISTER_V1.json"
CHANNEL_PACKETS = "m3_owner_channel_test_packets_v1.json"
OUTREACH_QUEUE = "m3_owner_channel_outreach_queue_v1.json"
QUOTE_REQUESTS = "m3_owner_channel_quote_request_texts_v1.json"
PARTIAL_BASKET = "m3_partial_quote_basket_state_v1.json"
AUTO_WIRE_AUDIT = "m3_process_real_supplier_quote_audit_v1.json"
REGRESSION = "m3_p0_prescale_hardening_regression_v1.json"
CONSERVATION = "m3_p0_prescale_conservation_v1.json"
GOLDEN = "m3_golden_path_corpus_v1.json"
NEXT_ACTION_STORE = "m3_canonical_next_action_v1.json"

PRIOR_MLR_CK = "m3_material_line_identity_price_recovery_v1_checkpoint.json"
PRIOR_DC_PACKETS = "m3_deep_completion_quote_packets_v1.json"
PRIOR_REV = "m3_revenue_evidence_v1_store.json"

GO_METRO_OID = "opengov:go-metro:298984"
DEKALB_OID = "opengov:dekalbcountyga:286698"
DANIA_OID = "opengov:daniabeachfl:284328"
BRIDGEPORT_OID = "opengov:bridgeportct:299806"
COLLIER_OID = "opengov:collier-county-fl:295143"

# Scope classes (P0-2)
PRODUCT = "PRODUCT"
PRODUCT_WITH_INCIDENTAL_DELIVERY = "PRODUCT_WITH_INCIDENTAL_DELIVERY"
INSTALLATION = "INSTALLATION"
LABOR = "LABOR"
SERVICE = "SERVICE"
CONSTRUCTION = "CONSTRUCTION"
MIXED_SCOPE = "MIXED_SCOPE"
UNKNOWN_SCOPE = "UNKNOWN_SCOPE"

PRODUCT_SOURCING_OK = {PRODUCT, PRODUCT_WITH_INCIDENTAL_DELIVERY}
NON_PRODUCT_SCOPE = {INSTALLATION, LABOR, SERVICE, CONSTRUCTION}

# Identity (P0-4)
A_EXACT_MPN = "A_EXACT_MPN"
B_EXACT_MODEL = "B_EXACT_MODEL"
C_NSN_TO_EXACT = "C_NSN_TO_EXACT_COMMERCIAL"
D_PERMITTED_EQUAL = "D_PERMITTED_EQUAL_WITH_SALIENT_SPECS"
E_STRONG_GENERIC = "E_STRONG_GENERIC_SPEC"
F_FAMILY_ONLY = "F_COMMERCIAL_FAMILY_ONLY"
G_AMBIGUOUS = "G_IDENTITY_AMBIGUOUS"

IDENTITY_PACKET_OK = {A_EXACT_MPN, B_EXACT_MODEL, C_NSN_TO_EXACT, D_PERMITTED_EQUAL, E_STRONG_GENERIC}
IDENTITY_PACKET_BLOCK = {F_FAMILY_ONLY, G_AMBIGUOUS}

# Revenue hierarchy (P0-5)
CURRENT_LINE_VALUE = "CURRENT_LINE_VALUE"
CURRENT_BASKET_VALUE = "CURRENT_BASKET_VALUE"
CURRENT_PRODUCT_SCOPE_VALUE = "CURRENT_PRODUCT_SCOPE_VALUE"
CURRENT_CONTRACT_VALUE = "CURRENT_CONTRACT_VALUE"
PROJECT_BUDGET = "PROJECT_BUDGET"
PROGRAM_FUNDING = "PROGRAM_FUNDING"
GRANT_TOTAL = "GRANT_TOTAL"
CEILING = "CEILING"
ESTIMATE = "ESTIMATE"
HISTORICAL_EXACT = "HISTORICAL_EXACT"
HISTORICAL_COMPARABLE = "HISTORICAL_COMPARABLE"
BUYER_CATEGORY_REFERENCE = "BUYER_CATEGORY_REFERENCE"
NON_REVENUE_AMOUNT = "NON_REVENUE_AMOUNT"

ECONOMIC_REVENUE_DIRECT = {
    CURRENT_LINE_VALUE,
    CURRENT_BASKET_VALUE,
    CURRENT_PRODUCT_SCOPE_VALUE,
}

# Line quote states (P0-7)
UNQUOTED = "UNQUOTED"
QUOTE_REQUESTED = "QUOTE_REQUESTED"
QUOTE_RECEIVED_VALID = "QUOTE_RECEIVED_VALID"
QUOTE_RECEIVED_PARTIAL = "QUOTE_RECEIVED_PARTIAL"
QUOTE_REJECTED = "QUOTE_REJECTED"
QUOTE_EXPIRED = "QUOTE_EXPIRED"
PUBLIC_PRICE_VALID = "PUBLIC_PRICE_VALID"

BASKET_READY = "BASKET_READY"
BASKET_PARTIAL = "BASKET_PARTIAL"
ECONOMICS_NOT_READY = "ECONOMICS_NOT_READY"
ECONOMICS_READY = "ECONOMICS_READY"

# Quote origins
TEST_FIXTURE_ONLY = "TEST_FIXTURE_ONLY"
REAL_SUPPLIER_QUOTE = "REAL_SUPPLIER_QUOTE"
REAL_QUOTE_TEST_MODE = "REAL_QUOTE_TEST_MODE"  # segregated test path
PRICE_ORIGIN_SUPPLIER_QUOTE = "SUPPLIER_QUOTE"

# Packet / channel
READY_FOR_OWNER_QUOTE_OUTREACH = "READY_FOR_OWNER_QUOTE_OUTREACH"
OWNER_CHANNEL_TEST_READY = "OWNER_CHANNEL_TEST_READY"
PACKET_FAIL = "PACKET_FAIL"
PACKET_PASS = "PACKET_PASS"
NO_PROVENANCE = "NO_PROVENANCE"
NOT_QUOTE_READY = "NOT_QUOTE_READY"

# Canonical next actions
FIX_SOURCE_PROVENANCE = "FIX_SOURCE_PROVENANCE"
RESOLVE_IDENTITY = "RESOLVE_IDENTITY"
RESOLVE_SCOPE = "RESOLVE_SCOPE"
RESOLVE_REVENUE = "RESOLVE_REVENUE"
PREPARE_QUOTE_PACKET = "PREPARE_QUOTE_PACKET"
WAITING_FOR_SUPPLIER_QUOTE = "WAITING_FOR_SUPPLIER_QUOTE"
REVIEW_RECEIVED_QUOTE = "REVIEW_RECEIVED_QUOTE"
REVIEW_FINANCING = "REVIEW_FINANCING"
LENDER_READY = "LENDER_READY"
REJECT = "REJECT"
READY_FOR_ECONOMICS = "READY_FOR_ECONOMICS"

CANONICAL_STAGES = [
    "OPPORTUNITY",
    "PACKAGE",
    "ELIGIBILITY",
    "PRODUCTS",
    "REVENUE",
    "ACQUISITION",
    "QUOTES",
    "BASKET",
    "FREIGHT",
    "FINANCING",
    "ECONOMICS",
    "EXECUTION",
    "LENDER READY",
    "BID READY",
]

FREIGHT_RESERVE_PCT = 0.10
FINANCING_RESERVE_PCT = 0.03
