"""Euna/Bonfire authentication status constants."""

from __future__ import annotations

NOT_CONNECTED = "NOT_CONNECTED"
CONNECTED = "CONNECTED"
SESSION_REUSED = "SESSION_REUSED"
LOGIN_REQUIRED = "LOGIN_REQUIRED"
LOGIN_SUCCESS = "LOGIN_SUCCESS"
AUTH_CHALLENGE = "AUTH_CHALLENGE"
AUTH_FAILED = "AUTH_FAILED"
EXPIRED = "EXPIRED"
DISABLED = "DISABLED"
PAID_OPTIONAL = "PAID_OPTIONAL"
OPTIONAL_TARGETED_SOURCE = "OPTIONAL_TARGETED_SOURCE"
PRIMARY_NATIONAL_SOURCE = "PRIMARY_NATIONAL_SOURCE"

# Granular auth failure / challenge reasons (never collapse to one vague state)
BAD_CREDENTIALS = "BAD_CREDENTIALS"
USERNAME_NOT_FOUND = "USERNAME_NOT_FOUND"
PASSWORD_REJECTED = "PASSWORD_REJECTED"
SSO_REQUIRED = "SSO_REQUIRED"
EMAIL_VERIFICATION_REQUIRED = "EMAIL_VERIFICATION_REQUIRED"
MFA_REQUIRED = "MFA_REQUIRED"
CAPTCHA = "CAPTCHA"
ACCOUNT_NOT_APPROVED = "ACCOUNT_NOT_APPROVED"
ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
ACCOUNT_PENDING_APPROVAL = "ACCOUNT_PENDING_APPROVAL"
ACCOUNT_EMAIL_NOT_VERIFIED = "ACCOUNT_EMAIL_NOT_VERIFIED"
ACCOUNT_PROFILE_INCOMPLETE = "ACCOUNT_PROFILE_INCOMPLETE"
ACCOUNT_ACTIVE = "ACCOUNT_ACTIVE"
SUPPLIER_NETWORK_NOT_ENABLED = "SUPPLIER_NETWORK_NOT_ENABLED"
CLOUDFLARE_CHALLENGE = "CLOUDFLARE_CHALLENGE"
WRONG_LOGIN_HOST = "WRONG_LOGIN_HOST"
WRONG_FORM_FLOW = "WRONG_FORM_FLOW"
SESSION_CONFLICT = "SESSION_CONFLICT"
NETWORK_TIMEOUT = "NETWORK_TIMEOUT"
AUTH_PROVIDER_ERROR = "AUTH_PROVIDER_ERROR"
UNKNOWN_AUTH_FAILURE = "UNKNOWN_AUTH_FAILURE"

WORKING = "WORKING"
WORKING_PUBLIC = "WORKING_PUBLIC"
WORKING_AUTH = "WORKING_AUTH"
PARTIAL = "PARTIAL"
ANTI_BOT = "ANTI_BOT"
NO_OPEN_BIDS = "NO_OPEN_BIDS"
INVALID_PORTAL = "INVALID_PORTAL"
SOURCE_ERROR = "SOURCE_ERROR"
BROKEN_PARSER = "BROKEN_PARSER"

AUTHENTICATED_STATUSES = frozenset({CONNECTED, SESSION_REUSED, LOGIN_SUCCESS})
SUCCESS_STATUSES = frozenset({WORKING, WORKING_PUBLIC, WORKING_AUTH, PARTIAL})

GRANULAR_FAILURES = frozenset(
    {
        BAD_CREDENTIALS,
        USERNAME_NOT_FOUND,
        PASSWORD_REJECTED,
        SSO_REQUIRED,
        EMAIL_VERIFICATION_REQUIRED,
        MFA_REQUIRED,
        CAPTCHA,
        ACCOUNT_NOT_APPROVED,
        ACCOUNT_INACTIVE,
        ACCOUNT_PENDING_APPROVAL,
        ACCOUNT_EMAIL_NOT_VERIFIED,
        ACCOUNT_PROFILE_INCOMPLETE,
        WRONG_LOGIN_HOST,
        WRONG_FORM_FLOW,
        SESSION_CONFLICT,
        NETWORK_TIMEOUT,
        AUTH_PROVIDER_ERROR,
        UNKNOWN_AUTH_FAILURE,
        AUTH_CHALLENGE,
        AUTH_FAILED,
    }
)
