"""R1 Solicitation Response Compiler — vocabulary and lifecycle states.

Build: 20260929-m3-r1-solicitation-response-compiler-foundation

Permanent invariants:
- Never silently guess material requirements → UNKNOWN / SUBMISSION_BLOCKED
- Fail closed
- Discovery source ≠ authoritative source ≠ submission system
- Internal evidence ≠ government submission content
"""

from __future__ import annotations

BUILD = "20260929-m3-r1-solicitation-response-compiler-foundation"

# ---------------------------------------------------------------------------
# Response project lifecycle
# ---------------------------------------------------------------------------
NOT_STARTED = "NOT_STARTED"
INTAKE_IN_PROGRESS = "INTAKE_IN_PROGRESS"
DOCUMENTS_INCOMPLETE = "DOCUMENTS_INCOMPLETE"
DOCUMENTS_READY = "DOCUMENTS_READY"
REQUIREMENTS_COMPILING = "REQUIREMENTS_COMPILING"
CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
COMPLIANCE_REVIEW = "COMPLIANCE_REVIEW"
BLOCKED = "BLOCKED"
READY_FOR_RESPONSE_BUILD = "READY_FOR_RESPONSE_BUILD"
RESPONSE_BUILD_IN_PROGRESS = "RESPONSE_BUILD_IN_PROGRESS"
READY_FOR_PREFLIGHT = "READY_FOR_PREFLIGHT"
READY_FOR_OWNER_REVIEW = "READY_FOR_OWNER_REVIEW"
READY_FOR_SUBMISSION = "READY_FOR_SUBMISSION"
SUBMITTED = "SUBMITTED"
SUPERSEDED = "SUPERSEDED"
CANCELLED = "CANCELLED"
PACKAGE_STALE_DUE_TO_AMENDMENT = "PACKAGE_STALE_DUE_TO_AMENDMENT"

RESPONSE_STATUSES = (
    NOT_STARTED, INTAKE_IN_PROGRESS, DOCUMENTS_INCOMPLETE, DOCUMENTS_READY,
    REQUIREMENTS_COMPILING, CLARIFICATION_REQUIRED, COMPLIANCE_REVIEW, BLOCKED,
    READY_FOR_RESPONSE_BUILD, RESPONSE_BUILD_IN_PROGRESS, READY_FOR_PREFLIGHT,
    READY_FOR_OWNER_REVIEW, READY_FOR_SUBMISSION, SUBMITTED, SUPERSEDED, CANCELLED,
    PACKAGE_STALE_DUE_TO_AMENDMENT,
)

# ---------------------------------------------------------------------------
# Document types
# ---------------------------------------------------------------------------
BASE_SOLICITATION = "BASE_SOLICITATION"
AMENDMENT = "AMENDMENT"
ADDENDUM = "ADDENDUM"
SPECIFICATION = "SPECIFICATION"
STATEMENT_OF_WORK = "STATEMENT_OF_WORK"
PRODUCT_REQUIREMENT = "PRODUCT_REQUIREMENT"
PRICING_SHEET = "PRICING_SHEET"
COST_SHEET = "COST_SHEET"
ATTACHMENT = "ATTACHMENT"
Q_AND_A = "Q_AND_A"
PORTAL_INSTRUCTIONS = "PORTAL_INSTRUCTIONS"
FORM = "FORM"
CERTIFICATION = "CERTIFICATION"
DRAWING = "DRAWING"
DELIVERY_SCHEDULE = "DELIVERY_SCHEDULE"
TERMS = "TERMS"
MASTER_SOLICITATION = "MASTER_SOLICITATION"
BUYER_TEMPLATE = "BUYER_TEMPLATE"
OTHER = "OTHER"

DOCUMENT_TYPES = (
    BASE_SOLICITATION, AMENDMENT, ADDENDUM, SPECIFICATION, STATEMENT_OF_WORK,
    PRODUCT_REQUIREMENT, PRICING_SHEET, COST_SHEET, ATTACHMENT, Q_AND_A,
    PORTAL_INSTRUCTIONS, FORM, CERTIFICATION, DRAWING, DELIVERY_SCHEDULE,
    TERMS, MASTER_SOLICITATION, BUYER_TEMPLATE, OTHER,
)

CONTROLLING = "CONTROLLING"
SUPERSEDED_DOC = "SUPERSEDED"
REFERENCE = "REFERENCE"
UNKNOWN_AUTHORITY = "UNKNOWN_AUTHORITY"

# ---------------------------------------------------------------------------
# Response types
# ---------------------------------------------------------------------------
FEDERAL_SIMPLIFIED_RFQ = "FEDERAL_SIMPLIFIED_RFQ"
FEDERAL_COMMERCIAL_RFQ = "FEDERAL_COMMERCIAL_RFQ"
FEDERAL_IFB = "FEDERAL_IFB"
FEDERAL_RFP = "FEDERAL_RFP"
FEDERAL_DIBBS_WEB_QUOTE = "FEDERAL_DIBBS_WEB_QUOTE"
FEDERAL_DLA_FORMAL_OFFER = "FEDERAL_DLA_FORMAL_OFFER"
FEDERAL_PIEE_OFFER = "FEDERAL_PIEE_OFFER"
STATE_LOCAL_RFQ = "STATE_LOCAL_RFQ"
STATE_LOCAL_IFB = "STATE_LOCAL_IFB"
STATE_LOCAL_RFP = "STATE_LOCAL_RFP"
STATE_LOCAL_PORTAL_QUOTE = "STATE_LOCAL_PORTAL_QUOTE"
EMAIL_QUOTE = "EMAIL_QUOTE"
PHYSICAL_BID = "PHYSICAL_BID"
UNKNOWN_RESPONSE_TYPE = "UNKNOWN_RESPONSE_TYPE"

# ---------------------------------------------------------------------------
# Evaluation methods
# ---------------------------------------------------------------------------
LOW_PRICE = "LOW_PRICE"
LOWEST_RESPONSIVE_RESPONSIBLE = "LOWEST_RESPONSIVE_RESPONSIBLE"
LPTA = "LPTA"
BEST_VALUE_TRADEOFF = "BEST_VALUE_TRADEOFF"
POINT_SCORED = "POINT_SCORED"
PRICE_PLUS_TECHNICAL = "PRICE_PLUS_TECHNICAL"
LINE_ITEM_AWARD = "LINE_ITEM_AWARD"
LOT_AWARD = "LOT_AWARD"
AGGREGATE_AWARD = "AGGREGATE_AWARD"
MULTIPLE_AWARD = "MULTIPLE_AWARD"
UNKNOWN_EVALUATION = "UNKNOWN"

# ---------------------------------------------------------------------------
# Materiality / timing / curability
# ---------------------------------------------------------------------------
MATERIAL = "MATERIAL"
POTENTIALLY_MATERIAL = "POTENTIALLY_MATERIAL"
NONMATERIAL = "NONMATERIAL"
UNKNOWN_MATERIALITY = "UNKNOWN"

PRE_QUESTION_DEADLINE = "PRE_QUESTION_DEADLINE"
AT_SUBMISSION = "AT_SUBMISSION"
PRE_AWARD = "PRE_AWARD"
POST_AWARD = "POST_AWARD"
AT_DELIVERY = "AT_DELIVERY"
ONGOING_CONTRACT = "ONGOING_CONTRACT"
UNKNOWN_TIMING = "UNKNOWN_TIMING"

NOT_CURABLE_AFTER_SUBMISSION = "NOT_CURABLE_AFTER_SUBMISSION"
NOT_SAFE_TO_ASSUME_CURABLE = "NOT_SAFE_TO_ASSUME_CURABLE"
MAY_BE_CURABLE = "MAY_BE_CURABLE"
PRE_AWARD_RESOLUTION_ALLOWED = "PRE_AWARD_RESOLUTION_ALLOWED"
POST_AWARD_REQUIREMENT = "POST_AWARD_REQUIREMENT"
UNKNOWN_CURABILITY = "UNKNOWN"

# ---------------------------------------------------------------------------
# Answer / compliance
# ---------------------------------------------------------------------------
UNANSWERED = "UNANSWERED"
ANSWERED_VERIFIED = "ANSWERED_VERIFIED"
ANSWERED_OWNER_CONFIRMED = "ANSWERED_OWNER_CONFIRMED"
ANSWERED_UNVERIFIED = "ANSWERED_UNVERIFIED"
ANSWER_UNKNOWN = "UNKNOWN"
NOT_APPLICABLE = "NOT_APPLICABLE"
CONFLICT = "CONFLICT"
REQ_SUPERSEDED = "SUPERSEDED"

PASS = "PASS"
FAIL = "FAIL"
UNKNOWN = "UNKNOWN"
REVIEW_REQUIRED = "REVIEW_REQUIRED"
CLARIFICATION_REQUIRED_STATUS = "CLARIFICATION_REQUIRED"

HIGH = "HIGH"
MEDIUM = "MEDIUM"
LOW = "LOW"

# ---------------------------------------------------------------------------
# Product modes / condition
# ---------------------------------------------------------------------------
BRAND_NAME_ONLY = "BRAND_NAME_ONLY"
EXACT_PART_NUMBER = "EXACT_PART_NUMBER"
BRAND_NAME_OR_EQUAL = "BRAND_NAME_OR_EQUAL"
PERFORMANCE_SPEC = "PERFORMANCE_SPEC"
ALTERNATES_ALLOWED = "ALTERNATES_ALLOWED"
UNKNOWN_PRODUCT_MODE = "UNKNOWN_PRODUCT_MODE"

NEW_OEM = "NEW_OEM"
NEW = "NEW"
REMANUFACTURED = "REMANUFACTURED"
RECONDITIONED = "RECONDITIONED"
SURPLUS = "SURPLUS"
USED = "USED"
UNKNOWN_CONDITION = "UNKNOWN"

# ---------------------------------------------------------------------------
# Evidence namespaces (clean-room firewall)
# ---------------------------------------------------------------------------
NS_INTERNAL_EVIDENCE = "INTERNAL_EVIDENCE"
NS_VERIFIED_RESPONSE_FACTS = "VERIFIED_RESPONSE_FACTS"
NS_GOVERNMENT_SUBMISSION = "GOVERNMENT_SUBMISSION_CONTENT"

# ---------------------------------------------------------------------------
# Deliverable types
# ---------------------------------------------------------------------------
PORTAL_FIELD = "PORTAL_FIELD"
PORTAL_QUESTION = "PORTAL_QUESTION"
CLIN_PRICE = "CLIN_PRICE"
DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD"
BUYER_TEMPLATE_DELIVERABLE = "BUYER_TEMPLATE"
FORM_DELIVERABLE = "FORM"
SIGNATURE = "SIGNATURE"
EMAIL_BODY = "EMAIL_BODY"
EMAIL_ATTACHMENT = "EMAIL_ATTACHMENT"
PHYSICAL_SAMPLE = "PHYSICAL_SAMPLE"
BID_GUARANTEE = "BID_GUARANTEE"
PHYSICAL_PACKAGE = "PHYSICAL_PACKAGE"
AMENDMENT_ACKNOWLEDGMENT = "AMENDMENT_ACKNOWLEDGMENT"

# ---------------------------------------------------------------------------
# Requirement categories (R1 canonical set)
# ---------------------------------------------------------------------------
REQUIREMENT_CATEGORIES = (
    "PRICE", "CLIN", "QUANTITY", "UOM", "PRODUCT_IDENTITY", "EXACT_BRAND",
    "BRAND_OR_EQUAL", "TECHNICAL_SPECIFICATION", "SALIENT_CHARACTERISTIC",
    "CONDITION", "COUNTRY_OF_ORIGIN", "BUY_AMERICAN", "TRADE_AGREEMENTS",
    "NMR", "SECTION_889", "SUPPLY_CHAIN", "AUTHORIZATION", "TRACEABILITY",
    "WARRANTY", "DELIVERY", "LEAD_TIME", "FOB", "FREIGHT", "PACKAGING",
    "MARKING", "INSPECTION", "ACCEPTANCE", "QUALITY", "CERTIFICATION",
    "REPRESENTATION", "SIGNATURE", "AMENDMENT_ACK", "FORM", "ATTACHMENT",
    "TECHNICAL_LITERATURE", "PAST_PERFORMANCE", "EXPERIENCE", "REGISTRATION",
    "ELIGIBILITY", "QUESTIONNAIRE", "PORTAL_FIELD", "FILE_FORMAT", "FILE_NAME",
    "PAGE_LIMIT", "FONT", "MARGIN", "SUBMISSION_METHOD", "SUBMISSION_DEADLINE",
    "QUESTION_DEADLINE", "PHYSICAL_SAMPLE", "BID_GUARANTEE", "DPAS", "OTHER",
)

# Categories that default toward MATERIAL when mandatory
DEFAULT_MATERIAL_CATEGORIES = frozenset({
    "PRICE", "CLIN", "QUANTITY", "EXACT_BRAND", "BRAND_OR_EQUAL",
    "TECHNICAL_SPECIFICATION", "SALIENT_CHARACTERISTIC", "COUNTRY_OF_ORIGIN",
    "BUY_AMERICAN", "TRADE_AGREEMENTS", "NMR", "SECTION_889", "AUTHORIZATION",
    "DELIVERY", "SIGNATURE", "AMENDMENT_ACK", "FORM", "SUBMISSION_METHOD",
    "SUBMISSION_DEADLINE", "CERTIFICATION", "ELIGIBILITY", "BID_GUARANTEE",
})
