"""R2 vocabulary — CLIN / pricing / technical compliance. No READY_TO_SUBMIT."""

from __future__ import annotations

BUILD = "20260929-m3-r2-clin-pricing-product-compliance"
DEFAULT_FINANCING_RATE = "0.05"  # Decimal string; configurable

# Evidence / numeric states
VERIFIED = "VERIFIED"
SUPPORTED_ESTIMATE = "SUPPORTED_ESTIMATE"
SCENARIO = "SCENARIO"
OWNER_ENTERED = "OWNER_ENTERED"
UNKNOWN = "UNKNOWN"
ESTIMATED = "ESTIMATED"

# Quantity states
QTY_EXACT = "EXACT"
QTY_ESTIMATED = "ESTIMATED"
QTY_MINIMUM = "MINIMUM"
QTY_MAXIMUM = "MAXIMUM"
QTY_RANGE = "RANGE"
QTY_OPTIONAL = "OPTIONAL"
QTY_UNKNOWN = "UNKNOWN"

# Award basis
LINE_ITEM = "LINE_ITEM"
LOT = "LOT"
GROUP = "GROUP"
AGGREGATE = "AGGREGATE"
ALL_OR_NONE = "ALL_OR_NONE"
MULTIPLE_AWARD = "MULTIPLE_AWARD"
UNKNOWN_AWARD = "UNKNOWN"

# Technical compliance
PASS_VERIFIED = "PASS_VERIFIED"
TECHNICAL_FAIL = "FAIL"
TECHNICAL_UNKNOWN = "UNKNOWN"
REVIEW_REQUIRED = "REVIEW_REQUIRED"
OWNER_CONFIRMATION_REQUIRED = "OWNER_CONFIRMATION_REQUIRED"
NOT_APPLICABLE = "NOT_APPLICABLE"

# Quote types
WRITTEN_QUOTE = "WRITTEN_QUOTE"
VERBAL_QUOTE = "VERBAL_QUOTE"
WEB_PRICE = "WEB_PRICE"
CATALOG_PRICE = "CATALOG_PRICE"
DISTRIBUTOR_PORTAL_PRICE = "DISTRIBUTOR_PORTAL_PRICE"
QUOTE_ESTIMATE = "ESTIMATE"
HISTORICAL_INTERNAL = "HISTORICAL_INTERNAL"

# Freight
FREIGHT_INCLUDED_VERIFIED = "INCLUDED_VERIFIED"
FREIGHT_QUOTED_SEPARATELY = "QUOTED_SEPARATELY"
FREIGHT_ESTIMATED = "ESTIMATED"
FREIGHT_OWNER_ENTERED = "OWNER_ENTERED"
FREIGHT_UNKNOWN = "UNKNOWN"
FREIGHT_NA = "NOT_APPLICABLE"

# Profit evidence
VERIFIED_PROFIT = "VERIFIED_PROFIT"
PROVISIONAL_PROFIT = "PROVISIONAL_PROFIT"
SCENARIO_PROFIT = "SCENARIO_PROFIT"
UNKNOWN_PROFIT = "UNKNOWN_PROFIT"

# R2 readiness (never READY_TO_SUBMIT)
CLIN_STRUCTURE_INCOMPLETE = "CLIN_STRUCTURE_INCOMPLETE"
PRODUCT_SELECTION_REQUIRED = "PRODUCT_SELECTION_REQUIRED"
SUPPLIER_QUOTE_REQUIRED = "SUPPLIER_QUOTE_REQUIRED"
TECHNICAL_REVIEW_REQUIRED = "TECHNICAL_REVIEW_REQUIRED"
TECHNICAL_FAIL_STATUS = "TECHNICAL_FAIL"
ECONOMICS_INCOMPLETE = "ECONOMICS_INCOMPLETE"
FINANCING_REVIEW_REQUIRED = "FINANCING_REVIEW_REQUIRED"
READY_FOR_RESPONSE_BUILD = "READY_FOR_RESPONSE_BUILD"
UOM_CONVERSION_BLOCKED = "UOM_CONVERSION_BLOCKED"
ECONOMICS_UNVERIFIED = "ECONOMICS_UNVERIFIED"
RESPONSE_BLOCKED = "RESPONSE_BLOCKED"

# Bid/no-bid recommendations
TECHNICALLY_READY_ECONOMICS_GOOD = "TECHNICALLY_READY_ECONOMICS_GOOD"
TECHNICALLY_READY_ECONOMICS_THIN = "TECHNICALLY_READY_ECONOMICS_THIN"
QUOTE_REQUIRED = "QUOTE_REQUIRED"
TECHNICAL_REVIEW = "TECHNICAL_REVIEW"
ECONOMIC_FAIL = "ECONOMIC_FAIL"
EXECUTION_FAIL = "EXECUTION_FAIL"
DO_NOT_BID = "DO_NOT_BID"

# Condition
NEW_OEM = "NEW_OEM"
NEW = "NEW"
REMANUFACTURED = "REMANUFACTURED"
RECONDITIONED = "RECONDITIONED"
SURPLUS = "SURPLUS"
USED = "USED"
UNKNOWN_CONDITION = "UNKNOWN"

# Product modes (align with R1)
BRAND_NAME_ONLY = "BRAND_NAME_ONLY"
EXACT_PART_NUMBER = "EXACT_PART_NUMBER"
BRAND_NAME_OR_EQUAL = "BRAND_NAME_OR_EQUAL"
PERFORMANCE_SPEC = "PERFORMANCE_SPEC"
ALTERNATES_ALLOWED = "ALTERNATES_ALLOWED"
UNKNOWN_PRODUCT_MODE = "UNKNOWN_PRODUCT_MODE"
