"""R3 vocabulary — company compliance / NMR / trade / attestations. Never READY_TO_SUBMIT."""

from __future__ import annotations

BUILD = "20260929-m3-r3-company-compliance-reps-certs-trade"

# Applicability
APPLIES = "APPLIES"
DOES_NOT_APPLY = "DOES_NOT_APPLY"
POSSIBLY_APPLIES = "POSSIBLY_APPLIES"
UNKNOWN_APPLICABILITY = "UNKNOWN"

# Answer states
VERIFIED_YES = "VERIFIED_YES"
VERIFIED_NO = "VERIFIED_NO"
OWNER_CONFIRMED_YES = "OWNER_CONFIRMED_YES"
OWNER_CONFIRMED_NO = "OWNER_CONFIRMED_NO"
REVIEW_REQUIRED = "REVIEW_REQUIRED"
UNKNOWN = "UNKNOWN"
NOT_APPLICABLE = "NOT_APPLICABLE"

# Matrix status
PASS_VERIFIED = "PASS_VERIFIED"
FAIL = "FAIL"
OWNER_CONFIRMATION_REQUIRED = "OWNER_CONFIRMATION_REQUIRED"
COMPLIANCE_BLOCKED = "COMPLIANCE_BLOCKED"

# NMR
NMR_NOT_APPLICABLE = "NMR_NOT_APPLICABLE"
NMR_APPLIES_COMPLIANT = "NMR_APPLIES_COMPLIANT"
NMR_APPLIES_WAIVER = "NMR_APPLIES_WAIVER"
NMR_APPLIES_NONCOMPLIANT = "NMR_APPLIES_NONCOMPLIANT"
NMR_REVIEW_REQUIRED = "NMR_REVIEW_REQUIRED"
NMR_UNKNOWN = "NMR_UNKNOWN"

# Trade regimes
BUY_AMERICAN = "BUY_AMERICAN"
TRADE_AGREEMENTS = "TRADE_AGREEMENTS"
FTA = "FTA"
TRADE_NONE = "NONE"
TRADE_OTHER = "OTHER"
TRADE_UNKNOWN = "UNKNOWN"

# Readiness
COMPANY_PROFILE_INCOMPLETE = "COMPANY_PROFILE_INCOMPLETE"
ELIGIBILITY_BLOCKED = "ELIGIBILITY_BLOCKED"
OWNER_ATTESTATION_REQUIRED = "OWNER_ATTESTATION_REQUIRED"
TRADE_COMPLIANCE_REVIEW = "TRADE_COMPLIANCE_REVIEW"
NMR_REVIEW = "NMR_REVIEW"
REGISTRATION_REQUIRED = "REGISTRATION_REQUIRED"
COMPLIANCE_READY = "COMPLIANCE_READY"
READY_FOR_RESPONSE_BUILD = "READY_FOR_RESPONSE_BUILD"
COMPLIANCE_STALE = "COMPLIANCE_STALE"
COMPANY_DATA_CONFLICT = "COMPANY_DATA_CONFLICT"
DO_NOT_BID = "DO_NOT_BID"

# CAGE / SAM
CAGE_ACTIVE = "ACTIVE"
CAGE_PENDING = "PENDING"
CAGE_UNKNOWN = "UNKNOWN"
SAM_ACTIVE = "ACTIVE"
SAM_UNKNOWN = "UNKNOWN"
SAM_REFRESH_REQUIRED = "SAM_REFRESH_REQUIRED"

# Cyber
CYBER_NOT_APPLICABLE = "NOT_APPLICABLE"
CYBER_REQUIRED_VERIFIED = "REQUIRED_VERIFIED"
CYBER_REQUIRED_NOT_MET = "REQUIRED_NOT_MET"
CYBER_REQUIRED_UNKNOWN = "REQUIRED_UNKNOWN"
CYBER_REVIEW_REQUIRED = "REVIEW_REQUIRED"

# Registration operator modes
REGISTER_BEFORE_BID = "REGISTER_BEFORE_BID"
DIBBS_CAGE_REQUIRED = "DIBBS_CAGE_REQUIRED"

# Size
SMALL_VERIFIED = "SMALL_VERIFIED"
OTHER_THAN_SMALL = "OTHER_THAN_SMALL"
SIZE_UNKNOWN = "UNKNOWN"
SIZE_REVIEW = "REVIEW_REQUIRED"
