"""R4 vocabulary — buyer forms / spreadsheets / response generation. Never READY_TO_SUBMIT."""

from __future__ import annotations

BUILD = "20260929-m3-r4-buyer-forms-response-generation"

# Package status
NOT_STARTED = "NOT_STARTED"
GENERATION_BLOCKED = "GENERATION_BLOCKED"
DRAFT_INCOMPLETE = "DRAFT_INCOMPLETE"
DRAFT_COMPLETE = "DRAFT_COMPLETE"
OWNER_INPUT_REQUIRED = "OWNER_INPUT_REQUIRED"
OWNER_SIGNATURE_REQUIRED = "OWNER_SIGNATURE_REQUIRED"
READY_FOR_R5_PREFLIGHT = "READY_FOR_R5_PREFLIGHT"
SUPERSEDED = "SUPERSEDED"
STALE_DUE_TO_AMENDMENT = "STALE_DUE_TO_AMENDMENT"
STALE_DUE_TO_PRODUCT_CHANGE = "STALE_DUE_TO_PRODUCT_CHANGE"
STALE_DUE_TO_PRICE_CHANGE = "STALE_DUE_TO_PRICE_CHANGE"
STALE_DUE_TO_COMPANY_PROFILE_CHANGE = "STALE_DUE_TO_COMPANY_PROFILE_CHANGE"

# Field status
READY = "READY"
POPULATED = "POPULATED"
UNKNOWN = "UNKNOWN"
OWNER_INPUT_REQUIRED_FIELD = "OWNER_INPUT_REQUIRED"
OWNER_ATTESTATION_REQUIRED = "OWNER_ATTESTATION_REQUIRED"
OWNER_SIGNATURE_REQUIRED_FIELD = "OWNER_SIGNATURE_REQUIRED"
MANUAL_ENTRY_REQUIRED = "MANUAL_ENTRY_REQUIRED"
NOT_APPLICABLE = "NOT_APPLICABLE"
BLOCKED = "BLOCKED"

# Readiness
RESPONSE_INPUT_INCOMPLETE = "RESPONSE_INPUT_INCOMPLETE"
FORM_MAPPING_REQUIRED = "FORM_MAPPING_REQUIRED"
DOCUMENT_REVIEW_REQUIRED = "DOCUMENT_REVIEW_REQUIRED"
RESPONSE_CONFLICT = "RESPONSE_CONFLICT"
OWNER_PRICE_APPROVAL_REQUIRED = "OWNER_PRICE_APPROVAL_REQUIRED"

# Deliverable types
BUYER_PDF_FORM = "BUYER_PDF_FORM"
BUYER_DOCX_FORM = "BUYER_DOCX_FORM"
BUYER_XLSX_TEMPLATE = "BUYER_XLSX_TEMPLATE"
BUYER_CSV_TEMPLATE = "BUYER_CSV_TEMPLATE"
GENERATED_QUOTE_LETTER = "GENERATED_QUOTE_LETTER"
GENERATED_TECHNICAL_RESPONSE = "GENERATED_TECHNICAL_RESPONSE"
GENERATED_COMPLIANCE_MATRIX = "GENERATED_COMPLIANCE_MATRIX"
GENERATED_PRODUCT_SCHEDULE = "GENERATED_PRODUCT_SCHEDULE"
GENERATED_PRICING_SCHEDULE = "GENERATED_PRICING_SCHEDULE"
GENERATED_CERTIFICATION = "GENERATED_CERTIFICATION"
GENERATED_COVER_LETTER = "GENERATED_COVER_LETTER"
ATTACHMENT_COPY = "ATTACHMENT_COPY"
OEM_DATASHEET = "OEM_DATASHEET"
AUTHORIZATION_LETTER = "AUTHORIZATION_LETTER"
OTHER_REQUIRED_ATTACHMENT = "OTHER_REQUIRED_ATTACHMENT"
PORTAL_RESPONSE_DATA = "PORTAL_RESPONSE_DATA"
EMAIL_RESPONSE_DATA = "EMAIL_RESPONSE_DATA"
PHYSICAL_PACKAGE_INSTRUCTION = "PHYSICAL_PACKAGE_INSTRUCTION"

# Attachment necessity
SUBMIT_REQUIRED = "SUBMIT_REQUIRED"
SUBMIT_RECOMMENDED = "SUBMIT_RECOMMENDED"
INTERNAL_ONLY = "INTERNAL_ONLY"
REFERENCE_ONLY = "REFERENCE_ONLY"

# File roles
ORIGINAL = "ORIGINAL"
WORKING_COPY = "WORKING_COPY"
GENERATED_RESPONSE_COPY = "GENERATED_RESPONSE_COPY"
REVIEWED_DRAFT = "REVIEWED_DRAFT"

DRAFT_LABEL = "DRAFT — NOT SUBMITTED"
MACRO_TEMPLATE_MANUAL = "MACRO_TEMPLATE_MANUAL_COMPLETION_REQUIRED"
FORMAT_CONFLICT = "FORMAT_CONFLICT_REVIEW_REQUIRED"
MANUAL_GENERATION_REQUIRED = "MANUAL_GENERATION_REQUIRED"
MANUAL_RESPONSE_OVERRIDE = "MANUAL_RESPONSE_OVERRIDE"
RESPONSE_DATA_CONFLICT = "RESPONSE_DATA_CONFLICT"
PAST_PERFORMANCE_INPUT_REQUIRED = "PAST_PERFORMANCE_INPUT_REQUIRED"
CAGE_REQUIRED_UNRESOLVED = "CAGE REQUIRED — UNRESOLVED"
