"""R5 vocabulary — preflight / approval / submission / receipts. Never auto-submit in tests."""

from __future__ import annotations

BUILD = "20260929-m3-r5-preflight-submission-ui-sync"

# Preflight check status
PASS = "PASS"
WARNING = "WARNING"
FAIL = "FAIL"
OWNER_ACTION_REQUIRED = "OWNER_ACTION_REQUIRED"
MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"

# Approval
APPROVAL_PENDING = "PENDING"
APPROVAL_APPROVED = "APPROVED"
APPROVAL_REJECTED = "REJECTED"
APPROVAL_CHANGES_REQUESTED = "CHANGES_REQUESTED"
APPROVAL_EXPIRED = "EXPIRED_DUE_TO_CHANGE"

# Signature
SIG_NOT_REQUIRED = "NOT_REQUIRED"
SIG_OWNER_REQUIRED = "OWNER_SIGNATURE_REQUIRED"
SIG_READY = "READY_FOR_SIGNATURE"
SIG_SIGNED = "SIGNED"
SIG_INVALID = "SIGNATURE_INVALID"
SIG_STALE = "STALE"

# Submission
SUB_NOT_STARTED = "NOT_STARTED"
SUB_IN_PROGRESS = "IN_PROGRESS"
SUB_WAITING_OWNER = "WAITING_OWNER_ACTION"
SUB_SUBMITTED_UNCONFIRMED = "SUBMITTED_UNCONFIRMED"
SUB_SUBMITTED_CONFIRMED = "SUBMITTED_CONFIRMED"
SUB_FAILED = "FAILED"
SUB_REJECTED = "REJECTED_BY_PORTAL"
SUB_RETRY = "RETRY_REQUIRED"
SUB_WITHDRAWN = "WITHDRAWN"
SUB_SUPERSEDED = "SUPERSEDED_BY_REVISION"
DRY_RUN_SUBMITTED_CONFIRMED = "DRY_RUN_SUBMITTED_CONFIRMED"

# Operator plain statuses
STATUS_DEADLINE_PASSED = "DEADLINE PASSED"
STATUS_DO_NOT_BID = "DO NOT BID"
STATUS_NEEDS_ACTION = "NEEDS ACTION"
STATUS_WAITING_OWNER = "WAITING ON OWNER"
STATUS_WAITING_EXTERNAL = "WAITING"
STATUS_READY_FOR_APPROVAL = "READY FOR OWNER APPROVAL"
STATUS_READY_TO_SUBMIT = "READY FOR GUIDED SUBMISSION"
STATUS_SUBMITTED = "SUBMITTED"
STATUS_AWAITING_RESULT = "AWAITING RESULT"
STATUS_BUILD_RESPONSE = "BUILD RESPONSE"

# Roles
ROLE_OPERATOR = "operator"
ROLE_OWNER = "owner"

# Adapter types
ADAPTER_PORTAL = "PORTAL"
ADAPTER_DIBBS = "DIBBS"
ADAPTER_PIEE = "PIEE"
ADAPTER_EMAIL = "EMAIL"
ADAPTER_PHYSICAL = "PHYSICAL"
ADAPTER_OTHER = "OTHER"
