"""Basket completion + canonical full-funnel reconciliation.

Build: 20261005-m3-basket-full-funnel-reconcile-v1
"""

from __future__ import annotations

BUILD = "20261005-m3-basket-full-funnel-reconcile-v1"

CK = "m3_basket_full_funnel_reconcile_v1_checkpoint.json"
JOB = "m3_basket_full_funnel_reconcile_v1_job.json"
REPORT = "m3_basket_full_funnel_reconcile_v1_last_report.json"
BOTH_SIDES_CORPUS = "m3_both_sides_basket_corpus_v1.json"
STAGE_CONTRACTS = "m3_canonical_stage_contracts_v1.json"
FUNNEL_AUDIT = "m3_canonical_funnel_audit_v1.json"
GOLDEN_PATH = "m3_golden_path_corpus_v1.json"
CONTROLLED_SAMPLE = "m3_controlled_scale_sample_v1.json"
CONSERVATION = "m3_basket_funnel_conservation_v1.json"
BYPASS_AUDIT = "m3_legacy_bypass_audit_v1.json"

PRIOR_ACQ_CK = "m3_acquisition_scale_v1_checkpoint.json"
PRIOR_REV = "m3_revenue_evidence_v1_store.json"
PRIOR_CONTROL_REPORT = "m3_live_seller_benchmark_reverify_v1_last_report.json"

TARGET_BOTH_SIDES = 16
CONTROLLED_SAMPLE_MIN = 250
CONTROLLED_SAMPLE_MAX = 500

# Line terminal states (Phase 3)
PRICED_EXECUTABLE = "PRICED_EXECUTABLE"
QUOTE_REQUIRED = "QUOTE_REQUIRED"
IDENTITY_AMBIGUOUS = "IDENTITY_AMBIGUOUS"
PUBLIC_PRICE_UNAVAILABLE = "PUBLIC_PRICE_UNAVAILABLE"
WRONG_OR_MISSING_PACK = "WRONG_OR_MISSING_PACK"
UOM_UNRESOLVED = "UOM_UNRESOLVED"
CONDITION_UNRESOLVED = "CONDITION_UNRESOLVED"
NO_COMPLIANT_SOURCE = "NO_COMPLIANT_SOURCE"
NOT_REQUIRED_FOR_BASKET = "NOT_REQUIRED_FOR_BASKET"
EXECUTION_BLOCKED = "EXECUTION_BLOCKED"

LINE_TERMINALS = {
    PRICED_EXECUTABLE,
    QUOTE_REQUIRED,
    IDENTITY_AMBIGUOUS,
    PUBLIC_PRICE_UNAVAILABLE,
    WRONG_OR_MISSING_PACK,
    UOM_UNRESOLVED,
    CONDITION_UNRESOLVED,
    NO_COMPLIANT_SOURCE,
    NOT_REQUIRED_FOR_BASKET,
    EXECUTION_BLOCKED,
}

# Basket ready classes
BASKET_READY_PUBLIC_PRICE = "BASKET_READY_PUBLIC_PRICE"
BASKET_READY_QUOTE_DEPENDENT = "BASKET_READY_QUOTE_DEPENDENT"
BASKET_BLOCKED = "BASKET_BLOCKED"

# Freight
PUBLIC_FREIGHT_CONFIRMED = "PUBLIC_FREIGHT_CONFIRMED"
FREIGHT_ESTIMATED_CONSERVATIVE = "FREIGHT_ESTIMATED_CONSERVATIVE"
FREIGHT_QUOTE_REQUIRED = "FREIGHT_QUOTE_REQUIRED"

# Financing
FINANCEABLE_PUBLIC_TERMS = "FINANCEABLE_PUBLIC_TERMS"
FINANCEABLE_MODELED = "FINANCEABLE_MODELED"
SUPPLIER_TERMS_REQUIRED = "SUPPLIER_TERMS_REQUIRED"
PO_FINANCING_REQUIRED = "PO_FINANCING_REQUIRED"
FINANCING_BLOCKED = "FINANCING_BLOCKED"
FINANCING_UNKNOWN = "FINANCING_UNKNOWN"

# Economic terminals
PROVEN_PROFITABLE = "PROVEN_PROFITABLE"
LIKELY_PROFITABLE = "LIKELY_PROFITABLE"
POSSIBLE_PROFIT = "POSSIBLE_PROFIT"
UNPROFITABLE = "UNPROFITABLE"
ECON_EXECUTION_BLOCKED = "EXECUTION_BLOCKED"
RESEARCH_EXHAUSTED = "RESEARCH_EXHAUSTED"

# Canonical stages (Phase 12)
CANONICAL_STAGES = [
    "DISCOVERED",
    "CANONICALIZED",
    "PRODUCT_QUALIFIED",
    "PACKAGE_ACQUIRED",
    "PACKAGE_VERIFIED",
    "ELIGIBILITY_CLEARED",
    "LINES_EXTRACTED",
    "COMMERCIAL_IDENTITY_READY",
    "REVENUE_EVIDENCE_READY",
    "ACQUISITION_COST_READY",
    "BASKET_READY",
    "FREIGHT_READY",
    "FINANCING_READY",
    "ECONOMICS_READY",
    "EXECUTION_CHECKED",
    "LENDER_READY",
    "BID_READY",
    "REJECTED",
    "BLOCKED",
    "QUOTE_RESERVE",
]

PROGRESS_EVERY = 2
ITEM_DEADLINE_S = 90.0
CONTROL_CAPTURE_S = 120.0
