"""Constants for funnel conservation audit."""

BUILD = "20261004-m3-funnel-conservation-v1"

# Identity terminal statuses (exclusive)
ID_ADVANCED_TO_BOTH_SIDES = "ADVANCED_TO_BOTH_SIDES"
ID_GOV_ONLY = "GOV_ONLY"
ID_PRICE_ONLY = "PRICE_ONLY"
ID_NO_HISTORY_EXHAUSTIVE = "NO_HISTORY_EXHAUSTIVE"
ID_NO_PRICE_EXHAUSTIVE = "NO_PRICE_EXHAUSTIVE"
ID_SHALLOW_HISTORY = "SHALLOW_HISTORY_SEARCH"
ID_SHALLOW_PRICE = "SHALLOW_PRICE_SEARCH"
ID_CONDITION_BLOCK = "CONDITION_BLOCK"
ID_UOM_BLOCK = "UOM_BLOCK"
ID_ELIGIBILITY_BLOCK = "ELIGIBILITY_BLOCK"
ID_EXPIRED = "EXPIRED"
ID_DUPLICATE_COLLAPSED = "DUPLICATE_COLLAPSED"
ID_NOT_PROCESSED = "NOT_PROCESSED"
ID_PIPELINE_BUG = "PIPELINE_BUG"
ID_RETRYABLE = "RETRYABLE_ERROR"
ID_OTHER = "OTHER_EXPLAINED"
ID_INSUFFICIENT = "INSUFFICIENT_IDENTITY"  # maps to OTHER_EXPLAINED in report rollup

IDENTITY_TERMINALS = [
    ID_ADVANCED_TO_BOTH_SIDES,
    ID_GOV_ONLY,
    ID_PRICE_ONLY,
    ID_NO_HISTORY_EXHAUSTIVE,
    ID_NO_PRICE_EXHAUSTIVE,
    ID_SHALLOW_HISTORY,
    ID_SHALLOW_PRICE,
    ID_CONDITION_BLOCK,
    ID_UOM_BLOCK,
    ID_ELIGIBILITY_BLOCK,
    ID_EXPIRED,
    ID_DUPLICATE_COLLAPSED,
    ID_NOT_PROCESSED,
    ID_PIPELINE_BUG,
    ID_RETRYABLE,
    ID_OTHER,
]

# Opportunity terminals
OPP_BOTH_SIDES = "BOTH_SIDES_PRESENT"
OPP_GOV_ONLY = "GOV_ONLY"
OPP_PRICE_ONLY = "PRICE_ONLY"
OPP_NO_EVIDENCE = "NO_EVIDENCE"
OPP_BASKET_INCOMPLETE = "BASKET_INCOMPLETE"
OPP_ECONOMICS_READY = "ECONOMICS_READY"
OPP_PROFITABLE = "PROFITABLE"
OPP_UNPROFITABLE = "UNPROFITABLE"
OPP_EXECUTION_BLOCKED = "EXECUTION_BLOCKED"
OPP_ELIGIBILITY_BLOCKED = "ELIGIBILITY_BLOCKED"
OPP_NOT_PROCESSED = "NOT_PROCESSED"
OPP_PIPELINE_BUG = "PIPELINE_BUG"
OPP_EXPIRED = "EXPIRED"
OPP_OTHER = "OTHER_EXPLAINED"

OPPORTUNITY_TERMINALS = [
    OPP_BOTH_SIDES,
    OPP_GOV_ONLY,
    OPP_PRICE_ONLY,
    OPP_NO_EVIDENCE,
    OPP_BASKET_INCOMPLETE,
    OPP_ECONOMICS_READY,
    OPP_PROFITABLE,
    OPP_UNPROFITABLE,
    OPP_EXECUTION_BLOCKED,
    OPP_ELIGIBILITY_BLOCKED,
    OPP_NOT_PROCESSED,
    OPP_PIPELINE_BUG,
    OPP_EXPIRED,
    OPP_OTHER,
]
