"""Phase E — End-to-end validation harness.

Compares M3 projection outputs against curated golden truth.
Golden expected data is NEVER generated by M3 itself.
"""

from __future__ import annotations

from validation_harness.case_loader import list_cases, load_case, load_cases
from validation_harness.gap_register import GapRegister
from validation_harness.reports import write_run_artifacts
from validation_harness.runner import run_case, run_corpus

BUILD_TAG = "20260922-m3-validation-harness-1"

__all__ = [
    "BUILD_TAG",
    "list_cases",
    "load_case",
    "load_cases",
    "run_case",
    "run_corpus",
    "write_run_artifacts",
    "GapRegister",
]
