"""Phase F — reality comparator report (EXPECTED / ACTUAL / MATCH / DIFFERENCE / …)."""

from __future__ import annotations

from typing import Any

from validation_harness.severity import consequence_for


def _biz_consequence(gap: dict[str, Any]) -> str:
    cat = str(gap.get("category") or "")
    path = str(gap.get("field_path") or "")
    if "QUANTITY" in cat or "uom" in path.lower() or "quantity" in path.lower():
        return "Supplier quote and bid economics may be wrong by unit-scale (e.g. HD vs EA)."
    if "FALSE_READINESS" in cat or "owner_readiness" in path:
        return "Deal may be presented as READY when it is not executable — financial / bid risk."
    if "SUPPLIER" in cat:
        return "Public market price may be mistaken for a validated executable supplier path."
    if "FINANCING" in cat:
        return "Owner cash or personal guarantee risk may be hidden."
    if "PACKAGING" in cat:
        return "Packaging cost/path may be missing from landed economics."
    if "AMENDMENT" in cat:
        return "Stale quantity/deadline may drive supplier quotes and bid."
    return consequence_for(cat, path) or "Operator may act on incorrect information."


def _ui_consequence(gap: dict[str, Any]) -> str:
    path = str(gap.get("field_path") or "")
    if "owner_readiness" in path:
        return "READY banner / approval counts may disagree with Deep Dive blockers."
    if "supplier" in path:
        return "Cards may show supplier as available when validation is incomplete."
    if "quantity" in path or "uom" in path:
        return "Deal may falsely appear highly profitable."
    if "financing" in path:
        return "Owner may not see cash/PG risk on Dashboard."
    return "Operator next-action guidance may be misleading."


def reality_rows_for_case(case: dict[str, Any], result: dict[str, Any]) -> list[dict[str, Any]]:
    """One row per compared field + gaps for reality report."""
    rows: list[dict[str, Any]] = []
    expected = case.get("expected") or {}
    actuals = result.get("actuals") or {}
    comparison = result.get("comparison") or {}
    matches = set(comparison.get("matches") or [])

    for domain, fields in expected.items():
        if not isinstance(fields, dict):
            continue
        act_domain = actuals.get(domain) or {}
        for field, exp in fields.items():
            path = f"{domain}.{field}"
            act = act_domain.get(field)
            match = path in matches or exp == act
            rows.append(
                {
                    "case_id": case.get("case_id"),
                    "field_path": path,
                    "expected": exp,
                    "actual": act,
                    "match": match,
                    "difference": None if match else {"expected": exp, "actual": act},
                    "severity": None,
                    "business_consequence": None,
                    "likely_module": None,
                    "ui_consequence": None,
                }
            )

    for g in comparison.get("gaps") or result.get("gaps") or []:
        rows.append(
            {
                "case_id": case.get("case_id") or g.get("case_id"),
                "field_path": g.get("field_path"),
                "expected": g.get("expected"),
                "actual": g.get("actual"),
                "match": False,
                "difference": {"expected": g.get("expected"), "actual": g.get("actual")},
                "severity": g.get("severity"),
                "business_consequence": _biz_consequence(g),
                "likely_module": g.get("likely_module"),
                "ui_consequence": _ui_consequence(g),
                "category": g.get("category"),
            }
        )
    return rows


def render_reality_markdown(run: dict[str, Any], cases_by_id: dict[str, dict[str, Any]]) -> str:
    lines = [
        "# M3 PHASE F — REALITY COMPARATOR REPORT",
        "",
        f"Run ID: `{run.get('run_id')}`",
        "",
        f"Reality cases: **{(run.get('depth_breakdown') or {}).get('reality_cases', 0)}**",
        "",
        f"Passed: **{run.get('passed')}** · Partial: **{run.get('partial')}** · Failed: **{run.get('failed')}**",
        "",
        "Golden expected truth is curated — never generated by M3.",
        "",
    ]
    for r in run.get("results") or []:
        if str(r.get("validation_depth")) != "reality" and "reality" not in (r.get("tags") or []):
            continue
        cid = r.get("case_id")
        case = cases_by_id.get(cid) or {}
        lines.append(f"## {cid} — {r.get('case_name')}")
        lines.append("")
        lines.append(f"Status: `{r.get('status')}` · Ready: `{r.get('ready_for_owner_approval')}`")
        lines.append("")
        lines.append("| Field | Expected | Actual | Match | Severity | Business consequence | Likely module | UI consequence |")
        lines.append("|---|---|---|---|---|---|---|---|")
        for row in reality_rows_for_case(case or {"case_id": cid, "expected": {}}, r):
            if row.get("match") and not row.get("severity"):
                continue  # keep report focused on differences; matches summarized above
            lines.append(
                "| {field} | `{exp}` | `{act}` | {match} | {sev} | {biz} | `{mod}` | {ui} |".format(
                    field=row.get("field_path"),
                    exp=row.get("expected"),
                    act=row.get("actual"),
                    match="MATCH" if row.get("match") else "DIFF",
                    sev=row.get("severity") or "—",
                    biz=(row.get("business_consequence") or "—").replace("|", "/"),
                    mod=row.get("likely_module") or "—",
                    ui=(row.get("ui_consequence") or "—").replace("|", "/"),
                )
            )
        if not (r.get("gaps") or []):
            lines.append("")
            lines.append("_No differences — all compared fields matched._")
        lines.append("")
    return "\n".join(lines)
