"""Phase F — seed REALITY_CASE corpus (R01–R12).

Expected truth is human-curated. Never generated by M3.
Cases are REALISTIC_FROZEN_FIXTURE unless a true REAL_SOURCE document is attached.
Do not label synthetic Phase E fixtures as real.
"""

from __future__ import annotations

import json
from pathlib import Path

from validation_harness.models import (
    SOURCE_TYPE_REAL_SOURCE,
    SOURCE_TYPE_REALISTIC_FROZEN,
    SOURCE_TYPE_SYNTHETIC_EDGE,
    empty_case,
)

OUT = Path(__file__).resolve().parent / "corpus"

_POS_READY = {
    "owner_readiness_fixture_confirm_all": True,
    "supplier_validated": True,
    "quote_executable": True,
    "formal_quote": True,
    "preferred_supplier": "Validated Wholesale LLC",
    "supplier_quote": {"quoted_total": 22500, "source": "SUPPLIER_FORMAL", "notes": "formal quote"},
    "acquisition_cost": 450,
    "supported_profit": 18400,
    "government_revenue": 52000,
    "economics_complete": True,
    "financing_compatible": True,
    "funding_state": "COMPATIBLE",
    "owner_cash_required_before_payment": 0,
    "personal_guarantee_required": False,
    "submission_complete": True,
    "packaging_resolved": True,
    "delivery_feasible": True,
    "amendments_resolved": True,
    "product_identity_confirmed": True,
    "quantity_uom_confirmed": True,
}


def _r(
    case_id: str,
    case_name: str,
    *,
    fixture: str,
    expected: dict,
    row_overrides: dict | None = None,
    expected_owner_readiness: bool | None = None,
    tags: list[str] | None = None,
    notes: str = "",
    reality_class: str = SOURCE_TYPE_REALISTIC_FROZEN,
    amendment_text: str | None = None,
    ui_expectations: dict | None = None,
    next_action_quality: str | None = None,
    expected_blockers: list | None = None,
    adversarial: bool = False,
) -> dict:
    c = empty_case(
        case_id=case_id,
        case_name=case_name,
        source_type=reality_class,
        source_fixture=fixture,
        row_overrides=row_overrides or {},
        expected=expected,
        expected_owner_readiness=expected_owner_readiness,
        expected_blockers=expected_blockers or [],
        tags=tags or [],
        notes=notes,
        adversarial=adversarial,
        validation_depth="reality",
        reality_class=reality_class,
        ui_expectations=ui_expectations or {},
        next_action_quality=next_action_quality,
    )
    if amendment_text:
        c["amendment_text"] = amendment_text
    return c


def build_reality_cases() -> list[dict]:
    cases: list[dict] = []

    # R01 — SIMPLE COMMERCIAL (path to READY when resolved)
    cases.append(
        _r(
            "R_01",
            "SIMPLE COMMERCIAL PRODUCT — path to READY",
            fixture=(
                "REALISTIC_FROZEN_FIXTURE\n"
                "RFQ CITY-IT-R01\nAgency: City of Fixture Procurement\n"
                "Manufacturer: Dell Inc.\nModel: Latitude 5540\n"
                "Dell Latitude 5540 laptop brand name or equal\n"
                "Quantity: 50 EA\nFOB DESTINATION\nDelivery within 30 days after award\n"
                "Commercial packaging ASTM D3951 acceptable.\n"
                "Submit quotes via email to buying@example.invalid\n"
                "Subject line: CITY-IT-R01 Quote\n"
            ),
            row_overrides=dict(_POS_READY),
            expected={
                "product_identity": {"brand_or_equal_detected": True},
                "quantity_uom": {"has_quantity": True},
                "shipping_delivery": {"fob_destination": True},
                "packaging": {"commercial_packaging_detected": True},
                "supplier": {"supplier_validated": True, "quote_executable": True},
                "economics": {"economics_complete": True},
                "financing": {"financing_compatible": True},
                "owner_readiness": {"ready_for_owner_approval": True},
            },
            expected_owner_readiness=True,
            tags=["reality", "commercial", "positive_ready", "R01"],
            notes="R01 — exact manufacturer/model; commercial pack; destination delivery; executable supplier path",
            next_action_quality="Escalate ready package to owner for bid approval.",
            ui_expectations={
                "ready_banner": True,
                "deep_dive_who_acts": "Owner",
                "no_stage_jargon": True,
            },
        )
    )

    # R02 — DIBBS NSN / approved source (incomplete → blocked; with resolve flags → ready variant in R11 style)
    cases.append(
        _r(
            "R_02",
            "DIBBS NSN / APPROVED SOURCE — incomplete blocks READY",
            fixture=(
                "REALISTIC_FROZEN_FIXTURE\nDIBBS RFQ SPE7M1-26-Q-R02\n"
                "NSN: 5310-00-123-4567\nApproved source CAGE 12345 required. No substitutes.\n"
                "Quantity: 100 EA\nFOB ORIGIN\n"
                "MIL-STD-2073 packaging required.\n"
                "Inspection at destination. Destination acceptance.\n"
                "Submit via DIBBS.\n"
            ),
            row_overrides={"product_classification": "DIBBS_HARDWARE", "current_public_price": 12.5},
            expected={
                "product_identity": {"nsn_detected": True},
                "shipping_delivery": {"fob_origin": True},
                "packaging": {"mil_std_2073_detected": True},
                "inspection_acceptance": {"destination_acceptance": True},
                "supplier": {"supplier_validated": False},
                "owner_readiness": {"ready_for_owner_approval": False},
            },
            expected_owner_readiness=False,
            tags=["reality", "dibbs", "nsn", "negative", "R02"],
            notes="R02 — public price must not clear approved-source / supplier validation",
            next_action_quality=(
                "Confirm an approved-source supplier (CAGE 12345 or equivalent) will quote "
                "100 EA of NSN 5310-00-123-4567 and provide a formal written quote."
            ),
            ui_expectations={"ready_banner": False, "supplier_unresolved_visible": True},
        )
    )

    # R03 — MIL-STD packaging — detect, do not auto-reject, block until resolved
    cases.append(
        _r(
            "R_03",
            "MIL-STD-2073 PACKAGING — detect without false reject",
            fixture=(
                "REALISTIC_FROZEN_FIXTURE\nRFQ PACK-R03\n"
                "Part Number: PKG-2073-55\nQuantity: 40 EA\n"
                "MIL-STD-2073 packaging required. Preservation method TBD.\n"
                "MIL-STD-129 marking. Specialist packaging house may be required.\n"
                "FOB DESTINATION Delivery 45 days ARO.\nSubmit via email.\n"
            ),
            expected={
                "packaging": {"mil_std_2073_detected": True, "specialist_packaging_flagged": True},
                "quantity_uom": {"has_quantity": True},
                "owner_readiness": {"ready_for_owner_approval": False},
            },
            expected_owner_readiness=False,
            tags=["reality", "packaging", "false_rejection", "R03"],
            notes="R03 — MIL packaging must not equal REJECTED; readiness blocked until cost/path resolved",
            next_action_quality=(
                "Confirm with a packaging provider whether MIL-STD-2073 applies for PN PKG-2073-55 "
                "and obtain per-unit packaging cost before bid economics."
            ),
            ui_expectations={"ready_banner": False, "not_lifecycle_rejected": True},
        )
    )

    # R04 — UOM trap HD = hundred
    cases.append(
        _r(
            "R_04",
            "UOM TRAP — HD (hundred) normalization",
            fixture=(
                "REALISTIC_FROZEN_FIXTURE\nRFQ UOM-R04\n"
                "Part Number: BOLT-M8-100\n"
                "Quantity: 552 HD\n"
                "Unit of measure: HD (hundred). One HD = 100 each.\n"
                "Total pieces required = 55,200 EA equivalent.\n"
                "FOB DESTINATION Delivery 30 days.\nCommercial packaging.\nSubmit via email.\n"
            ),
            row_overrides={
                "uom": "HD",
                "quantity": 552,
                "quantity_uom_confirmed": True,
                "total_pieces": 55200,
            },
            expected={
                "quantity_uom": {
                    "has_quantity": True,
                    "hd_hundred_detected": True,
                    "total_pieces_noted": True,
                },
                "owner_readiness": {"ready_for_owner_approval": False},
            },
            expected_owner_readiness=False,
            tags=["reality", "uom", "quantity", "trap", "R04", "REGRESSION_QUANTITY"],
            notes=(
                "R04 — expected business truth: 552 HD = 55,200 pieces. "
                "If M3 treats HD as EA, economics understate by 100x (CRITICAL)."
            ),
            next_action_quality=(
                "Normalize quantity: confirm supplier quote covers 55,200 pieces "
                "(552 HD × 100), not 552 each."
            ),
            ui_expectations={"ready_banner": False},
            reality_class=SOURCE_TYPE_SYNTHETIC_EDGE,
        )
    )

    # R05 — multi-CLIN multi-destination
    cases.append(
        _r(
            "R_05",
            "MULTI-CLIN / MULTI-DESTINATION — do not flatten",
            fixture=(
                "REALISTIC_FROZEN_FIXTURE\nRFQ MULTI-R05\nPart Number: MC-100\n"
                "CLIN 0001 Quantity: 100 EA Destination: Richmond VA FOB DESTINATION Delivery 30 days ARO\n"
                "CLIN 0002 Quantity: 250 EA Destination: Norfolk VA FOB ORIGIN Delivery 45 days ARO\n"
                "Submit via email.\n"
            ),
            row_overrides={
                "line_items": [
                    {"clin": "0001", "quantity": 100, "uom": "EA", "destination": "Richmond", "fob": "DESTINATION"},
                    {"clin": "0002", "quantity": 250, "uom": "EA", "destination": "Norfolk", "fob": "ORIGIN"},
                ]
            },
            expected={
                "quantity_uom": {"multi_clin_destinations": 2},
                "shipping_delivery": {"fob_destination": True, "fob_origin": True},
                "owner_readiness": {"ready_for_owner_approval": False},
            },
            expected_owner_readiness=False,
            tags=["reality", "clin", "delivery", "R05"],
            notes="R05 — two destinations/FOBs must remain distinct in execution",
            next_action_quality=(
                "Request separate freight quotes for CLIN 0001 Richmond (FOB Destination) "
                "and CLIN 0002 Norfolk (FOB Origin) before rolling economics."
            ),
        )
    )

    # R06 — amendment quantity/deadline
    cases.append(
        _r(
            "R_06",
            "AMENDMENT — latest quantity and deadline authoritative",
            fixture=(
                "REALISTIC_FROZEN_FIXTURE\nRFQ AMD-R06\n"
                "Part Number: AMD-9\nQuantity: 100 EA\n"
                "Bid deadline: 2026-10-10\nFOB DESTINATION\n"
                "Acknowledge all amendments.\nSubmit via email.\n"
            ),
            amendment_text=(
                "REALISTIC_FROZEN_FIXTURE Amendment 0001\n"
                "Quantity changed to 150 EA.\n"
                "Bid deadline extended to 2026-10-14.\n"
                "FOB DESTINATION unchanged.\nAcknowledge amendment.\n"
            ),
            expected={
                "amendment": {"amendment_applied": True},
                "submission": {"amendment_ack_required": True},
                "owner_readiness": {"ready_for_owner_approval": False},
            },
            expected_owner_readiness=False,
            tags=["reality", "amendment", "R06", "REGRESSION_AMENDMENT"],
            notes="R06 — downstream logic must use 150 EA / 2026-10-14 after amendment",
            next_action_quality=(
                "Resolve whether the amendment dated for RFQ AMD-R06 supersedes the original "
                "quantity (150 EA) before requesting supplier pricing."
            ),
        )
    )

    # R07 — IDIQ estimate vs minimum
    cases.append(
        _r(
            "R_07",
            "IDIQ / ESTIMATE VS MINIMUM — estimate not guaranteed revenue",
            fixture=(
                "REALISTIC_FROZEN_FIXTURE\nRFQ IDIQ-R07\n"
                "Part Number: IDIQ-22\n"
                "Estimated annual quantity: 10,000 EA (estimate only — not a guaranteed order quantity).\n"
                "Minimum order quantity: 50 EA.\nContract ceiling: $2,000,000.\n"
                "FOB DESTINATION.\nSubmit via email.\n"
            ),
            expected={
                "quantity_uom": {"estimate_flagged_not_guaranteed": True, "has_quantity": True},
                "owner_readiness": {"ready_for_owner_approval": False},
                "financing": {"financing_assumed": False},
            },
            expected_owner_readiness=False,
            tags=["reality", "idiq", "quantity", "R07"],
            notes="R07 — estimated annual qty ≠ guaranteed order; ceiling ≠ revenue",
            next_action_quality=(
                "Treat 10,000 EA as an estimate only; price supplier quotes against the "
                "50 EA minimum (or confirmed release quantity), not the ceiling."
            ),
        )
    )

    # R08 — First Article
    cases.append(
        _r(
            "R_08",
            "FIRST ARTICLE / TEST — production hold until acceptance",
            fixture=(
                "REALISTIC_FROZEN_FIXTURE\nRFQ FAT-R08\n"
                "Part Number: FAT-1 Quantity: 15 EA\n"
                "First Article Test (FAT) required prior to production.\n"
                "Source inspection may apply for FAT.\n"
                "Destination acceptance after FAT approval.\n"
                "FOB DESTINATION. Submit via email.\n"
            ),
            expected={
                "inspection_acceptance": {"first_article": True},
                "owner_readiness": {"ready_for_owner_approval": False},
            },
            expected_owner_readiness=False,
            tags=["reality", "fat", "inspection", "post_award", "R08"],
            notes="R08 — post-award workflow must reflect testing hold; not normal production start",
            next_action_quality=(
                "Document First Article Test requirements and confirm supplier can support "
                "FAT for PN FAT-1 before treating production as unlocked."
            ),
        )
    )

    # R09 — Source inspection
    cases.append(
        _r(
            "R_09",
            "SOURCE INSPECTION — survives into execution / supplier packet",
            fixture=(
                "REALISTIC_FROZEN_FIXTURE\nRFQ SRC-R09\n"
                "Part Number: SI-2 Quantity: 8 EA\n"
                "Source inspection required at contractor facility.\n"
                "Certificate of Conformance required.\n"
                "FOB ORIGIN. Submit via email.\n"
            ),
            expected={
                "inspection_acceptance": {"source_inspection": True, "certificate_of_conformance": True},
                "shipping_delivery": {"fob_origin": True},
                "owner_readiness": {"ready_for_owner_approval": False},
            },
            expected_owner_readiness=False,
            tags=["reality", "inspection", "supplier", "R09"],
            notes="R09 — source inspection must appear in supplier confirmation packet",
            next_action_quality=(
                "Ask Supplier whether source inspection at their facility is supported for "
                "PN SI-2 (8 EA) and include CoC in the quote packet."
            ),
        )
    )

    # R10 — Financing failure (good margin/supplier, cash/PG required)
    cases.append(
        _r(
            "R_10",
            "FINANCING FAILURE — good deal economics but cash/PG blocks owner",
            fixture=(
                "REALISTIC_FROZEN_FIXTURE\nRFQ FIN-R10\n"
                "Part Number: FIN-OK-1 brand name or equal\nQuantity: 20 EA\n"
                "FOB DESTINATION Delivery 30 days\nCommercial packaging acceptable\n"
                "Submit via email.\n"
            ),
            row_overrides={
                **{k: v for k, v in _POS_READY.items() if k not in {"financing_compatible", "funding_state", "owner_cash_required_before_payment", "personal_guarantee_required"}},
                "financing_compatible": False,
                "funding_state": "UNRESOLVED_OWNER_CASH",
                "owner_cash_required_before_payment": 45000,
                "personal_guarantee_required": True,
            },
            expected={
                "supplier": {"supplier_validated": True},
                "economics": {"economics_complete": True},
                "financing": {"financing_compatible": False},
                "owner_readiness": {"ready_for_owner_approval": False},
                "execution_blockers_include_any": ["FINANCING_INCOMPATIBLE_OR_UNKNOWN"],
            },
            expected_owner_readiness=False,
            tags=["reality", "financing", "false_readiness", "R10", "REGRESSION_READY"],
            notes="R10 — high margin must not override owner-cash / PG prohibition",
            next_action_quality=(
                "Financing is unresolved. Supplier terms require payment before government "
                "reimbursement and a personal guarantee is indicated. Confirm a zero-owner-cash, "
                "non-PG funding path before bid approval."
            ),
            ui_expectations={"ready_banner": False, "financing_blocker_visible": True},
        )
    )

    # R11 — GOOD DEAL (critical positive)
    cases.append(
        _r(
            "R_11",
            "GOOD DEAL — fully executable READY FOR OWNER APPROVAL",
            fixture=(
                "REALISTIC_FROZEN_FIXTURE\nRFQ GOOD-R11\nAgency: Fixture Agency\n"
                "Manufacturer: AcmeCorp Model: X100\nPart Number: ACME-X100-R11\n"
                "Quantity: 25 EA\nFOB DESTINATION Delivery within 20 days after award\n"
                "Commercial packaging ASTM D3951 acceptable.\n"
                "Submit quotes via email to buying@example.invalid\n"
                "Subject line: GOOD-R11 Quote\n"
            ),
            row_overrides={
                **_POS_READY,
                "preferred_supplier": "AcmeCorp Authorized Distributor",
                "product_classification": "COMMERCIAL_HARDWARE",
            },
            expected={
                "classification": {"product_classification": "COMMERCIAL_HARDWARE"},
                "product_identity": {"part_number_detected": True},
                "quantity_uom": {"has_quantity": True},
                "supplier": {"supplier_validated": True, "quote_executable": True, "state": "QUOTE_EXECUTABLE"},
                "economics": {"economics_complete": True},
                "financing": {"financing_compatible": True},
                "owner_readiness": {"ready_for_owner_approval": True},
            },
            expected_owner_readiness=True,
            tags=["reality", "positive_ready", "good_deal", "R11", "REGRESSION_READY"],
            notes="R11 — proves M3 can let a genuinely executable deal through",
            next_action_quality="Present READY package to owner for bid approval decision.",
            ui_expectations={
                "ready_banner": True,
                "dashboard_and_deep_dive_agree": True,
                "pipeline_consistent": True,
            },
        )
    )

    # R12 — BAD DEAL THAT LOOKS GOOD
    cases.append(
        _r(
            "R_12",
            "BAD DEAL THAT LOOKS GOOD — public price + MIL pack + missing submission",
            fixture=(
                "REALISTIC_FROZEN_FIXTURE\nRFQ LOOKS-GOOD-R12\n"
                "Part Number: SHINY-99 brand name or equal\nQuantity: 30 EA\n"
                "Apparent high margin opportunity.\n"
                "MIL-STD-2073 packaging required. Approved source traceability required.\n"
                "FOB DESTINATION Delivery 15 days.\n"
                "Signed representations and certifications required. Acknowledge all amendments.\n"
                "Submit via portal with mandatory attachments.\n"
            ),
            row_overrides={
                "current_public_price": 99.0,
                "supported_profit": 50000,
                "government_revenue": 80000,
                "preferred_supplier": "Online Marketplace Seller",
                # economics look good but supplier/packaging/submission unresolved
                "economics_complete": True,
                "acquisition_cost": 40,
            },
            expected={
                "packaging": {"mil_std_2073_detected": True},
                "supplier": {"supplier_validated": False, "has_public_market_price": True},
                "owner_readiness": {"ready_for_owner_approval": False},
                "execution_blockers_include_any": [
                    "SUPPLIER_NOT_VALIDATED",
                    "QUOTE_NOT_EXECUTABLE",
                    "PACKAGING_UNRESOLVED",
                    "SUBMISSION_INCOMPLETE_OR_UNKNOWN",
                    "FINANCING_INCOMPATIBLE_OR_UNKNOWN",
                ],
            },
            expected_owner_readiness=False,
            tags=["reality", "false_readiness", "looks_good", "R12", "REGRESSION_SUPPLIER"],
            notes="R12 — public price + high margin must not create READY",
            next_action_quality=(
                "Do not escalate. Resolve approved-source / traceability, obtain a formal "
                "supplier quote (not public web price), confirm MIL-STD-2073 packaging cost, "
                "and complete mandatory submission attachments."
            ),
            ui_expectations={"ready_banner": False},
            adversarial=True,
        )
    )

    # R13 — REAL_SOURCE: Opp199 SAM/GSA (frozen local fixture — not live scrape)
    cases.append(
        _r(
            "R_13",
            "REAL_SOURCE Opp199 — SAM 47QACA26Q0439 Dell PowerEdge R670",
            reality_class=SOURCE_TYPE_REAL_SOURCE,
            fixture=(
                "REAL_SOURCE_FIXTURE\n"
                "Source: fixtures/opp199.py + _opp199_stage3_report.json (frozen local)\n"
                "Solicitation: 47QACA26Q0439\n"
                "Notice: 610bea2df5c1436994e316259e29a9a6\n"
                "Agency: GSA / FAS\n"
                "Part Number: 210-BNZH\n"
                "Dell PowerEdge R670 Server brand-name basis\n"
                "Quantity: 14 EA\n"
                "Ship to: 2415 Eisenhower Avenue, Alexandria, VA 22314\n"
                "Delivery within 30 days ARO\n"
                "FOB DESTINATION\n"
                "On-Site Installation Declined\n"
                "Memory: 16GB RDIMM 6400MT/s — 8 per server (112 total)\n"
                "Storage: 2.4TB SAS — 6 per server (84 total)\n"
                "Submit per solicitation package.\n"
            ),
            row_overrides={
                "canonical_id": "opp199:47QACA26Q0439",
                "solicitation_number": "47QACA26Q0439",
                "product_classification": "IT_SERVER",
                "preferred_supplier": "Dell Technologies Federal / Dell Federal Systems L.P.",
                "line_items": [
                    {"clin": "0001", "description": "Dell PowerEdge R670 / 210-BNZH", "quantity": 14, "uom": "EA", "destination": "Alexandria VA", "fob": "DESTINATION"},
                ],
            },
            expected={
                "product_identity": {"part_number_detected": True},
                "quantity_uom": {"has_quantity": True},
                "shipping_delivery": {"fob_destination": True, "delivery_aro_detected": True},
                "owner_readiness": {"ready_for_owner_approval": False},
            },
            expected_owner_readiness=False,
            tags=["reality", "real_source", "opp199", "sam", "R13"],
            notes=(
                "R13 — REAL_SOURCE from local Opp199 frozen reports/fixtures. "
                "Incomplete supplier/econ/finance → not READY (expected)."
            ),
            next_action_quality=(
                "Request a formal quote from Dell Federal / authorized reseller for 14 EA of "
                "PN 210-BNZH (PowerEdge R670) delivered to Alexandria VA within 30 days ARO; "
                "confirm memory and storage BOM quantities match the solicitation."
            ),
            ui_expectations={"ready_banner": False, "real_source_labeled": True},
        )
    )

    # R14 — REAL_SOURCE: Iowa Jaggaer wildflower seed (frozen breakthrough artifact)
    cases.append(
        _r(
            "R_14",
            "REAL_SOURCE Iowa — 645-DOTRFB-3046-2027 Wildflower and Native Grass Seed",
            reality_class=SOURCE_TYPE_REAL_SOURCE,
            fixture=(
                "REAL_SOURCE_FIXTURE\n"
                "Source: artifacts/m3_iowa_live_breakthrough.json (frozen local; auth tokens redacted)\n"
                "Solicitation: 645-DOTRFB-3046-2027\n"
                "Agency: State of Iowa Department of Administrative Services\n"
                "Title: Wildflower and Native Grass Seed\n"
                "Response deadline: 9/28/2026, 1:00 PM CDT\n"
                "Open date is not the response deadline.\n"
                "Line P1: Big bluestem (Andropogon gerardii) Quantity: 324.3 LB\n"
                "Line P3: Blue grama (Bouteloua gracilis) Quantity: 324.0 LB\n"
                "Line P4: Canada wildrye (Elymus canadensis) Quantity: 108.1 LB\n"
                "Multi-line seed BOM (~196 lines in source PDF).\n"
                "Submit via Iowa DAS Jaggaer / SciQuest event.\n"
            ),
            row_overrides={
                "canonical_id": "sol:645DOTRFB30462027:stateofiowadepartmentofadministrativeser",
                "solicitation_number": "645-DOTRFB-3046-2027",
                "agency": "State of Iowa Department of Administrative Services",
                "product_classification": "AGRICULTURAL_SEED",
                "deadline": "2026-09-28T13:00:00-05:00",
                "open_is_not_response_deadline": True,
                "line_items": [
                    {"clin": "P1", "description": "Big bluestem (Andropogon gerardii)", "quantity": 324.3, "uom": "LB"},
                    {"clin": "P3", "description": "Blue grama (Bouteloua gracilis)", "quantity": 324.0, "uom": "LB"},
                    {"clin": "P4", "description": "Canada wildrye (Elymus canadensis)", "quantity": 108.1, "uom": "LB"},
                ],
            },
            expected={
                "quantity_uom": {"has_quantity": True},
                "owner_readiness": {"ready_for_owner_approval": False},
            },
            expected_owner_readiness=False,
            tags=["reality", "real_source", "iowa", "jaggaer", "multi_line", "R14"],
            notes=(
                "R14 — REAL_SOURCE from frozen Iowa breakthrough artifact. "
                "Multi-line LB UOM seed buy; not READY without supplier/econ/finance resolution."
            ),
            next_action_quality=(
                "Obtain supplier quotes covering the full seed BOM in pounds (not EA), "
                "starting with Big bluestem 324.3 LB and Blue grama 324.0 LB, before economics."
            ),
            ui_expectations={"ready_banner": False, "real_source_labeled": True},
        )
    )

    return cases


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    cases = build_reality_cases()
    for c in cases:
        path = OUT / f"{c['case_id']}.json"
        path.write_text(json.dumps(c, indent=2), encoding="utf-8")
        print("wrote", path.name)
    print("total_reality", len(cases))


if __name__ == "__main__":
    main()
