"""Acquisition-cost scale models + channel quote path statuses.

Build: 20261004-m3-acquisition-scale-v1

Historical awards = revenue/channel only — NEVER acquisition cost.
"""

from __future__ import annotations

BUILD = "20261004-m3-acquisition-scale-v1"

PUBLIC_PRICE_AVAILABLE = "PUBLIC_PRICE_AVAILABLE"
PUBLIC_PRICE_BLOCKED_RETRYABLE = "PUBLIC_PRICE_BLOCKED_RETRYABLE"
OEM_QUOTE_PATH_IDENTIFIED = "OEM_QUOTE_PATH_IDENTIFIED"
DISTRIBUTOR_QUOTE_PATH_IDENTIFIED = "DISTRIBUTOR_QUOTE_PATH_IDENTIFIED"
CHANNEL_PATH_IDENTIFIED = "CHANNEL_PATH_IDENTIFIED"
NO_EXECUTABLE_CHANNEL_FOUND = "NO_EXECUTABLE_CHANNEL_FOUND"

OEM_QUOTE_REQUIRED = "OEM_QUOTE_REQUIRED"
DISTRIBUTOR_QUOTE_REQUIRED = "DISTRIBUTOR_QUOTE_REQUIRED"
SUPPLIER_QUOTE_REQUIRED = "SUPPLIER_QUOTE_REQUIRED"

# Priority ranks (lower = research first)
PRIORITY_STRONG_R1_R3 = 1
PRIORITY_CURRENT_VALUE = 2
PRIORITY_EXACT_PRIOR_LINE = 3
PRIORITY_RECURRING_BASKET = 4
PRIORITY_OPEN_RESELLER = 5
PRIORITY_MANAGEABLE_BASKET = 6
PRIORITY_OTHER = 9
