"""Discovery network constants — source types, trust tiers, live capability statuses."""

from __future__ import annotations

# Source types (jurisdiction / buyer)
SOURCE_FEDERAL_PUBLIC = "FEDERAL_PUBLIC"
SOURCE_STATE = "STATE"
SOURCE_COUNTY = "COUNTY"
SOURCE_CITY = "CITY"
SOURCE_SCHOOL_DISTRICT = "SCHOOL_DISTRICT"
SOURCE_PUBLIC_UNIVERSITY = "PUBLIC_UNIVERSITY"
SOURCE_PUBLIC_COLLEGE = "PUBLIC_COLLEGE"
SOURCE_AIRPORT = "AIRPORT"
SOURCE_TRANSIT = "TRANSIT"
SOURCE_PUBLIC_UTILITY = "PUBLIC_UTILITY"
SOURCE_SPECIAL_DISTRICT = "SPECIAL_DISTRICT"
SOURCE_COOPERATIVE = "COOPERATIVE"
SOURCE_OTHER_PUBLIC = "OTHER_PUBLIC"

SOURCE_TYPES = (
    SOURCE_FEDERAL_PUBLIC,
    SOURCE_STATE,
    SOURCE_COUNTY,
    SOURCE_CITY,
    SOURCE_SCHOOL_DISTRICT,
    SOURCE_PUBLIC_UNIVERSITY,
    SOURCE_PUBLIC_COLLEGE,
    SOURCE_AIRPORT,
    SOURCE_TRANSIT,
    SOURCE_PUBLIC_UTILITY,
    SOURCE_SPECIAL_DISTRICT,
    SOURCE_COOPERATIVE,
    SOURCE_OTHER_PUBLIC,
)

# Trust tiers
TIER_1 = 1  # official government portal
TIER_2 = 2  # official cooperative
TIER_3 = 3  # reputable aggregator
TIER_4 = 4  # other discovery lead

# Adapter / source capability status
# LIVE_VERIFIED = production fetcher + passed real live validation against current endpoint
# UNVERIFIED_LIVE = has fetcher+URL but NOT yet live-validated (was formerly optimistic LIVE_CAPABLE)
# FIXTURE_ONLY = parser proven on fixtures only
ADAPTER_LIVE_VERIFIED = "LIVE_VERIFIED"
ADAPTER_UNVERIFIED_LIVE = "UNVERIFIED_LIVE"
ADAPTER_LIVE_CAPABLE = ADAPTER_UNVERIFIED_LIVE  # legacy alias — no longer means verified
ADAPTER_FIXTURE_ONLY = "FIXTURE_ONLY"
ADAPTER_PARTIAL = "PARTIAL"
ADAPTER_PLANNED = "PLANNED"
ADAPTER_AUTH_REQUIRED = "AUTH_REQUIRED"
ADAPTER_BLOCKED = "BLOCKED"
ADAPTER_BROKEN = "BROKEN"
ADAPTER_DEGRADED = "DEGRADED"
ADAPTER_UNSUPPORTED = "UNSUPPORTED"
# Legacy alias used by older tests/registry rows
ADAPTER_IMPLEMENTED = ADAPTER_FIXTURE_ONLY

ADAPTER_STATUSES = (
    ADAPTER_LIVE_VERIFIED,
    ADAPTER_UNVERIFIED_LIVE,
    ADAPTER_FIXTURE_ONLY,
    ADAPTER_PARTIAL,
    ADAPTER_PLANNED,
    ADAPTER_AUTH_REQUIRED,
    ADAPTER_BLOCKED,
    ADAPTER_BROKEN,
    ADAPTER_DEGRADED,
    ADAPTER_UNSUPPORTED,
)

# Statuses eligible for controlled live validation attempts
VALIDATABLE_STATUSES = (
    ADAPTER_UNVERIFIED_LIVE,
    ADAPTER_DEGRADED,
    ADAPTER_LIVE_VERIFIED,  # re-check allowed
)

# Health
HEALTH_HEALTHY = "HEALTHY"
HEALTH_DEGRADED = "DEGRADED"
HEALTH_BROKEN = "BROKEN"
HEALTH_AUTH_REQUIRED = "AUTH_REQUIRED"
HEALTH_BLOCKED = "BLOCKED"
HEALTH_DISABLED = "DISABLED"
HEALTH_UNTESTED = "UNTESTED"

# Product classification (discovery-stage, free/deterministic)
CLASS_CORE_PRODUCT = "CORE_PRODUCT"
CLASS_PRODUCT_PLUS_SERVICE = "PRODUCT_PLUS_SERVICE"
CLASS_UNKNOWN = "UNKNOWN"
CLASS_SERVICE = "SERVICE"
CLASS_CLEARLY_IRRELEVANT = "CLEARLY_IRRELEVANT"

CLASS_PRIORITY_ORDER = (
    CLASS_CORE_PRODUCT,
    CLASS_PRODUCT_PLUS_SERVICE,
    CLASS_UNKNOWN,
    CLASS_SERVICE,
    CLASS_CLEARLY_IRRELEVANT,
)

# Notice types
NOTICE_OPEN_SOLICITATION = "OPEN_SOLICITATION"
NOTICE_AWARD = "AWARD_NOTICE"
NOTICE_CANCELLED = "CANCELLED"
NOTICE_FORECAST = "FORECAST"
NOTICE_PRESOLICITATION = "PRESOLICITATION"
NOTICE_AWARDED_CONTRACT_CATALOG = "AWARDED_CONTRACT_CATALOG"
NOTICE_UNKNOWN = "NOTICE_UNKNOWN"

# Operator statuses
OP_NEW = "NEW"
OP_NEEDS_REVIEW = "NEEDS_REVIEW"
OP_RESEARCH_CANDIDATE = "RESEARCH_CANDIDATE"
OP_REJECTED = "REJECTED"
OP_WATCH = "WATCH"
OP_ACTIVE_DEAL = "ACTIVE_DEAL"

# Platform families
PLATFORM_BONFIRE = "Bonfire"
PLATFORM_OPENGOV = "OpenGov"
PLATFORM_IONWAVE = "IonWave"
PLATFORM_PLANETBIDS = "PlanetBids"
PLATFORM_BIDNET = "BidNet"
PLATFORM_DEMANDSTAR = "DemandStar"
PLATFORM_JAGGAER = "Jaggaer"
PLATFORM_PERISCOPE = "Periscope"
PLATFORM_PUBLIC_PURCHASE = "PublicPurchase"
PLATFORM_BEACON = "BeaconBid"
PLATFORM_VENDOR_REGISTRY = "VendorRegistry"
PLATFORM_BIDDINGO = "Biddingo"
PLATFORM_SIMPLE_HTML = "SimpleHTML"
PLATFORM_RSS = "RSS"
PLATFORM_JSON = "JSON"
PLATFORM_STATE_OWNED = "StateOwned"
PLATFORM_UNKNOWN = "UNKNOWN"

PLATFORM_FAMILIES = (
    PLATFORM_BONFIRE,
    PLATFORM_OPENGOV,
    PLATFORM_IONWAVE,
    PLATFORM_PLANETBIDS,
    PLATFORM_BIDNET,
    PLATFORM_DEMANDSTAR,
    PLATFORM_JAGGAER,
    PLATFORM_PERISCOPE,
    PLATFORM_PUBLIC_PURCHASE,
    PLATFORM_BEACON,
    PLATFORM_VENDOR_REGISTRY,
    PLATFORM_BIDDINGO,
    PLATFORM_SIMPLE_HTML,
    PLATFORM_RSS,
    PLATFORM_JSON,
    PLATFORM_STATE_OWNED,
    PLATFORM_UNKNOWN,
)

CADENCE_FAST = "FAST"
CADENCE_NORMAL = "NORMAL"
CADENCE_SLOW = "SLOW"
