"""Direct county/city purchasing portal catalog for L.17.2 saturation (authoritative buyer sites)."""

from __future__ import annotations

from typing import Any

from discovery.lower48 import MANUAL_PUBLIC, PORTAL_DISCOVERED_NOT_INTEGRATED

# Explicit researched purchasing pages — priority states first (TX GA VA KY MO KS IL IA) then national.
# Format: (state, buyer_type, name_hint, url, platform_or_None, status)
COUNTY_CITY_PORTALS: list[tuple[str, str, str, str, str | None, str]] = [
    # --- Texas counties (priority) ---
    ("TX", "COUNTY", "Harris", "https://www.harriscountytx.gov/Purchasing", "Bonfire", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Dallas", "https://www.dallascounty.org/departments/purchasing/", "Bonfire", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Tarrant", "https://www.tarrantcounty.com/en/purchasing.html", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Bexar", "https://www.bexar.org/1480/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Travis", "https://www.traviscountytx.gov/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Collin", "https://www.collincountytx.gov/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Denton", "https://www.dentoncounty.gov/Departments/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Fort Bend", "https://www.fortbendcountytx.gov/government/departments/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Williamson", "https://www.wilco.org/Departments/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Hidalgo", "https://www.hidalgocounty.us/256/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "El Paso", "https://www.epcounty.com/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Montgomery", "https://www.mctx.org/departments_offices/departments/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Cameron", "https://www.cameroncountytx.gov/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Brazoria", "https://www.brazoriacountytx.gov/departments/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Galveston", "https://www.galvestoncountytx.gov/our-county/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Nueces", "https://www.nuecesco.com/county-services/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Bell", "https://www.bellcountytx.com/county_offices/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "McLennan", "https://www.co.mclennan.tx.us/161/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Lubbock", "https://www.lubbockcounty.gov/departments/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Webb", "https://www.webbcountytx.gov/Purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Jefferson", "https://co.jefferson.tx.us/Purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Smith", "https://www.smith-county.com/government/departments/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Hays", "https://hayscountytx.com/departments/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Ellis", "https://www.co.ellis.tx.us/161/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Johnson", "https://www.johnsoncountytx.org/departments/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Guadalupe", "https://www.co.guadalupe.tx.us/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Comal", "https://www.co.comal.tx.us/Purchasing.htm", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Parker", "https://www.parkercountytx.com/161/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Brazos", "https://www.brazoscountytx.gov/161/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Kaufman", "https://www.kaufmancounty.net/departments/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Rockwall", "https://www.rockwallcountytexas.com/161/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Hunt", "https://www.huntcounty.net/page/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Gregg", "https://www.co.gregg.tx.us/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Potter", "https://www.pottercountytx.gov/departments/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Randall", "https://www.randallcounty.com/161/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Taylor", "https://www.taylorcountytexas.org/161/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Tom Green", "https://www.co.tom-green.tx.us/page/tomgreen.Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Midland", "https://www.co.midland.tx.us/161/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Ector", "https://www.co.ector.tx.us/page/ector.Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Wichita", "https://www.co.wichita.tx.us/page/wichita.Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Houston", "https://purchasing.houstontx.gov/", "Bonfire", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Dallas", "https://dallascityhall.com/departments/procurement/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Austin", "https://www.austintexas.gov/department/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "San Antonio", "https://www.sa.gov/Directory/Departments/Finance/Purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Fort Worth", "https://www.fortworthtexas.gov/departments/finance/purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "El Paso", "https://www.elpasotexas.gov/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Arlington", "https://www.arlingtontx.gov/city_hall/departments/purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Corpus Christi", "https://www.cctexas.com/departments/finance-and-procurement/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Plano", "https://www.plano.gov/1475/Purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Laredo", "https://www.cityoflaredo.com/Purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Lubbock", "https://ci.lubbock.tx.us/departments/purchasing", "IonWave", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Garland", "https://www.garlandtx.gov/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Irving", "https://www.cityofirving.org/1395/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Amarillo", "https://www.amarillo.gov/?page_id=122", "IonWave", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Grand Prairie", "https://www.gptx.org/city-government/city-departments/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "McKinney", "https://www.mckinneytexas.org/199/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Frisco", "https://www.friscotexas.gov/214/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Pasadena", "https://www.pasadenatx.gov/159/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Mesquite", "https://www.cityofmesquite.com/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Killeen", "https://www.killeentexas.gov/145/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "McAllen", "https://www.mcallen.net/departments/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Waco", "https://www.waco-texas.com/Departments/Purchasing", "IonWave", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Denton", "https://www.cityofdenton.com/175/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Carrollton", "https://www.cityofcarrollton.com/departments/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Midland", "https://www.midlandtexas.gov/149/Purchasing", "IonWave", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Abilene", "https://www.abilenetx.gov/149/Purchasing", "IonWave", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Beaumont", "https://beaumonttexas.gov/departments/purchasing/", "IonWave", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Round Rock", "https://www.roundrocktexas.gov/departments/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Richardson", "https://www.cor.net/departments/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Odessa", "https://www.odessa-tx.gov/149/Purchasing", "IonWave", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Tyler", "https://www.cityoftyler.org/government/departments/purchasing", "IonWave", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "College Station", "https://www.cstx.gov/departments___city_hall/purchasing", "IonWave", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Pearland", "https://www.pearlandtx.gov/departments/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "League City", "https://www.leaguecitytx.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Allen", "https://www.cityofallen.org/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Sugar Land", "https://www.sugarlandtx.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Edinburg", "https://www.cityofedinburg.com/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Mission", "https://missiontexas.us/city-departments/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Pharr", "https://www.pharr-tx.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Bryan", "https://www.bryantx.gov/149/Purchasing", "IonWave", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Missouri City", "https://www.missouricitytx.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Baytown", "https://www.baytown.org/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Flower Mound", "https://www.flower-mound.com/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "New Braunfels", "https://www.nbtexas.org/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Cedar Park", "https://www.cedarparktexas.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Georgetown", "https://georgetown.org/departments/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Temple", "https://www.templetx.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "San Angelo", "https://www.cosatx.us/departments-services/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Wichita Falls", "https://www.wichitafallstx.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Conroe", "https://www.conroe.org/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Nacogdoches", "https://www.nactx.us/149/Purchasing", None, MANUAL_PUBLIC),
    # --- Georgia ---
    ("GA", "COUNTY", "Fulton", "https://www.fultoncountyga.gov/services/doing-business/procurement", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "COUNTY", "Gwinnett", "https://www.gwinnettcounty.com/web/gwinnett/Departments/SupportServices/Purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "COUNTY", "Cobb", "https://www.cobbcounty.org/finance/purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "COUNTY", "DeKalb", "https://www.dekalbcountyga.gov/purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "COUNTY", "Chatham", "https://www.chathamcountyga.gov/Departments/Finance/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "COUNTY", "Clayton", "https://www.claytoncountyga.gov/government/finance/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "COUNTY", "Cherokee", "https://www.cherokeega.com/Purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "COUNTY", "Henry", "https://www.henrycounty-ga.com/Departments/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "COUNTY", "Forsyth", "https://www.forsythco.com/Departments-Offices/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "COUNTY", "Hall", "https://www.hallcounty.org/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "COUNTY", "Richmond", "https://www.augustaga.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "COUNTY", "Muscogee", "https://www.columbusga.gov/finance/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "COUNTY", "Bibb", "https://www.maconbibb.us/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "CITY", "Atlanta", "https://www.atlantaga.gov/government/departments/procurement", "Bonfire", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "CITY", "Savannah", "https://www.savannahga.gov/137/Purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "CITY", "Augusta", "https://www.augustaga.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "CITY", "Columbus", "https://www.columbusga.gov/finance/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "CITY", "Macon", "https://www.maconbibb.us/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "CITY", "Athens", "https://www.accgov.com/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "CITY", "Sandy Springs", "https://www.sandyspringsga.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "CITY", "Roswell", "https://www.roswellgov.com/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "CITY", "Johns Creek", "https://www.johnscreekga.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "CITY", "Alpharetta", "https://www.alpharetta.ga.us/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    # --- Virginia ---
    ("VA", "COUNTY", "Fairfax", "https://www.fairfaxcounty.gov/procurement/", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "COUNTY", "Prince William", "https://www.pwcgov.org/government/dept/finance/Pages/Purchasing.aspx", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "COUNTY", "Loudoun", "https://www.loudoun.gov/purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "COUNTY", "Chesterfield", "https://www.chesterfield.gov/149/Purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "COUNTY", "Henrico", "https://henrico.us/finance/divisions/purchasing/", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "COUNTY", "Arlington", "https://www.arlingtonva.us/Government/Departments/DTS/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "COUNTY", "Stafford", "https://www.staffordcountyva.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "COUNTY", "Spotsylvania", "https://www.spotsylvania.va.us/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "COUNTY", "Albemarle", "https://www.albemarle.org/government/finance/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "COUNTY", "Hanover", "https://www.hanovercounty.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "CITY", "Virginia Beach", "https://www.vbgov.com/government/departments/finance/purchasing/", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "CITY", "Norfolk", "https://www.norfolk.gov/149/Purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "CITY", "Chesapeake", "https://www.cityofchesapeake.net/government/city-departments/departments/finance-department/purchasing.htm", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "CITY", "Richmond", "https://www.rva.gov/procurement-services", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "CITY", "Newport News", "https://www.nnva.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "CITY", "Alexandria", "https://www.alexandriava.gov/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "CITY", "Hampton", "https://www.hampton.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "CITY", "Roanoke", "https://www.roanokeva.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    # --- Illinois ---
    ("IL", "COUNTY", "Cook", "https://www.cookcountyil.gov/agency/office-chief-procurement-officer", "BidNet", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "COUNTY", "DuPage", "https://www.dupagecounty.gov/government/departments/finance/purchasing.php", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "COUNTY", "Lake", "https://www.lakecountyil.gov/195/Purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "COUNTY", "Will", "https://www.willcountyillinois.com/County-Offices/Finance/Purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "COUNTY", "Kane", "https://www.countyofkane.org/Pages/Purchasing.aspx", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "COUNTY", "McHenry", "https://www.mchenrycountyil.gov/county-government/departments-a-i/finance/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "COUNTY", "Winnebago", "https://wincoil.gov/departments/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "COUNTY", "Madison", "https://www.madisoncountyil.gov/departments/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "COUNTY", "St. Clair", "https://www.stclaircountyil.gov/departments/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "COUNTY", "Champaign", "https://www.co.champaign.il.us/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "CITY", "Chicago", "https://www.chicago.gov/city/en/depts/dps.html", "BidNet", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "CITY", "Aurora", "https://www.aurora-il.org/149/Purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "CITY", "Naperville", "https://www.naperville.il.us/government/departments/finance/purchasing/", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "CITY", "Joliet", "https://www.joliet.gov/government/departments/finance/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "CITY", "Rockford", "https://www.rockfordil.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "CITY", "Springfield", "https://www.springfield.il.us/Departments/Purchasing.aspx", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "CITY", "Peoria", "https://www.peoriagov.org/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "CITY", "Elgin", "https://www.cityofelgin.org/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    # --- Missouri / Kansas / Kentucky / Iowa ---
    ("MO", "COUNTY", "St. Louis", "https://stlouiscountymo.gov/st-louis-county-departments/administration/procurement/", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MO", "COUNTY", "Jackson", "https://www.jacksongov.org/154/Purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MO", "COUNTY", "St. Charles", "https://www.sccmo.org/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MO", "COUNTY", "Greene", "https://greenecountymo.gov/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MO", "COUNTY", "Clay", "https://www.claycountymo.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MO", "COUNTY", "Jefferson", "https://www.jeffcomo.org/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MO", "CITY", "Kansas City", "https://www.kcmo.gov/city-hall/departments/finance/purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MO", "CITY", "St. Louis", "https://www.stlouis-mo.gov/government/departments/supply/", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MO", "CITY", "Springfield", "https://www.springfieldmo.gov/149/Purchasing", "IonWave", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MO", "CITY", "Columbia", "https://www.como.gov/finance/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KS", "COUNTY", "Johnson", "https://www.jocogov.org/department/treasury-and-financial-management/purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KS", "COUNTY", "Sedgwick", "https://www.sedgwickcounty.org/purchasing/", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KS", "COUNTY", "Shawnee", "https://www.snco.us/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KS", "COUNTY", "Wyandotte", "https://www.wycokck.org/Departments/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KS", "CITY", "Wichita", "https://www.wichita.gov/165/Purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KS", "CITY", "Overland Park", "https://www.opkansas.org/city-government/finance/purchasing/", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KS", "CITY", "Kansas City", "https://www.wycokck.org/Departments/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KS", "CITY", "Topeka", "https://www.topeka.org/purchasing/", "IonWave", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KS", "CITY", "Olathe", "https://www.olatheks.org/government/finance/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KS", "CITY", "Lawrence", "https://lawrenceks.org/purchasing/", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KY", "COUNTY", "Jefferson", "https://louisvilleky.gov/government/purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KY", "COUNTY", "Fayette", "https://www.lexingtonky.gov/purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KY", "COUNTY", "Kenton", "https://www.kentoncounty.org/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KY", "COUNTY", "Boone", "https://www.boonecountyky.org/departments/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KY", "CITY", "Louisville", "https://louisvilleky.gov/government/purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KY", "CITY", "Lexington", "https://www.lexingtonky.gov/purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KY", "CITY", "Bowling Green", "https://www.bgky.org/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KY", "CITY", "Owensboro", "https://www.owensboro.org/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "COUNTY", "Polk", "https://www.polkcountyiowa.gov/purchasing/", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "COUNTY", "Linn", "https://www.linncountyiowa.gov/149/Purchasing", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "COUNTY", "Scott", "https://www.scottcountyiowa.gov/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "COUNTY", "Johnson", "https://www.johnsoncountyiowa.gov/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "COUNTY", "Black Hawk", "https://www.blackhawkcounty.iowa.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "CITY", "Des Moines", "https://www.dsm.city/departments/finance___management/purchasing.php", "OpenGov", PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "CITY", "Cedar Rapids", "https://www.cedar-rapids.org/local_government/departments_a_-_f/finance/purchasing.php", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "CITY", "Davenport", "https://www.davenportiowa.com/government/departments/finance/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "CITY", "Sioux City", "https://www.sioux-city.org/government/departments-a-h/finance/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "CITY", "Iowa City", "https://www.icgov.org/city-government/departments-and-divisions/finance/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "CITY", "Waterloo", "https://www.waterloo-ia.org/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "CITY", "Ames", "https://www.cityofames.org/government/departments-divisions-a-h/finance/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "CITY", "West Des Moines", "https://www.wdm.iowa.gov/government/finance/purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "CITY", "Ankeny", "https://www.ankenyiowa.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "CITY", "Council Bluffs", "https://www.councilbluffs-ia.gov/149/Purchasing", None, PORTAL_DISCOVERED_NOT_INTEGRATED),
]


def county_city_portal_catalog() -> list[dict[str, Any]]:
    out = []
    for st, bt, name, url, plat, status in COUNTY_CITY_PORTALS:
        out.append(
            {
                "state": st,
                "buyer_type": bt,
                "name": name,
                "portal_url": url,
                "platform": plat,
                "source_status": status,
                "catalog": "county_city_portal_catalog",
                "auth_required": False,
            }
        )
    return out


# States to probe unresolved counties first
PRIORITY_COUNTY_STATES = ("TX", "GA", "VA", "KY", "MO", "KS", "IL", "IA")
