"""Curated public platform buyer directories for L.17.2 enumeration + registry crosswalk.

One adapter / platform family → many buyers. Entries use known public portal URLs.
Membership is explicit — never invent buyer→platform links without a portal URL.
"""

from __future__ import annotations

from typing import Any

from discovery.constants import (
    PLATFORM_BIDNET,
    PLATFORM_BONFIRE,
    PLATFORM_IONWAVE,
    PLATFORM_JAGGAER,
    PLATFORM_OPENGOV,
    PLATFORM_PLANETBIDS,
    PLATFORM_PUBLIC_PURCHASE,
)
from discovery.lower48 import (
    FREE_REGISTRATION_REQUIRED,
    PORTAL_DISCOVERED_NOT_INTEGRATED,
)

# (state, buyer_type, name_hint, platform, url, auth_required, status_hint)
_RAW: list[tuple[str, str, str, str, str, bool, str]] = [
    # --- OpenGov portals ---
    ("TX", "CITY", "San Antonio", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/sanantonio", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("NC", "CITY", "Raleigh", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/raleigh", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "CITY", "Sacramento", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/sacramento", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("NC", "COUNTY", "Wake", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/wakegov", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("WA", "CITY", "Seattle", PLATFORM_OPENGOV, "https://www.seattle.gov/purchasing-and-contracting/current-solicitations", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MA", "CITY", "Boston", PLATFORM_OPENGOV, "https://www.boston.gov/bid-listings", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("AZ", "CITY", "Phoenix", PLATFORM_OPENGOV, "https://solicitations.phoenix.gov/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Fort Worth", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/fortworth", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Plano", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/plano", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Arlington", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/arlingtontexas", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "CITY", "Fresno", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/fresno", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "CITY", "Oakland", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/oakland", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "CITY", "Stockton", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/stockton", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("FL", "CITY", "Orlando", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/orlando", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("FL", "CITY", "Tampa", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/tampa", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("FL", "COUNTY", "Orange", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/orangecountyfl", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("FL", "COUNTY", "Hillsborough", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/hillsboroughcounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CO", "CITY", "Colorado Springs", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/coloradosprings", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CO", "CITY", "Aurora", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/auroraco", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CO", "COUNTY", "Arapahoe", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/arapahoecounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CO", "COUNTY", "Jefferson", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/jeffco", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "CITY", "Savannah", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/savannah", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "COUNTY", "Cobb", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/cobbcounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "COUNTY", "Gwinnett", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/gwinnett", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "COUNTY", "DeKalb", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/dekalbcountyga", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "COUNTY", "Fulton", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/fultoncountyga", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "CITY", "Aurora", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/auroraillinois", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "CITY", "Naperville", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/naperville", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "COUNTY", "DuPage", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/dupagecounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "COUNTY", "Lake", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/lakecountyil", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IL", "COUNTY", "Will", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/willcounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IN", "CITY", "Indianapolis", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/indy", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IN", "COUNTY", "Marion", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/marioncountyin", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MI", "CITY", "Grand Rapids", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/grandrapids", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MI", "COUNTY", "Oakland", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/oaklandcountymi", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MI", "COUNTY", "Wayne", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/waynecountymi", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MN", "COUNTY", "Hennepin", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/hennepin", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MN", "COUNTY", "Ramsey", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/ramseycounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MO", "CITY", "Kansas City", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/kcmo", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MO", "CITY", "St. Louis", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/stlouis", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MO", "COUNTY", "St. Louis", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/stlouiscounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MO", "COUNTY", "Jackson", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/jacksoncountymo", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("NJ", "CITY", "Jersey City", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/jerseycity", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("NJ", "COUNTY", "Bergen", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/bergencounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("NJ", "COUNTY", "Essex", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/essexcountynj", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("NV", "CITY", "Las Vegas", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/lasvegas", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("NV", "COUNTY", "Clark", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/clarkcountynv", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("NY", "COUNTY", "Westchester", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/westchestergov", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("NY", "COUNTY", "Suffolk", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/suffolkcountyny", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("NY", "COUNTY", "Nassau", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/nassaucountyny", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("OH", "CITY", "Cincinnati", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/cincinnati", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("OH", "CITY", "Cleveland", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/cleveland", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("OH", "COUNTY", "Franklin", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/franklincountyohio", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("OH", "COUNTY", "Cuyahoga", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/cuyahoga", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("OH", "COUNTY", "Hamilton", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/hamiltoncountyohio", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("OR", "COUNTY", "Multnomah", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/multnomahcounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("OR", "COUNTY", "Washington", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/washingtoncountyoregon", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("PA", "CITY", "Pittsburgh", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/pittsburgh", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("PA", "COUNTY", "Allegheny", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/alleghenycounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("PA", "COUNTY", "Montgomery", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/montcopa", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TN", "CITY", "Nashville", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/nashville", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TN", "CITY", "Memphis", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/memphis", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TN", "COUNTY", "Davidson", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/davidsoncounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TN", "COUNTY", "Shelby", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/shelbycountytn", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("UT", "CITY", "Salt Lake City", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/slcgov", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("UT", "COUNTY", "Salt Lake", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/saltlakecounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "CITY", "Virginia Beach", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/vbgov", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "CITY", "Norfolk", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/norfolk", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "CITY", "Chesapeake", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/chesapeake", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "COUNTY", "Fairfax", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/fairfaxcounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "COUNTY", "Prince William", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/pwcgov", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "COUNTY", "Loudoun", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/loudoun", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "COUNTY", "Chesterfield", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/chesterfield", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("VA", "COUNTY", "Henrico", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/henrico", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("WA", "COUNTY", "King", PLATFORM_OPENGOV, "https://kingcounty.gov/en/dept/kcf/business/procurement-payment", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("WA", "COUNTY", "Pierce", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/piercecounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("WA", "COUNTY", "Snohomish", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/snohomishcounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("WI", "COUNTY", "Milwaukee", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/milwaukeecounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("WI", "COUNTY", "Dane", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/danecounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MD", "COUNTY", "Prince George's", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/pgc", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MD", "COUNTY", "Baltimore", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/baltimorecounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MD", "COUNTY", "Anne Arundel", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/aacounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MD", "COUNTY", "Howard", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/howardcountymd", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MD", "CITY", "Baltimore", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/baltimorecity", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("SC", "CITY", "Charleston", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/charleston", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("SC", "COUNTY", "Charleston", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/charlestoncounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("SC", "COUNTY", "Greenville", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/greenvillecounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("SC", "COUNTY", "Richland", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/richlandcountysc", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KY", "CITY", "Louisville", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/louisville", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KY", "CITY", "Lexington", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/lexingtonky", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KY", "COUNTY", "Jefferson", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/jeffersoncountyky", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KY", "COUNTY", "Fayette", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/fayettecountyky", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "CITY", "Des Moines", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/desmoines", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "COUNTY", "Polk", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/polkcountyiowa", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("IA", "COUNTY", "Linn", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/linncounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KS", "CITY", "Wichita", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/wichita", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KS", "CITY", "Overland Park", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/opkansas", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KS", "COUNTY", "Johnson", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/jocogov", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KS", "COUNTY", "Sedgwick", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/sedgwickcounty", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("NE", "CITY", "Omaha", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/cityofomaha", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("NE", "CITY", "Lincoln", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/lincoln", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("NE", "COUNTY", "Douglas", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/douglascountyne", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("NE", "COUNTY", "Lancaster", PLATFORM_OPENGOV, "https://procurement.opengov.com/portal/lancasterne", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    # --- Bonfire ---
    ("TX", "CITY", "Houston", PLATFORM_BONFIRE, "https://purchasing.houstontx.gov/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Harris", PLATFORM_BONFIRE, "https://www.harriscountytx.gov/Purchasing", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "SCHOOL_DISTRICT", "Houston Independent School District", PLATFORM_BONFIRE, "https://houstonisd.bonfirehub.com/portal/?tab=openOpportunities", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CO", "CITY", "Denver", PLATFORM_BONFIRE, "https://denver.bonfirehub.com/portal/?tab=openOpportunities", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("AZ", "COUNTY", "Maricopa", PLATFORM_BONFIRE, "https://www.maricopa.gov/3978/Procurement", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("GA", "CITY", "Atlanta", PLATFORM_BONFIRE, "https://www.atlantaga.gov/government/departments/procurement", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Dallas", PLATFORM_BONFIRE, "https://dallascityhall.bonfirehub.com/portal/?tab=openOpportunities", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Dallas", PLATFORM_BONFIRE, "https://www.dallascounty.org/departments/purchasing/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Tarrant", PLATFORM_BONFIRE, "https://www.tarrantcounty.com/en/purchasing.html", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Bexar", PLATFORM_BONFIRE, "https://www.bexar.org/1480/Purchasing", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Travis", PLATFORM_BONFIRE, "https://www.traviscountytx.gov/purchasing", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Collin", PLATFORM_BONFIRE, "https://www.collincountytx.gov/Purchasing", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Denton", PLATFORM_BONFIRE, "https://www.dentoncounty.gov/Departments/Purchasing", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Fort Bend", PLATFORM_BONFIRE, "https://www.fortbendcountytx.gov/government/departments/purchasing", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Williamson", PLATFORM_BONFIRE, "https://www.wilco.org/Departments/Purchasing", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Hidalgo", PLATFORM_BONFIRE, "https://www.hidalgocounty.us/256/Purchasing", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "El Paso", PLATFORM_BONFIRE, "https://www.epcounty.com/purchasing/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Montgomery", PLATFORM_BONFIRE, "https://www.mctx.org/departments_offices/departments/purchasing/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Cameron", PLATFORM_BONFIRE, "https://www.cameroncountytx.gov/purchasing/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Brazoria", PLATFORM_BONFIRE, "https://www.brazoriacountytx.gov/departments/purchasing", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Galveston", PLATFORM_BONFIRE, "https://www.galvestoncountytx.gov/our-county/purchasing", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Nueces", PLATFORM_BONFIRE, "https://www.nuecesco.com/county-services/purchasing", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Bell", PLATFORM_BONFIRE, "https://www.bellcountytx.com/county_offices/purchasing/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "McLennan", PLATFORM_BONFIRE, "https://www.co.mclennan.tx.us/161/Purchasing", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Lubbock", PLATFORM_BONFIRE, "https://www.lubbockcounty.gov/departments/purchasing", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Webb", PLATFORM_BONFIRE, "https://www.webbcountytx.gov/Purchasing/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Jefferson", PLATFORM_BONFIRE, "https://co.jefferson.tx.us/Purchasing/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "COUNTY", "Smith", PLATFORM_BONFIRE, "https://www.smith-county.com/government/departments/purchasing", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "AIRPORT", "Dallas Fort Worth International Airport", PLATFORM_BONFIRE, "https://www.dfwairport.com/business/solicitations/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "PUBLIC_UNIVERSITY", "University of Texas at Austin", PLATFORM_BONFIRE, "https://procurement.utexas.edu/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    # --- PlanetBids ---
    ("CA", "CITY", "Los Angeles", PLATFORM_PLANETBIDS, "https://www.labavn.org/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "CITY", "San Diego", PLATFORM_PLANETBIDS, "https://pbsystem.planetbids.com/portal/15820/portal-home", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "CITY", "Long Beach", PLATFORM_PLANETBIDS, "https://pbsystem.planetbids.com/portal/13784/portal-home", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "CITY", "Anaheim", PLATFORM_PLANETBIDS, "https://pbsystem.planetbids.com/portal/14972/portal-home", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "CITY", "Santa Ana", PLATFORM_PLANETBIDS, "https://pbsystem.planetbids.com/portal/15566/portal-home", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "CITY", "Riverside", PLATFORM_PLANETBIDS, "https://pbsystem.planetbids.com/portal/14897/portal-home", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "CITY", "Irvine", PLATFORM_PLANETBIDS, "https://pbsystem.planetbids.com/portal/14555/portal-home", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "COUNTY", "Los Angeles", PLATFORM_PLANETBIDS, "https://lacounty.planetbids.com/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "COUNTY", "Orange", PLATFORM_PLANETBIDS, "https://ocgov.planetbids.com/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "COUNTY", "San Diego", PLATFORM_PLANETBIDS, "https://sandiegocounty.planetbids.com/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "COUNTY", "Riverside", PLATFORM_PLANETBIDS, "https://rivco.planetbids.com/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "COUNTY", "San Bernardino", PLATFORM_PLANETBIDS, "https://sbcounty.planetbids.com/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "COUNTY", "Alameda", PLATFORM_PLANETBIDS, "https://alamedacounty.planetbids.com/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "COUNTY", "Sacramento", PLATFORM_PLANETBIDS, "https://saccounty.planetbids.com/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "COUNTY", "Contra Costa", PLATFORM_PLANETBIDS, "https://contracosta.planetbids.com/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "COUNTY", "Fresno", PLATFORM_PLANETBIDS, "https://fresnocounty.planetbids.com/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "COUNTY", "Kern", PLATFORM_PLANETBIDS, "https://kerncounty.planetbids.com/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "COUNTY", "Ventura", PLATFORM_PLANETBIDS, "https://venturacounty.planetbids.com/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "SCHOOL_DISTRICT", "Los Angeles Unified School District", PLATFORM_PLANETBIDS, "https://www.lausd.org/procurement", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "AIRPORT", "Los Angeles World Airports", PLATFORM_PLANETBIDS, "https://pbsystem.planetbids.com/portal/15424/portal-home", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("CA", "PUBLIC_UTILITY", "Los Angeles Department of Water and Power", PLATFORM_PLANETBIDS, "https://www.ladwp.com/ladwp/faces/ladwp/aboutus/a-procurement", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    # --- IonWave ---
    ("OK", "CITY", "Tulsa", PLATFORM_IONWAVE, "https://tulsaok.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("OK", "CITY", "Oklahoma City", PLATFORM_IONWAVE, "https://okc.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("OK", "CITY", "Norman", PLATFORM_IONWAVE, "https://normanok.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("OK", "COUNTY", "Tulsa", PLATFORM_IONWAVE, "https://tulsacounty.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("OK", "COUNTY", "Oklahoma", PLATFORM_IONWAVE, "https://oklahomacounty.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("OK", "COUNTY", "Cleveland", PLATFORM_IONWAVE, "https://clevelandcountyok.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("AR", "CITY", "Little Rock", PLATFORM_IONWAVE, "https://littlerock.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("AR", "COUNTY", "Pulaski", PLATFORM_IONWAVE, "https://pulaskicounty.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("KS", "CITY", "Topeka", PLATFORM_IONWAVE, "https://topeka.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("MO", "CITY", "Springfield", PLATFORM_IONWAVE, "https://springfieldmo.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Amarillo", PLATFORM_IONWAVE, "https://amarillo.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Lubbock", PLATFORM_IONWAVE, "https://lubbock.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Waco", PLATFORM_IONWAVE, "https://waco.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Beaumont", PLATFORM_IONWAVE, "https://beaumont.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Abilene", PLATFORM_IONWAVE, "https://abilene.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Odessa", PLATFORM_IONWAVE, "https://odessa.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Midland", PLATFORM_IONWAVE, "https://midland.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Tyler", PLATFORM_IONWAVE, "https://tyler.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "College Station", PLATFORM_IONWAVE, "https://cstx.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("TX", "CITY", "Bryan", PLATFORM_IONWAVE, "https://bryantx.ionwave.net/PublicPortal.aspx", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    # --- Jaggaer / SciQuest public events ---
    ("TX", "PUBLIC_UNIVERSITY", "Texas A&M", PLATFORM_JAGGAER, "https://bids.sciquest.com/apps/Router/PublicEvent?CustomerOrg=TAMU", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    ("AL", "STATE", "Alabama", PLATFORM_JAGGAER, "https://www.alabamabuys.gov/", True, FREE_REGISTRATION_REQUIRED),
    ("DE", "STATE", "Delaware", PLATFORM_JAGGAER, "https://mymarketplace.delaware.gov/", False, PORTAL_DISCOVERED_NOT_INTEGRATED),
    # --- Public Purchase / DemandStar (map only; auth often required) ---
    ("WY", "CITY", "Cheyenne", PLATFORM_PUBLIC_PURCHASE, "https://www.publicpurchase.com/gems/cheyenne/buyer/public/home", True, FREE_REGISTRATION_REQUIRED),
    ("US", "MULTI_AGENCY_NETWORK", "Public Purchase Network", PLATFORM_PUBLIC_PURCHASE, "https://www.publicpurchase.com/gems/browse/home", True, FREE_REGISTRATION_REQUIRED),
    ("FL", "MULTI_AGENCY_NETWORK", "DemandStar", "DemandStar", "https://www.demandstar.com/app/agencies", True, FREE_REGISTRATION_REQUIRED),
    # --- BidNet statewide networks (network-level; individual buyers still need confirmation) ---
    ("TX", "MULTI_AGENCY_NETWORK", "BidNet Direct Texas", PLATFORM_BIDNET, "https://www.bidnetdirect.com/texas/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("GA", "MULTI_AGENCY_NETWORK", "BidNet Direct Georgia", PLATFORM_BIDNET, "https://www.bidnetdirect.com/georgia/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("VA", "MULTI_AGENCY_NETWORK", "BidNet Direct Virginia", PLATFORM_BIDNET, "https://www.bidnetdirect.com/virginia/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("IL", "MULTI_AGENCY_NETWORK", "BidNet Direct Illinois", PLATFORM_BIDNET, "https://www.bidnetdirect.com/illinois/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("FL", "MULTI_AGENCY_NETWORK", "BidNet Direct Florida", PLATFORM_BIDNET, "https://www.bidnetdirect.com/florida/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("CA", "MULTI_AGENCY_NETWORK", "BidNet Direct California", PLATFORM_BIDNET, "https://www.bidnetdirect.com/california/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("NY", "MULTI_AGENCY_NETWORK", "BidNet Direct New York", PLATFORM_BIDNET, "https://www.bidnetdirect.com/new-york/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("OH", "MULTI_AGENCY_NETWORK", "BidNet Direct Ohio", PLATFORM_BIDNET, "https://www.bidnetdirect.com/ohio/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("NC", "MULTI_AGENCY_NETWORK", "BidNet Direct North Carolina", PLATFORM_BIDNET, "https://www.bidnetdirect.com/north-carolina/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("PA", "MULTI_AGENCY_NETWORK", "BidNet Direct Pennsylvania", PLATFORM_BIDNET, "https://www.bidnetdirect.com/pennsylvania/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("MO", "MULTI_AGENCY_NETWORK", "BidNet Direct Missouri", PLATFORM_BIDNET, "https://www.bidnetdirect.com/missouri/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("KY", "MULTI_AGENCY_NETWORK", "BidNet Direct Kentucky", PLATFORM_BIDNET, "https://www.bidnetdirect.com/kentucky/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("KS", "MULTI_AGENCY_NETWORK", "BidNet Direct Kansas", PLATFORM_BIDNET, "https://www.bidnetdirect.com/kansas/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("IA", "MULTI_AGENCY_NETWORK", "BidNet Direct Iowa", PLATFORM_BIDNET, "https://www.bidnetdirect.com/iowa/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("WA", "MULTI_AGENCY_NETWORK", "BidNet Direct Washington", PLATFORM_BIDNET, "https://www.bidnetdirect.com/washington/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("OR", "MULTI_AGENCY_NETWORK", "BidNet Direct Oregon", PLATFORM_BIDNET, "https://www.bidnetdirect.com/oregon/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("MN", "MULTI_AGENCY_NETWORK", "BidNet Direct Minnesota", PLATFORM_BIDNET, "https://www.bidnetdirect.com/minnesota/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("WI", "MULTI_AGENCY_NETWORK", "BidNet Direct Wisconsin", PLATFORM_BIDNET, "https://www.bidnetdirect.com/wisconsin/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("MI", "MULTI_AGENCY_NETWORK", "BidNet Direct Michigan", PLATFORM_BIDNET, "https://www.bidnetdirect.com/michigan/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("AZ", "MULTI_AGENCY_NETWORK", "BidNet Direct Arizona", PLATFORM_BIDNET, "https://www.bidnetdirect.com/arizona/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("CO", "MULTI_AGENCY_NETWORK", "BidNet Direct Colorado", PLATFORM_BIDNET, "https://www.bidnetdirect.com/colorado/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
    ("NM", "MULTI_AGENCY_NETWORK", "BidNet Direct New Mexico", PLATFORM_BIDNET, "https://www.bidnetdirect.com/new-mexico/solicitations/open-bids", True, FREE_REGISTRATION_REQUIRED),
]


def platform_buyer_catalog() -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for st, bt, name, plat, url, auth, status in _RAW:
        out.append(
            {
                "state": st,
                "buyer_type": bt,
                "name": name,
                "platform": plat,
                "portal_url": url,
                "auth_required": auth,
                "source_status": status,
                "catalog": "platform_buyer_catalog",
                "registration_free": auth and plat in {PLATFORM_BIDNET, PLATFORM_PUBLIC_PURCHASE, "DemandStar"},
            }
        )
    return out


def platform_catalog_by_family() -> dict[str, list[dict[str, Any]]]:
    by: dict[str, list[dict[str, Any]]] = {}
    for row in platform_buyer_catalog():
        by.setdefault(str(row["platform"]), []).append(row)
    return by
