"""Build: 20261005-m3-bidnet-full-production-v1"""

from __future__ import annotations

BUILD = "20261006-m3-bidnet-discovery-complete-v2"

CORPUS = "LARGE_TEST_CORPUS_V1.json"
ACCEPTANCE_SAMPLE = 192

CK = "m3_bidnet_full_production_v1_checkpoint.json"
JOB = "m3_bidnet_full_production_v1_job.json"
REPORT = "m3_bidnet_full_production_v1_last_report.json"
REPORT_TXT = "m3_bidnet_full_production_v1_last_report.txt"
PROGRESS = "m3_bidnet_full_production_v1_progress.json"
RESULTS = "m3_bidnet_full_production_v1_results.json"
UI = "m3_bidnet_full_production_v1_ui.json"
ARCHITECTURE = "m3_bidnet_full_production_architecture_audit.json"
BUYER_DIRECTORY = "BIDNET_BUYER_DIRECTORY.json"
CHECKPOINT_EVERY = 5

# Auth page classification (Phase 4)
AUTHENTICATED_VALID = "AUTHENTICATED_VALID"
SESSION_EXPIRED = "SESSION_EXPIRED"
LOGIN_REQUIRED = "LOGIN_REQUIRED"
REGISTRATION_REDIRECT = "REGISTRATION_REDIRECT"
PACKAGE_LOCKED = "PACKAGE_LOCKED"
ACCESS_DENIED = "ACCESS_DENIED"
PUBLIC_PAGE = "PUBLIC_PAGE"
AUTH_UNKNOWN = "UNKNOWN"

# Detail states (Phase 8)
DETAIL_OK = "DETAIL_OK"
DETAIL_PARTIAL = "DETAIL_PARTIAL"
DETAIL_LOCKED = "DETAIL_LOCKED"
DETAIL_REGISTRATION_REDIRECT = "DETAIL_REGISTRATION_REDIRECT"
DETAIL_FAILED_RETRYABLE = "DETAIL_FAILED_RETRYABLE"
DETAIL_FAILED_TERMINAL = "DETAIL_FAILED_TERMINAL"

# Package access (Phase 14)
PACKAGE_ACQUIRED_BIDNET = "PACKAGE_ACQUIRED_BIDNET"
PACKAGE_ACQUIRED_OFFICIAL_SOURCE = "PACKAGE_ACQUIRED_OFFICIAL_SOURCE"
PACKAGE_LOCKED_MEMBERSHIP = "PACKAGE_LOCKED_MEMBERSHIP"
PACKAGE_EXTERNAL_PORTAL_REQUIRED = "PACKAGE_EXTERNAL_PORTAL_REQUIRED"
PACKAGE_REGISTRATION_REQUIRED = "PACKAGE_REGISTRATION_REQUIRED"
PACKAGE_NOT_POSTED = "PACKAGE_NOT_POSTED"
PACKAGE_RETRYABLE = "PACKAGE_RETRYABLE"
PACKAGE_TERMINAL_OTHER = "PACKAGE_TERMINAL_OTHER"

BUYER_HIGH = "HIGH"
BUYER_MEDIUM = "MEDIUM"
BUYER_LOW = "LOW"
BUYER_UNRESOLVED = "UNRESOLVED"

PACKAGE_TERMINAL_STATES = {
    PACKAGE_ACQUIRED_BIDNET,
    PACKAGE_ACQUIRED_OFFICIAL_SOURCE,
    PACKAGE_LOCKED_MEMBERSHIP,
    PACKAGE_EXTERNAL_PORTAL_REQUIRED,
    PACKAGE_REGISTRATION_REQUIRED,
    PACKAGE_NOT_POSTED,
    PACKAGE_TERMINAL_OTHER,
}
