"""Execution requirement vocabulary (Phase D)."""

from __future__ import annotations

BUILD_TAG = "20260922-m3-execution-compliance-1"

# Operational requirement statuses — UNKNOWN never silently becomes satisfied
ST_CONFIRMED = "CONFIRMED"
ST_REQUIRES_ACTION = "REQUIRES_ACTION"
ST_REQUIRES_SUPPLIER = "REQUIRES_SUPPLIER_CONFIRMATION"
ST_REQUIRES_OWNER = "REQUIRES_OWNER_DECISION"
ST_BLOCKED = "BLOCKED"
ST_UNKNOWN = "UNKNOWN"
ST_NOT_APPLICABLE = "NOT_APPLICABLE"

REQUIREMENT_STATUSES: tuple[str, ...] = (
    ST_CONFIRMED,
    ST_REQUIRES_ACTION,
    ST_REQUIRES_SUPPLIER,
    ST_REQUIRES_OWNER,
    ST_BLOCKED,
    ST_UNKNOWN,
    ST_NOT_APPLICABLE,
)

CATEGORIES: tuple[str, ...] = (
    "SUBMISSION",
    "PRODUCT",
    "QUANTITY_UOM",
    "PACKAGING",
    "MARKING",
    "LABELING",
    "DELIVERY",
    "SHIPPING",
    "FOB",
    "INSPECTION",
    "ACCEPTANCE",
    "QUALITY",
    "TRACEABILITY",
    "WARRANTY",
    "COUNTRY_OF_ORIGIN",
    "CERTIFICATION",
    "TECHNICAL_DATA",
    "SUPPLIER_CONFIRMATION",
    "POST_AWARD",
    "INVOICE",
    "PAYMENT",
    "REPORTING",
    "OTHER",
)

# Clause relevance classes
CLAUSE_EXECUTION = "EXECUTION_RELEVANT"
CLAUSE_FINANCIAL = "FINANCIAL_RELEVANT"
CLAUSE_ELIGIBILITY = "ELIGIBILITY_RELEVANT"
CLAUSE_INFO = "INFORMATIONAL"
CLAUSE_UNKNOWN = "UNKNOWN"

CLAUSE_RELEVANCE: tuple[str, ...] = (
    CLAUSE_EXECUTION,
    CLAUSE_FINANCIAL,
    CLAUSE_ELIGIBILITY,
    CLAUSE_INFO,
    CLAUSE_UNKNOWN,
)

# Payment-state separation (never collapse)
PAY_SHIPPED = "SHIPPED"
PAY_DELIVERED = "DELIVERED"
PAY_ACCEPTED = "ACCEPTED"
PAY_INVOICED = "INVOICED"
PAY_PAID = "PAID"

PAYMENT_STATES: tuple[str, ...] = (
    PAY_SHIPPED,
    PAY_DELIVERED,
    PAY_ACCEPTED,
    PAY_INVOICED,
    PAY_PAID,
)

ACTOR_VA = "VA"
ACTOR_OWNER = "OWNER"
ACTOR_SUPPLIER = "SUPPLIER"
ACTOR_SYSTEM = "SYSTEM"

CONFLICT_FLAG = "REQUIREMENT_CONFLICT"

# Map legacy bid_requirement / DLA categories → Phase D categories
CATEGORY_ALIASES: dict[str, str] = {
    "QUANTITY": "QUANTITY_UOM",
    "TECHNICAL_SPECIFICATION": "PRODUCT",
    "BRAND_OR_EQUAL": "PRODUCT",
    "EXACT_BRAND_REQUIRED": "PRODUCT",
    "OEM_REQUIREMENT": "PRODUCT",
    "BUY_AMERICAN": "COUNTRY_OF_ORIGIN",
    "TRADE_AGREEMENTS": "COUNTRY_OF_ORIGIN",
    "DOMESTIC_CONTENT": "COUNTRY_OF_ORIGIN",
    "DELIVERY_DATE": "DELIVERY",
    "DELIVERY_LOCATION": "DELIVERY",
    "FREIGHT": "SHIPPING",
    "LABELING": "LABELING",
    "SERIAL_NUMBER": "TRACEABILITY",
    "LOT_OR_BATCH": "TRACEABILITY",
    "SUBSTITUTION": "PRODUCT",
    "CERTIFICATION_FORM": "CERTIFICATION",
    "PAYMENT_TERMS": "PAYMENT",
    "SUBMISSION_METHOD": "SUBMISSION",
    "SUBMISSION_EMAIL": "SUBMISSION",
    "SUBMISSION_PORTAL": "SUBMISSION",
    "FILE_FORMAT": "SUBMISSION",
    "BID_DEADLINE": "SUBMISSION",
    "AMENDMENT_ACKNOWLEDGEMENT": "SUBMISSION",
    "SIGNATURE": "SUBMISSION",
    "PRICING_FORM": "SUBMISSION",
    "CERTIFICATIONS": "CERTIFICATION",
}

# Categories that can block owner approval when mandatory + unresolved
EXECUTION_CRITICAL_CATEGORIES: frozenset[str] = frozenset(
    {
        "SUBMISSION",
        "PRODUCT",
        "QUANTITY_UOM",
        "PACKAGING",
        "DELIVERY",
        "FOB",
        "INSPECTION",
        "ACCEPTANCE",
        "COUNTRY_OF_ORIGIN",
        "SUPPLIER_CONFIRMATION",
        "CERTIFICATION",
    }
)
