"""Operator-facing workflow states and ranks (projection only)."""

from __future__ import annotations

# Operator workflow ladder (Phase A) — least advanced → most advanced
OW_DISCOVERED = "DISCOVERED"
OW_QUALIFIED = "QUALIFIED"
OW_DEEP_RESEARCH = "DEEP_RESEARCH"
OW_SUPPLIER_VALIDATION = "SUPPLIER_VALIDATION"
OW_FINANCE_REVIEW = "FINANCE_REVIEW"
OW_BID_PREPARATION = "BID_PREPARATION"
OW_SUBMITTED = "SUBMITTED"
OW_AWARDED = "AWARDED"
OW_ORDERING = "ORDERING"
OW_DELIVERED = "DELIVERED"
OW_PAID = "PAID"
OW_HISTORY = "HISTORY"

OPERATOR_STATES: tuple[str, ...] = (
    OW_DISCOVERED,
    OW_QUALIFIED,
    OW_DEEP_RESEARCH,
    OW_SUPPLIER_VALIDATION,
    OW_FINANCE_REVIEW,
    OW_BID_PREPARATION,
    OW_SUBMITTED,
    OW_AWARDED,
    OW_ORDERING,
    OW_DELIVERED,
    OW_PAID,
    OW_HISTORY,
)

# Lower rank = less advanced (conservative picks minimum)
STATE_RANK: dict[str, int] = {
    OW_DISCOVERED: 0,
    OW_QUALIFIED: 1,
    OW_DEEP_RESEARCH: 2,
    OW_SUPPLIER_VALIDATION: 3,
    OW_FINANCE_REVIEW: 4,
    OW_BID_PREPARATION: 5,
    OW_SUBMITTED: 6,
    OW_AWARDED: 7,
    OW_ORDERING: 8,
    OW_DELIVERED: 9,
    OW_PAID: 10,
    OW_HISTORY: 11,
}

# Confidence of the projection itself (not AI model confidence)
CONFIDENCE_HIGH = "HIGH"
CONFIDENCE_MEDIUM = "MEDIUM"
CONFIDENCE_LOW = "LOW"
CONFIDENCE_UNKNOWN = "UNKNOWN"

BUILD_TAG = "20260922-m3-operator-workflow-projection-1"

# Cap ranks: pre-award evidence gates (cannot exceed without evidence)
RANK_PRE_AWARD_MAX = STATE_RANK[OW_BID_PREPARATION]
RANK_BID_PREP = STATE_RANK[OW_BID_PREPARATION]
RANK_SUPPLIER = STATE_RANK[OW_SUPPLIER_VALIDATION]
RANK_FINANCE = STATE_RANK[OW_FINANCE_REVIEW]
RANK_DEEP = STATE_RANK[OW_DEEP_RESEARCH]
RANK_SUBMITTED = STATE_RANK[OW_SUBMITTED]
