"""Statuses and thresholds for scale-evidence-to-profit."""

from __future__ import annotations

BUILD = "20261003-m3-scale-evidence-to-profit-v1"

# Line statuses
BOTH_SIDES_READY = "BOTH_SIDES_READY"
GOV_ONLY = "GOV_ONLY"
COST_ONLY = "COST_ONLY"
INSUFFICIENT_IDENTITY = "INSUFFICIENT_IDENTITY"
NO_HISTORY_AFTER_EXHAUSTIVE_SEARCH = "NO_HISTORY_AFTER_EXHAUSTIVE_SEARCH"
NO_PUBLIC_PRICE_AFTER_EXHAUSTIVE_SEARCH = "NO_PUBLIC_PRICE_AFTER_EXHAUSTIVE_SEARCH"
UOM_BLOCKED = "UOM_BLOCKED"
RETRYABLE = "RETRYABLE"

# Opportunity both-sides classes
OPPORTUNITY_BOTH_SIDES_NONE = "OPPORTUNITY_BOTH_SIDES_NONE"
OPPORTUNITY_BOTH_SIDES_PARTIAL = "OPPORTUNITY_BOTH_SIDES_PARTIAL"
OPPORTUNITY_BOTH_SIDES_MAJORITY = "OPPORTUNITY_BOTH_SIDES_MAJORITY"
OPPORTUNITY_BOTH_SIDES_COMPLETE = "OPPORTUNITY_BOTH_SIDES_COMPLETE"

# Pipeline readiness
LENDER_READY = "LENDER_READY"
NEAR_READY_24H = "NEAR_READY_24H"
EXECUTION_READY = "EXECUTION_READY"
EXECUTION_REVIEW = "EXECUTION_REVIEW"
EXECUTION_BLOCKED = "EXECUTION_BLOCKED"

# Acquisition basis
PUBLIC_VENDOR_BID_REFERENCE = "PUBLIC_VENDOR_BID_REFERENCE"

MAJORITY_COVERAGE = 0.50
COMPLETE_COVERAGE = 0.90
BASKET_READY_COVERAGE = 0.50
