"""Financing Intelligence — constants (deterministic)."""

from __future__ import annotations

BUILD = "20261001-m3-financing-ops-hardening"

# Source types
SRC_PO_FINANCE = "PO_FINANCE_COMPANY"
SRC_FACTOR = "FACTOR"
SRC_AR_FINANCIER = "ACCOUNTS_RECEIVABLE_FINANCIER"
SRC_ABL = "ASSET_BASED_LENDER"
SRC_SUPPLIER = "SUPPLIER_DISTRIBUTOR"
SRC_MANUFACTURER = "MANUFACTURER"
SRC_BANK = "BANK_CREDIT_FACILITY"
SRC_PRIME = "PRIME_CONTRACTOR_FINANCING"
SRC_OTHER = "OTHER"

SOURCE_TYPES = (
    SRC_PO_FINANCE,
    SRC_FACTOR,
    SRC_AR_FINANCIER,
    SRC_ABL,
    SRC_SUPPLIER,
    SRC_MANUFACTURER,
    SRC_BANK,
    SRC_PRIME,
    SRC_OTHER,
)

PREF_PREFERRED = "PREFERRED"
PREF_BACKUP = "BACKUP"
PREF_AVOID = "AVOID"
PREF_NEUTRAL = "NEUTRAL"

# Tri-state / extended
YES = "YES"
NO = "NO"
CONDITIONAL = "CONDITIONAL"
UNKNOWN = "UNKNOWN"
CASE_BY_CASE = "CASE_BY_CASE"
LIMITED = "LIMITED"
REQUIRED = "REQUIRED"
NOT_REQUIRED = "NOT_REQUIRED"

PG_REQUIRED = "REQUIRED"
PG_NOT_REQUIRED = "NOT_REQUIRED"
PG_LIMITED = "LIMITED"
PG_CASE_BY_CASE = "CASE_BY_CASE"
PG_UNKNOWN = "UNKNOWN"

CREDIT_HARD = "HARD_PULL"
CREDIT_SOFT = "SOFT_PULL"
CREDIT_REVIEW = "REVIEW_ONLY"
CREDIT_NOT_REQUIRED = "NOT_REQUIRED"
CREDIT_UNKNOWN = "UNKNOWN"

# Evidence hierarchy (higher = stronger)
EV_MARKETING_CLAIM = "MARKETING_CLAIM"
EV_VERBAL_CONFIRMATION = "VERBAL_CONFIRMATION"
EV_WRITTEN_CONFIRMATION = "WRITTEN_CONFIRMATION"
EV_DEAL_QUOTE = "DEAL_QUOTE"
EV_ACTUAL_APPROVAL = "ACTUAL_APPROVAL"
EV_ACTUAL_FUNDED_DEAL = "ACTUAL_FUNDED_DEAL"
EV_COMPLETED_TRANSACTION = "COMPLETED_TRANSACTION"

EVIDENCE_RANK = {
    EV_MARKETING_CLAIM: 1,
    EV_VERBAL_CONFIRMATION: 2,
    EV_WRITTEN_CONFIRMATION: 3,
    EV_DEAL_QUOTE: 4,
    EV_ACTUAL_APPROVAL: 5,
    EV_ACTUAL_FUNDED_DEAL: 6,
    EV_COMPLETED_TRANSACTION: 7,
}

# Fact lifecycle
FACT_PROPOSED = "PROPOSED"
FACT_APPROVED = "APPROVED"
FACT_REJECTED = "REJECTED"
FACT_SUPERSEDED = "SUPERSEDED"

# Opportunity financing states
ST_LIKELY_FINANCEABLE = "LIKELY_FINANCEABLE"
ST_NEEDS_LENDER_APPROVAL = "NEEDS_LENDER_APPROVAL"
ST_REQUIRES_SUPPLIER_TERMS = "REQUIRES_SUPPLIER_TERMS"
ST_CAPITAL_CONFIRMATION_REQUIRED = "CAPITAL_CONFIRMATION_REQUIRED"
ST_CAPITAL_STACK_CLOSED = "CAPITAL_STACK_CLOSED"
ST_FINANCING_GAP = "FINANCING_GAP"
ST_EXECUTION_FAIL = "EXECUTION_FAIL"
ST_FINANCING_UNKNOWN = "FINANCING_UNKNOWN"
ST_FINANCEABLE_BUT_TIMING_RISK = "FINANCEABLE_BUT_TIMING_RISK"

# Capital reservation
RES_PROPOSED = "PROPOSED"
RES_CONFIRMED = "CONFIRMED"
RES_RELEASED = "RELEASED"
RES_SPENT = "SPENT"
RES_RETURNED = "RETURNED"
RES_CANCELED = "CANCELED"

# Transaction outcomes
TX_NOT_CONTACTED = "NOT_CONTACTED"
TX_CONTACTED = "CONTACTED"
TX_APPLICATION_STARTED = "APPLICATION_STARTED"
TX_SUBMITTED = "SUBMITTED"
TX_APPROVED = "APPROVED"
TX_DENIED = "DENIED"
TX_FUNDED = "FUNDED"
TX_REPAID = "REPAID"
TX_COMPLETED = "COMPLETED"

# Blocked-profit reasons
BLOCKED_BY_CAPITAL = "BLOCKED_BY_CAPITAL"
BLOCKED_BY_PG = "BLOCKED_BY_PG_REQUIREMENT"
BLOCKED_BY_PERSONAL_CREDIT = "BLOCKED_BY_PERSONAL_CREDIT"
BLOCKED_BY_LENDER_MINIMUM = "BLOCKED_BY_LENDER_MINIMUM"
BLOCKED_BY_SUPPLIER_TERMS = "BLOCKED_BY_SUPPLIER_TERMS"
BLOCKED_BY_FINANCING_GAP = "BLOCKED_BY_FINANCING_GAP"
BLOCKED_BY_LENDER_SIZE = "BLOCKED_BY_LENDER_SIZE_LIMIT"
BLOCKED_BY_UNSUPPORTED_BUYER = "BLOCKED_BY_UNSUPPORTED_BUYER"
BLOCKED_BY_UNSUPPORTED_CONTRACT = "BLOCKED_BY_UNSUPPORTED_CONTRACT_TYPE"
BLOCKED_BY_SUPPLIER_CREDIT = "BLOCKED_BY_SUPPLIER_CREDIT_INSUFFICIENT"
BLOCKED_BY_FREIGHT = "BLOCKED_BY_FREIGHT_NOT_FUNDABLE"
BLOCKED_BY_TIMING = "BLOCKED_BY_TIMING_MISMATCH"
BLOCKED_BY_ACQUISITION_UNKNOWN = "BLOCKED_BY_ACQUISITION_COST_UNKNOWN"
BLOCKED_BY_APPROVAL_NEEDED = "BLOCKED_BY_TRANSACTION_APPROVAL_NEEDED"
BLOCKED_BY_INFO_MISSING = "BLOCKED_BY_FINANCING_INFORMATION_MISSING"
