"""OpenGov authentication status constants (aligned with BidNet)."""

from __future__ import annotations

NOT_CONNECTED = "NOT_CONNECTED"
CONNECTED = "CONNECTED"
SESSION_REUSED = "SESSION_REUSED"
LOGIN_REQUIRED = "LOGIN_REQUIRED"
LOGIN_SUCCESS = "LOGIN_SUCCESS"
AUTH_CHALLENGE = "AUTH_CHALLENGE"
AUTH_FAILED = "AUTH_FAILED"
EXPIRED = "EXPIRED"
DISABLED = "DISABLED"

AUTHENTICATED_STATUSES = frozenset({CONNECTED, SESSION_REUSED, LOGIN_SUCCESS})
BLOCKING_STATUSES = frozenset(
    {AUTH_CHALLENGE, AUTH_FAILED, EXPIRED, DISABLED, LOGIN_REQUIRED, NOT_CONNECTED}
)

# Portal / entity outcome classification (§8)
WORKING = "WORKING"
WORKING_PUBLIC = "WORKING_PUBLIC"
WORKING_AUTH = "WORKING_AUTH"
NETWORK_TIMEOUT = "NETWORK_TIMEOUT"
PARTIAL = "PARTIAL"
AUTH_REQUIRED = "AUTH_REQUIRED"
MOVED = "MOVED"
BROKEN_PARSER = "BROKEN_PARSER"
NO_OPEN_BIDS = "NO_OPEN_BIDS"
INVALID_PORTAL = "INVALID_PORTAL"
SOURCE_ERROR = "SOURCE_ERROR"
ANTI_BOT = "ANTI_BOT"
RECOVERY_BLOCKED = "RECOVERY_BLOCKED"

# Route-resolved working statuses (non-terminal ANTI_BOT is never final when a route works)
WORKING_STRUCTURED = "WORKING_STRUCTURED"
WORKING_EMBED = "WORKING_EMBED"
WORKING_PAGE_STATE = "WORKING_PAGE_STATE"
WORKING_AUTH_REQUEST = "WORKING_AUTH_REQUEST"
WORKING_GLOBAL_SEARCH = "WORKING_GLOBAL_SEARCH"
WORKING_AGENCY_FALLBACK = "WORKING_AGENCY_FALLBACK"
WORKING_BROWSER = "WORKING_BROWSER"

SUCCESS_STATUSES = frozenset(
    {
        WORKING,
        WORKING_PUBLIC,
        WORKING_AUTH,
        PARTIAL,
        WORKING_STRUCTURED,
        WORKING_EMBED,
        WORKING_PAGE_STATE,
        WORKING_AUTH_REQUEST,
        WORKING_GLOBAL_SEARCH,
        WORKING_AGENCY_FALLBACK,
        WORKING_BROWSER,
    }
)
